SELECT
	A.COD_SCENARIO,
	A.COD_PERIODO,
	A.COD_AZIENDA AS BUSINESS_UNIT,
	A.COD_AZI_CTP AS AFFILIATE,
	A.COD_CONTO AS GL_KEY_CODE,
	A.COD_CATEGORIA AS CATEGORY,
	A.COD_DEST1 AS GL_ACCOUNT,
	CASE
		WHEN SUBSTR(A.COD_DEST2, 3) = 'BLC'
			THEN SUBSTR(A.COD_DEST2, 5)
		ELSE NULL
	END AS OPERATING_UNIT,
	CASE
		WHEN SUBSTR(A.COD_DEST2, 3) = 'DPT'
			THEN SUBSTR(A.COD_DEST2, 5)
		ELSE NULL
	END AS DEPTID,
	CASE
		WHEN SUBSTR(A.COD_DEST2_CTP, 3) = 'BLC'
			THEN SUBSTR(A.COD_DEST2_CTP, 5)
		ELSE NULL
	END AS OPERATING_UNIT,
	CASE
		WHEN SUBSTR(A.COD_DEST2_CTP, 3) = 'DPT'
			THEN SUBSTR(A.COD_DEST2_CTP, 5)
		ELSE NULL
	END AS DEPTID,
	A.COD_DEST3 AS PRODUCT,
	A.COD_DEST4 AS CUSTOMER_CLASS,
	A.COD_DEST5 AS CALL_CODE,
	A.NOTE AS PROJECTID
	A.COD_VALUTA AS BASE_CURRENCY,
	A.IMPORTO AS BASE_EQUIVALENT,
	A.COD_VALUTA_ORIGINARIA AS CURRENCY_CD,
	A.IMPORTO_VALUTA_ORIGINARIA AS FOREIGN_EQUIVALENT
FROM
	(
		SELECT
			'ORIGINAL' AS DATA_SOURCE
			COD_CONTO_REP,
			COD_SCENARIO,
			COD_PERIODO,
			COD_AZIENDA,
			COD_AZI_CTP,
			COD_CONTO,
			COD_CATEGORIA,
			COD_DEST1,
			COD_DEST2,
			COD_DEST2_CTP,
			COD_DEST3,
			COD_DEST4,
			COD_DEST5,
			NOTE,
			COD_VALUTA,
			SUM(IMPORTO) AS IMPORTO,
			COD_VALUTA_ORIGINARIA,
			SUM(IMPORTO_VALUTA_ORIGINARIA) AS IMPORTO_VALUTA_ORIGINARIA
		FROM
			(
				SELECT
					A.COD_CONTO AS COD_CONTO_REP,
					B.COD_SCENARIO,
					B.COD_PERIODO,
					B.COD_AZIENDA,
					RB_F_TGK_SANITIZE_CODE(NULL) AS COD_AZI_CTP,
					B.COD_CONTO,
					B.COD_CATEGORIA,
					B.COD_DEST1,
					B.COD_DEST2,
					RB_F_TGK_SANITIZE_CODE(NULL) AS COD_DEST2_CTP,
					B.COD_DEST3,
					B.COD_DEST4,
					B.COD_DEST5,
					B.NOTE,
					B.COD_VALUTA,
					B.IMPORTO,
					B.COD_VALUTA_ORIGINARIA,
					B.IMPORTO_VALUTA_ORIGINARIA
				FROM
					RB_DRILL_INSTRUMENT A
					INNER JOIN
					DATI_SALDI_LORDI B
					ON
						A.OID_FORM_DATI = B.OID_FORM_DATI
					INNER JOIN
					(
						SELECT DISTINCT
							COD_SCENARIO,
							COD_PERIODO,
							COD_CONTO
						FROM
							DATI_SALDI_LORDI
						WHERE
							COD_CATEGORIA = 'ORI_REP'
							AND PROVENIENZA LIKE 'MAP_REP_' || ${A1} || '_' || ${B1} || '_%' 
					) C
					ON
						A.COD_SCENARIO = C.COD_SCENARIO
						AND A.COD_PERIODO = C.COD_PERIODO
						AND A.COD_CONTO = C.COD_CONTO
				WHERE
					A.COD_SCENARIO IN (${$Scenario.code})
					AND A.COD_PERIODO IN (${$Period.code})
					AND A.PROVENIENZA LIKE 'MAP_REP_' || ${A1} || '_' || ${B1} || '_%'
					AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 3) = ${A1}
					AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 4) = ${B1}
					AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 7) IS NULL
					AND A.COD_CATEGORIA IN ('ORI_REP')
				UNION ALL
				SELECT
					K.COD_CONTO_REP,
					D.COD_SCENARIO,
					D.COD_PERIODO,
					D.COD_AZIENDA,
					RB_F_TGK_SANITIZE_CODE(NULL) AS COD_AZI_CTP,
					D.COD_CONTO,
					D.COD_CATEGORIA,
					D.COD_DEST1,
					D.COD_DEST2,
					RB_F_TGK_SANITIZE_CODE(NULL) AS COD_DEST2_CTP,
					D.COD_DEST3,
					D.COD_DEST4,
					D.COD_DEST5,
					D.NOTE,
					D.COD_VALUTA,
					-D.IMPORTO AS IMPORTO,
					D.COD_VALUTA_DOC AS COD_VALUTA_ORIGINARIA,
					-D.IMPORTO_VALUTA_DOC AS IMPORTO_VALUTA_ORIGINARIA
				FROM
					(
						SELECT DISTINCT
							A.COD_CONTO AS COD_CONTO_REP,
							B.COD_SCENARIO,
							B.COD_PERIODO,
							B.COD_AZIENDA,
							B.COD_CONTO,
							B.COD_CATEGORIA,
							B.COD_DEST1,
							B.COD_DEST2,
							B.COD_DEST3,
							B.COD_DEST4,
							B.COD_DEST5,
							B.NOTE,
							B.COD_VALUTA,
							B.COD_VALUTA_ORIGINARIA
						FROM
							RB_DRILL_INSTRUMENT A
							INNER JOIN
							DATI_SALDI_LORDI B
							ON
								A.OID_FORM_DATI = B.OID_FORM_DATI
							INNER JOIN
							(
								SELECT DISTINCT
									COD_SCENARIO,
									COD_PERIODO,
									COD_CONTO
								FROM
									DATI_SALDI_LORDI
								WHERE
									COD_CATEGORIA = 'ORI_REP'
									AND PROVENIENZA LIKE 'MAP_REP_' || ${A1} || '_' || ${B1} || '_%' 
							) C
							ON
								A.COD_SCENARIO = C.COD_SCENARIO
								AND A.COD_PERIODO = C.COD_PERIODO
								AND A.COD_CONTO = C.COD_CONTO
						WHERE
							A.COD_SCENARIO IN (${$Scenario.code})
							AND A.COD_PERIODO IN (${$Period.code})
							AND A.PROVENIENZA LIKE 'MAP_REP_' || ${A1} || '_' || ${B1} || '_%'
							AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 3) = ${A1}
							AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 4) = ${B1}
							AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 7) IS NULL
							AND A.COD_CATEGORIA IN ('ORI_REP')
					) K
					INNER JOIN
					DATA_SALDI_IC D
					ON
						K.COD_SCENARIO = D.COD_SCENARIO
						AND K.COD_PERIODO = D.COD_PERIODO
						AND K.COD_CONTO = D.COD_CONTO
						AND K.COD_CATEGORIA = D.COD_CATEGORIA
						AND K.DEST1 = D.DEST1
						AND K.DEST2 = D.DEST2
						AND K.DEST3 = D.DEST3
						AND K.DEST4 = D.DEST4
						AND K.DEST5 = D.DEST5
						AND K.COD_VALUTA = D.COD_VALUTA
						AND K.COD_VALUTA_ORIGINARIA = D.COD_VALUTA_ORIGINARIA
						AND K.NOTE = D.NOTE
				UNION ALL
				SELECT
					K.COD_CONTO_REP,
					D.COD_SCENARIO,
					D.COD_PERIODO,
					D.COD_AZIENDA,
					D.COD_AZI_CTP,
					D.COD_CONTO,
					D.COD_CATEGORIA,
					D.COD_DEST1,
					D.COD_DEST2,
					D.COD_DEST2_CTP,
					D.COD_DEST3,
					D.COD_DEST4,
					D.COD_DEST5,
					D.NOTE,
					D.COD_VALUTA,
					-D.IMPORTO AS IMPORTO,
					D.COD_VALUTA_DOC AS COD_VALUTA_ORIGINARIA,
					-D.IMPORTO_VALUTA_DOC AS IMPORTO_VALUTA_ORIGINARIA
				FROM
					(
						SELECT DISTINCT
							A.COD_CONTO AS COD_CONTO_REP,
							B.COD_SCENARIO,
							B.COD_PERIODO,
							B.COD_AZIENDA,
							B.COD_CONTO,
							B.COD_CATEGORIA,
							B.COD_DEST1,
							B.COD_DEST2,
							B.COD_DEST3,
							B.COD_DEST4,
							B.COD_DEST5,
							B.NOTE,
							B.COD_VALUTA,
							B.COD_VALUTA_ORIGINARIA
						FROM
							RB_DRILL_INSTRUMENT A
							INNER JOIN
							DATI_SALDI_LORDI B
							ON
								A.OID_FORM_DATI = B.OID_FORM_DATI
							INNER JOIN
							(
								SELECT DISTINCT
									COD_SCENARIO,
									COD_PERIODO,
									COD_CONTO
								FROM
									DATI_SALDI_LORDI
								WHERE
									COD_CATEGORIA = 'ORI_REP'
									AND PROVENIENZA LIKE 'MAP_REP_' || ${A1} || '_' || ${B1} || '_%' 
							) C
							ON
								A.COD_SCENARIO = C.COD_SCENARIO
								AND A.COD_PERIODO = C.COD_PERIODO
								AND A.COD_CONTO = C.COD_CONTO
						WHERE
							A.COD_SCENARIO IN (${$Scenario.code})
							AND A.COD_PERIODO IN (${$Period.code})
							AND A.PROVENIENZA LIKE 'MAP_REP_' || ${A1} || '_' || ${B1} || '_%'
							AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 3) = ${A1}
							AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 4) = ${B1}
							AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 7) IS NULL
							AND A.COD_CATEGORIA IN ('ORI_REP')
					) K
					INNER JOIN
					DATA_SALDI_IC D
					ON
						K.COD_SCENARIO = D.COD_SCENARIO
						AND K.COD_PERIODO = D.COD_PERIODO
						AND K.COD_CONTO = D.COD_CONTO
						AND K.COD_CATEGORIA = D.COD_CATEGORIA
						AND K.DEST1 = D.DEST1
						AND K.DEST2 = D.DEST2
						AND K.DEST3 = D.DEST3
						AND K.DEST4 = D.DEST4
						AND K.DEST5 = D.DEST5
						AND K.COD_VALUTA = D.COD_VALUTA
						AND K.COD_VALUTA_ORIGINARIA = D.COD_VALUTA_ORIGINARIA
						AND K.NOTE = D.NOTE
				)
				GROUP BY
					COD_CONTO_REP,
					COD_SCENARIO,
					COD_PERIODO,
					COD_AZIENDA,
					COD_AZI_CTP,
					COD_CONTO,
					COD_CATEGORIA,
					COD_DEST1,
					COD_DEST2,
					COD_DEST2_CTP,
					COD_DEST3,
					COD_DEST4,
					COD_DEST5,
					NOTE,
					COD_VALUTA
					COD_VALUTA_ORIGINARIA
			) A
WHERE	
	COD_SCENARIO = ${A1}
	AND COD_PERIODO = ${B1}