SELECT
    FD.COD_PROSPETTO AS COD_TAPE,
    CAST(DATA.RB_ROWID AS VARCHAR2(255)) AS RB_ROWID,
    DATA.MONTH_END_DATE,
    DATA.REPORTING_ENTITY,
    DATA.INSTRUMENT,
    DATA.INTERCOMPANY,
    DATA.CALL_CODE,
    DATA.CALL_CODE_DESC,
    DATA.GL_KEY_CODE,
    DATA.GL_KEY_CODE_DESC,
    DATA.CONSOL_NODE,
    DATA.BUSINESS_UNIT,
    DATA.CURRENCY_CODE,
    DATA.FOREIGN_AMOUNT,
    DATA.CURRENCY_USQ,
    DATA.BASE_EQUIVALENT,
    DATA.MATURITY_DATE,
    DATA.REMAINING_MATURITY_DAYS,
    DATA.MATURITY_BUCKETS,
    DATA.MATURITY_BUCKETS_2,
    DATA.CUSTOMER_ID,
    DATA."DEPO_NON-DEPO",
    DATA.FOREIGN_DOMESTIC,
    DATA.PRINCIPAL_ORIG_CCY,
    DATA.DISCOUNT_GIVEN_ORIG_CCY,
    DATA.OVERDRAFT_CASH_ORIG_CCY,
    DATA.PRINCIPAL_BASE_EQ,
    DATA.DISCOUNT_GIVEN_BASE_EQ,
    DATA.OVERDRAFT_CASH_BASE_EQ,
    DATA.PROD_TYPE_DESC,
    DATA.CUSTOMER_TYPE,
    DATA.UMD_1,
    DATA.SOURCE,
    DATA.UMD_2,
    DATA.UMD_3,
    DATA.UMD_4,
    DATA.TRADE_ID,
    DATA.REPORTABLE_Y_N,
    DATA.BU,
    DATA.ACCOUNT,
    DATA.PRODUCT,
    DATA.OPERATING_UNIT,
    DATA.DEPTID,
    DATA.CUST_CLASS,
    DATA.AFFILIATE,
    DATA.CIF_TYPE,
    DATA.CIF_TYPE_DESCRIPTION,
    DATA.DISC_GIVEN_CALL_CODE_CODEBLOCK,
    DATA.OVRDRFT_CASH_CALL_CODE_CODEBLK,
    DATA.FILLER_1,
    DATA.FILLER_2,
    DATA.FILLER_3,
    DATA.FILLER_4,
    DATA.FILLER_5,
    DATA.FILLER_6,
    DATA.FILLER_7,
    DATA.FILLER_8,
    DATA.FILLER_9,
    DATA.FILLER_10,
    DATA.FILLER_11,
    DATA.FILLER_12,
    DATA.FILLER_13,
    DATA.FILLER_14,
    DATA.FILLER_15,
    DATA.FILLER_16,
    DATA.FILLER_17,
    DATA.FILLER_18,
    DATA.FILLER_19,
    DATA.FILLER_20,
    DATA.FILLER_21,
    DATA.FILLER_22,
    DATA.FILLER_23,
    DATA.FILLER_24,
    DATA.FILLER_25,
    ${CONCATENATE($Account.code, " (", PARENT($Account(HIERARCHY("RE"))).code, " - ", PARENT($Account(HIERARCHY("RE"))).desc, ": ", $Account.attribute4, " - ", $Account.attribute5, ")")} AS LINE_ITEM
FROM
  RB_DRILL_INSTRUMENT DRILL
  INNER JOIN
  FORM_DATI FD
  ON
    DRILL.OID_FORM_DATI = FD.OID_FORM_DATI
  INNER JOIN
  RB_V_BORROWINGS DATA
  ON
    FD.DATA_1 = DATA.MONTH_END_DATE
    AND FD.TESTO_1 = DATA.REPORTING_ENTITY
    AND CAST(FD.IMPORTO_14 AS VARCHAR2(255)) = CAST(DATA.RB_ROWID AS VARCHAR2(255))
WHERE
  DRILL.COD_SCENARIO IN (${$Scenario.code})
  AND DRILL.COD_PERIODO IN (${$Period.code})
  AND DRILL.COD_AZIENDA IN (${$Entity.code})
  AND DRILL.COD_CONTO IN (${$Account.code})
  AND DRILL.COD_DEST1 IN (${$Cust_Dim1.code})
  AND DRILL.COD_DEST2 IN (${$Cust_Dim2.code})
  AND DRILL.COD_DEST3 IN (${$Cust_Dim3.code})
  AND DRILL.COD_DEST4 IN (${$Cust_Dim4.code})
  AND DRILL.COD_DEST5 IN (${$Cust_Dim5.code})
  AND DRILL.COD_CATEGORIA IN (${$Category.code})
UNION ALL
SELECT
    'ADJUSTMENTS' AS COD_TAPE,
    DATA.NUM_RETTIFICA AS RB_ROWID,
    SP.DATA_FINE AS MONTH_END_DATE,
    NULL AS REPORTING_ENTITY,
    NULL AS INSTRUMENT,
    NULL AS INTERCOMPANY,
    NULL AS CALL_CODE,
    NULL AS CALL_CODE_DESC,
    NULL AS GL_KEY_CODE,
    NULL AS GL_KEY_CODE_DESC,
    NULL AS CONSOL_NODE,
    DATA.COD_AZIENDA AS BUSINESS_UNIT,
    DATA.COD_VALUTA2 AS CURRENCY_CODE,
    DATA.IMPORTO2 AS FOREIGN_AMOUNT,
    DATA.COD_VALUTA AS CURRENCY_USQ,
    DATA.IMPORTO2 AS BASE_EQUIVALENT,
    NULL AS MATURITY_DATE,
    NULL AS REMAINING_MATURITY_DAYS,
    NULL AS MATURITY_BUCKETS,
    NULL AS MATURITY_BUCKETS_2,
    NULL AS CUSTOMER_ID,
    NULL AS "DEPO_NON-DEPO",
    NULL AS FOREIGN_DOMESTIC,
    NULL AS PRINCIPAL_ORIG_CCY,
    NULL AS DISCOUNT_GIVEN_ORIG_CCY,
    NULL AS OVERDRAFT_CASH_ORIG_CCY,
    NULL AS PRINCIPAL_BASE_EQ,
    NULL AS DISCOUNT_GIVEN_BASE_EQ,
    NULL AS OVERDRAFT_CASH_BASE_EQ,
    NULL AS PROD_TYPE_DESC,
    NULL AS CUSTOMER_TYPE,
    NULL AS UMD_1,
    A.NOTE AS SOURCE,
    NULL AS UMD_2,
    NULL AS UMD_3,
    NULL AS UMD_4,
    NULL AS TRADE_ID,
    NULL AS REPORTABLE_Y_N,
    NULL AS BU,
    DATA.COD_DEST1 AS ACCOUNT,
    DATA.COD_DEST3 AS PRODUCT,
    CASE
        WHEN SUBSTR(DATA.COD_DEST2, 1, 4) = 'BLC_'
            THEN SUBSTR(DATA.COD_DEST2, 5)
        ELSE NULL
    END AS OPERATING_UNIT,
    CASE
        WHEN SUBSTR(DATA.COD_DEST2, 1, 4) = 'DPT_'
            THEN SUBSTR(DATA.COD_DEST2, 5)
        ELSE NULL
    END AS DEPTID,
    DATA.COD_DEST4 AS CUST_CLASS,
    DATA.COD_AZI_CTP AS AFFILIATE,
    NULL AS CIF_TYPE,
    NULL AS CIF_TYPE_DESCRIPTION,
    NULL AS DISC_GIVEN_CALL_CODE_CODEBLOCK,
    NULL AS OVRDRFT_CASH_CALL_CODE_CODEBLK,
    NULL AS FILLER_1,
    NULL AS FILLER_2,
    NULL AS FILLER_3,
    NULL AS FILLER_4,
    NULL AS FILLER_5,
    NULL AS FILLER_6,
    NULL AS FILLER_7,
    NULL AS FILLER_8,
    NULL AS FILLER_9,
    NULL AS FILLER_10,
    NULL AS FILLER_11,
    NULL AS FILLER_12,
    NULL AS FILLER_13,
    NULL AS FILLER_14,
    NULL AS FILLER_15,
    NULL AS FILLER_16,
    NULL AS FILLER_17,
    NULL AS FILLER_18,
    NULL AS FILLER_19,
    NULL AS FILLER_20,
    NULL AS FILLER_21,
    NULL AS FILLER_22,
    NULL AS FILLER_23,
    NULL AS FILLER_24,
    NULL AS FILLER_25,
    ${CONCATENATE($Account.code, " (", PARENT($Account(HIERARCHY("RE"))).code, " - ", PARENT($Account(HIERARCHY("RE"))).desc, ": ", $Account.attribute4, " - ", $Account.attribute5, ")")} AS LINE_ITEM
FROM
    DATI_RETT_RIGA DATA
    LEFT OUTER JOIN
    DATI_RETT A
    ON
        DATA.COD_SCENARIO = A.COD_SCENARIO
        AND DATA.COD_PERIODO = A.COD_PERIODO
        AND DATA.NUM_RETTIFICA = A.NUM_RETTIFICA
    LEFT OUTER JOIN
    SCENARIO_PERIODO SP
    ON
        DATA.COD_SCENARIO = SP.COD_SCENARIO
        AND DATA.COD_PERIODO = SP.COD_PERIODO
    LEFT OUTER JOIN
    CONTO C
    ON
        DATA.COD_CONTO = C.COD_CONTO
WHERE
  DATA.COD_SCENARIO IN (${$Scenario.code}) 
  AND DATA.COD_PERIODO IN (${$Period.code})
  AND DATA.COD_AZIENDA IN (${$Entity.code})
  AND DATA.COD_CONTO IN (${$Account.code})
  AND DATA.COD_DEST1 IN (${$Cust_Dim1.code})
  AND DATA.COD_DEST2 IN (${$Cust_Dim2.code})
  AND DATA.COD_DEST3 IN (${$Cust_Dim3.code})
  AND DATA.COD_DEST4 IN (${$Cust_Dim4.code})
  AND DATA.COD_DEST5 IN (${$Cust_Dim5.code})
  AND DATA.COD_CATEGORIA IN (${$Category.code})