SELECT
(
  SELECT
    SUM(FOREIGN_AMOUNT) AS FOREIGN_AMOUNT,
	SUM(BASE_EQUIVALENT) AS BASE_EQUIVALENT,
	SUM(PRINCIPAL_BASE_EQ) AS PRINCIPAL_BASE_EQ,
	SUM(DISCOUNT_GIVEN_BASE_EQ) AS DISCOUNT_GIVEN_BASE_EQ,
	SUM(OVERDRAFT_CASH_BASE_EQ) AS OVERDRAFT_CASH_BASE_EQ
  FROM
    RB_V_HST_BORROWINGS S
  WHERE
    (
      USERUPD = ${user.code}
      AND (EXISTS(SELECT 1 FROM RB_V_HST_BORROWINGS WHERE USERUPD = ${user.code}))
    )
    OR (
      DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_BORROWINGS)
      AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_BORROWINGS WHERE USERUPD = ${user.code}))
    )
) AS STG,
(
  SELECT
    SUM(IMPORTO_2) AS FOREIGN_AMOUNT,
	SUM(IMPORTO_1) AS BASE_EQUIVALENT,
	SUM(IMPORTO_7) AS PRINCIPAL_BASE_EQ,
	SUM(IMPORTO_8) AS DISCOUNT_GIVEN_BASE_EQ,
	SUM(IMPORTO_9) AS OVERDRAFT_CASH_BASE_EQ
  FROM
    FORM_DATI A
    INNER JOIN
    (
      SELECT DISTINCT
        RB_F_TGK_CREATE_SCENARIO_CODE(MONTH_END_DATE) AS COD_SCENARIO,
        RB_F_TGK_CREATE_PERIOD_CODE(MONTH_END_DATE) AS COD_PERIODO,
        REPORTING_ENTITY
      FROM
        RB_V_HST_BORROWINGS S
      WHERE
        (
          USERUPD = ${user.code}
          AND (EXISTS(SELECT 1 FROM RB_V_HST_BORROWINGS WHERE USERUPD = ${user.code}))
        )
        OR (
          DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_BORROWINGS)
          AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_BORROWINGS WHERE USERUPD = ${user.code}))
        )
    ) S
  ON
	A.COD_SCENARIO = S.COD_SCENARIO
	AND A.COD_PERIODO = S.COD_PERIODO
	AND A.TESTO_1 = S.REPORTING_ENTITY
  WHERE
    A.COD_PROSPETTO = 'BORROWINGS'
) AS APP
FROM
  DUAL