SELECT
    RB_ROWID,
    H.MONTH_END_DATE,
    REPORTING_ENTITY,
    INSTRUMENT,
    INTERCOMPANY,
    CALL_CODE,
    CALL_CODE_DESC,
    GL_KEY_CODE,
    GL_KEY_CODE_DESC,
    CONSOL_NODE,
    H.BUSINESS_UNIT,
    CURRENCY_CODE,
    FOREIGN_AMOUNT,
    CURRENCY_USQ,
    BASE_EQUIVALENT,
    MATURITY_DATE,
    REMAINING_MATURITY_DAYS,
    MATURITY_BUCKETS,
    MATURITY_BUCKETS_2,
    CUSTOMER_ID,
    "DEPO_NON-DEPO",
    FOREIGN_DOMESTIC,
    PRINCIPAL_ORIG_CCY,
    DISCOUNT_GIVEN_ORIG_CCY,
    OVERDRAFT_CASH_ORIG_CCY,
    PRINCIPAL_BASE_EQ,
    DISCOUNT_GIVEN_BASE_EQ,
    OVERDRAFT_CASH_BASE_EQ,
    PROD_TYPE_DESC,
    CUSTOMER_TYPE,
    UMD_1,
    SOURCE,
    UMD_2,
    UMD_3,
    UMD_4,
    TRADE_ID,
    REPORTABLE_Y_N,
    BU,
    ACCOUNT,
    PRODUCT,
    OPERATING_UNIT,
    DEPTID,
    CUST_CLASS,
    AFFILIATE,
    CIF_TYPE,
    CIF_TYPE_DESCRIPTION,
    DISC_GIVEN_CALL_CODE_CODEBLOCK,
    OVRDRFT_CASH_CALL_CODE_CODEBLK,
    FILLER_1,
    FILLER_2_ORIGINATION_DATE,
    FILLER_3_ORIGINAL_MATURITY,
    FILLER_4_CUSTOMER_NAME,
    FILLER_5_SECURED_BORROWINGS,
    FILLER_6_IBF_ONLY_COLUMN_YN,
    FILLER_7_RES_COUNTRY,
    FILLER_8_RISK_COUNTRY,
    FILLER_9,
    FILLER_10,
    FILLER_11,
    FILLER_12,
    FILLER_13,
    FILLER_14,
    FILLER_15,
    FILLER_16,
    FILLER_17,
    FILLER_18,
    FILLER_19,
    FILLER_20,
    FILLER_21,
    FILLER_22,
    FILLER_23,
    FILLER_24,
    FILLER_25
FROM
    RB_V_BORROWINGS H
    INNER JOIN
    (
        SELECT DISTINCT
            DATA_1 AS MONTH_END_DATE,
            COD_AZIENDA AS BUSINESS_UNIT
        FROM
            FORM_DATI
        WHERE
            COD_SCENARIO = ${A1}
            AND COD_PERIODO = ${B1}
            AND COD_PROSPETTO = 'BORROWINGS'
            AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )
    ) F
    ON
        H.MONTH_END_DATE = F.MONTH_END_DATE
        AND RB_F_TGK_SANITIZE_CODE(H.BUSINESS_UNIT) = F.BUSINESS_UNIT
  