SELECT
	FD.COD_PROSPETTO AS COD_TAPE,
	CAST(DATA.RB_ROWID AS VARCHAR2(255)) AS RB_ROWID,
	DATA.MONTH_END_DATE,
	DATA.REPORTING_ENTITY,
	DATA.INSTRUMENT,
	DATA.INTERCOMPANY,
	DATA.CONSOL_NODE,
	DATA.BUSINESS_UNIT,
	DATA.GL_KEY_CODE,
	DATA.GL_KEY_CODE_DESC,
	DATA.CALL_CODE,
	DATA.CALL_CODE_DESC,
	DATA.ACCRUAL_VALUE,
	DATA.CLEAN_PRICE_VALUE,
	DATA.DIRTY_PRICE_VALUE,
	DATA.MANUAL_ADJUSTMENTS,
	DATA.CREDIT_ADJ,
	DATA.CREDIT_VALUATION_ADJUSTMENT,
	DATA.USQ_NOTIONAL,
	DATA.POSITIVE_NEGATIVE,
	DATA.BUY_SELL_INDICATOR,
	DATA.MATURITY_PCT_WEIGHT,
	DATA.ADD_ON,
	DATA.REPLACEMENT_VALUE,
	DATA.CREDIT_EQUIVALENT,
	DATA.CPTY_WGHT,
	DATA.AMT_BOUGHT,
	DATA.AMT_SOLD,
	DATA.CCY_RECEIVE,
	DATA.CCY_PAY,
	DATA.SOURCE,
	DATA.ACC_INT_REC_GL_US_GAAP_BASE_EQ,
	DATA.UNSET_TRADE_GL_US_GAAP_BASE_EQ,
	DATA.RECEIVABLES_ADVANCES_BASE_EQ,
	DATA.UNRLZED_PLG_GL_US_GAAP_BASE_EQ,
	DATA.UNREAL_PLG_CCY_SWAP_US_BASE_EQ,
	DATA.ACC_INT_PAY_GL_US_GAAP_BASE_EQ,
	DATA.ACC_FEE_PAY_GL_US_GAAP_BASE_EQ,
	DATA.UNSET_TRADE_PAYABLE_US_BASE_EQ,
	DATA.UNRLZED_PLL_GL_US_GAAP_BASE_EQ,
	DATA.UNREAL_PLL_CCY_SWAP_US_BASE_EQ,
	DATA.MARCA_PROVISION,
	DATA.NOTL_OPT_BUY_US_GAAP_BASE_EQ,
	DATA.NOTL_SWAP_BUY_US_GAAP_BASE_EQ,
	DATA.NOTL_OPT_GL_US_GAAP_BASE_EQ,
	DATA.NOTL_OPT_SOLD_US_GAAP_BASE_EQ,
	DATA.NOTL_SWAP_SOLD_US_GAAP_BASE_EQ,
	DATA.IBF_ONLY_RAL_COLUMN_B_YN,
	DATA.REGULATORY_RISK_RATINGS,
	DATA.LEVEL_FAIR_VALUE,
	DATA.CRC_RATING,
	DATA.UMD1,
	DATA.UMD2,
	DATA.UMD3,
	DATA.MATURITY_DATE,
	DATA.REMAINING_MATURITY,
	DATA.MATURITY_BUCKETS,
	DATA.ONE_YEAR_OR_LESS,
	DATA.ONE_TO_FIVE_YEARS,
	DATA.GREATER_THAN_FIVE_YEARS,
	DATA.ACCOUNTING_CLASSIFICATION,
	DATA.BA_CODE,
	DATA.ENTITY_ENT_CODE,
	DATA.COUNTERPARTY_ENT_CODE,
	DATA.COVERED_MARKET_RISK_RULE,
	DATA.AFFIRMED_REG_RPT_CAP_GUARANTEE,
	DATA.SECURITY_DESCRIPTION,
	DATA.INVESTMENT_GRADE,
	DATA.SUBINVESTMENT_GRADE,
	DATA.UMD4,
	DATA.UMD5,
	DATA.UMD6,
	DATA.TRADE_ID,
	DATA.CUSTOMER_ID,
	DATA.RELATED_DEP_INST,
	DATA.CUSTOMER_NAME,
	DATA.CUSTOMER_TYPE,
	DATA.CITY,
	DATA.OPERATING_STATE,
	DATA.FOREIGN_DOMESTIC,
	DATA.COUNTRY_CODE,
	DATA.COUNTRY_DESC,
	DATA.RELATION_ID,
	DATA.FX_RATE_REC,
	DATA.FX_RATE_PAY,
	DATA.STRIKE_PRICE,
	DATA.FIXED_OR_VARIABLE,
	DATA.RECEIVE_INTEREST_RATE,
	DATA.PAY_INTEREST_RATE,
	DATA.INDEX_RATE_ADD,
	DATA.FLOAT_FREQ,
	DATA.LAST_RATE_RESET_DATE,
	DATA.NEXT_RATE_RESET_DATE,
	DATA.BRANCH_SUBSIDIARY,
	DATA.START_DATE,
	DATA.TRADE_DATE,
	DATA.SETTLE_DATE,
	DATA.UMD7,
	DATA.UMD8,
	DATA.UMD9,
	DATA.UMD10,
	DATA.ACCOUNT,
	DATA.PRODUCT,
	DATA.OPERATING_UNIT,
	DATA.AFFILIATE,
	DATA.CUST_CLASS,
	DATA.CODEBLOCK,
	DATA.ACCRUAL_CODEBLOCK,
	DATA.UNREALIZED_CODEBLOCK,
	DATA.CALL_CODE_CONCAT,
	DATA.FILLER_1,
	DATA.FILLER_2,
	DATA.FILLER_3,
	DATA.FILLER_4,
	DATA.FILLER_5,
	DATA.FILLER_6,
	DATA.FILLER_7,
	DATA.FILLER_8,
	DATA.FILLER_9,
	DATA.FILLER_10,
	DATA.FILLER_11,
	DATA.FILLER_12,
	DATA.FILLER_13,
	DATA.FILLER_14,
	DATA.FILLER_15,
	DATA.FILLER_16,
	DATA.FILLER_17,
	DATA.FILLER_18,
	DATA.FILLER_19,
	DATA.FILLER_20,
	DATA.FILLER_21,
	DATA.FILLER_22,
	DATA.FILLER_23,
	DATA.FILLER_24,
	DATA.FILLER_25,
	${CONCATENATE($Account.code, " (", PARENT($Account(HIERARCHY("RE"))).code, " - ", PARENT($Account(HIERARCHY("RE"))).desc, ": ", $Account.attribute4, " - ", $Account.attribute5, ")")} AS LINE_ITEM
FROM
  RB_DRILL_INSTRUMENT DRILL
  INNER JOIN
  FORM_DATI FD
  ON
    DRILL.OID_FORM_DATI = FD.OID_FORM_DATI
  INNER JOIN
  RB_V_DERIVATIVES DATA
  ON
	FD.DATA_1 = DATA.MONTH_END_DATE
	AND FD.TESTO_1 = DATA.REPORTING_ENTITY
	AND CAST(FD.IMPORTO_1 AS VARCHAR2(255)) = CAST(DATA.RB_ROWID AS VARCHAR2(255))
WHERE
  DRILL.COD_SCENARIO IN (${$Scenario.code})
  AND DRILL.COD_PERIODO IN (${$Period.code})
  AND DRILL.COD_AZIENDA IN (${$Entity.code})
  AND DRILL.COD_CONTO IN (${$Account.code})
  AND DRILL.COD_DEST1 IN (${$Cust_Dim1.code})
  AND DRILL.COD_DEST2 IN (${$Cust_Dim2.code})
  AND DRILL.COD_DEST3 IN (${$Cust_Dim3.code})
  AND DRILL.COD_DEST4 IN (${$Cust_Dim4.code})
  AND DRILL.COD_DEST5 IN (${$Cust_Dim5.code})
  AND DRILL.COD_CATEGORIA IN (${$Category.code})
UNION ALL
SELECT
	'ADJUSTMENTS' AS COD_TAPE,
	DATA.NUM_RETTIFICA AS RB_ROWID,
	SP.DATA_FINE AS MONTH_END_DATE,
	NULL AS REPORTING_ENTITY,
	NULL AS INSTRUMENT,
	NULL AS INTERCOMPANY,
	NULL AS CONSOL_NODE,
	COD_AZIENDA AS BUSINESS_UNIT,
	NULL AS GL_KEY_CODE,
	NULL AS GL_KEY_CODE_DESC,
	NULL AS CALL_CODE,
	NULL AS CALL_CODE_DESC,
	NULL AS ACCRUAL_VALUE,
	NULL AS CLEAN_PRICE_VALUE,
	NULL AS DIRTY_PRICE_VALUE,
	NULL AS MANUAL_ADJUSTMENTS,
	NULL AS CREDIT_ADJ,
	CASE
		WHEN COALESCE(C.ATTRIBUTO1, 'CVA') = 'CVA'
			THEN DATA.IMPORTO2 * 1000
		ELSE NULL
	END AS CREDIT_VALUATION_ADJUSTMENT,
	CASE
		WHEN COALESCE(C.ATTRIBUTO1, 'CVA') = 'UN'
			THEN DATA.IMPORTO2 * 1000
		ELSE NULL
	END AS USQ_NOTIONAL,
	NULL AS POSITIVE_NEGATIVE,
	NULL AS BUY_SELL_INDICATOR,
	NULL AS MATURITY_PCT_WEIGHT,
	NULL AS ADD_ON,
	CASE
		WHEN COALESCE(C.ATTRIBUTO1, 'CVA') = 'RV'
			THEN DATA.IMPORTO2 * 1000
		ELSE NULL
	END AS REPLACEMENT_VALUE,
	CASE
		WHEN COALESCE(C.ATTRIBUTO1, 'CVA') = 'CE'
			THEN DATA.IMPORTO2 * 1000
		ELSE NULL
	END AS CREDIT_EQUIVALENT,
	NULL AS CPTY_WGHT,
	NULL AS AMT_BOUGHT,
	NULL AS AMT_SOLD,
	NULL AS CCY_RECEIVE,
	NULL AS CCY_PAY,
	A.NOTE AS SOURCE,
	NULL AS ACC_INT_REC_GL_US_GAAP_BASE_EQ,
	NULL AS UNSET_TRADE_GL_US_GAAP_BASE_EQ,
	NULL AS RECEIVABLES_ADVANCES_BASE_EQ,
	NULL AS UNRLZED_PLG_GL_US_GAAP_BASE_EQ,
	NULL AS UNREAL_PLG_CCY_SWAP_US_BASE_EQ,
	NULL AS ACC_INT_PAY_GL_US_GAAP_BASE_EQ,
	NULL AS ACC_FEE_PAY_GL_US_GAAP_BASE_EQ,
	NULL AS UNSET_TRADE_PAYABLE_US_BASE_EQ,
	NULL AS UNRLZED_PLL_GL_US_GAAP_BASE_EQ,
	NULL AS UNREAL_PLL_CCY_SWAP_US_BASE_EQ,
	NULL AS MARCA_PROVISION,
	NULL AS NOTL_OPT_BUY_US_GAAP_BASE_EQ,
	NULL AS NOTL_SWAP_BUY_US_GAAP_BASE_EQ,
	NULL AS NOTL_OPT_GL_US_GAAP_BASE_EQ,
	NULL AS NOTL_OPT_SOLD_US_GAAP_BASE_EQ,
	NULL AS NOTL_SWAP_SOLD_US_GAAP_BASE_EQ,
	NULL AS IBF_ONLY_RAL_COLUMN_B_YN,
	NULL AS REGULATORY_RISK_RATINGS,
	NULL AS LEVEL_FAIR_VALUE,
	NULL AS CRC_RATING,
	NULL AS UMD1,
	NULL AS UMD2,
	NULL AS UMD3,
	NULL AS MATURITY_DATE,
	NULL AS REMAINING_MATURITY,
	NULL AS MATURITY_BUCKETS,
	NULL AS ONE_YEAR_OR_LESS,
	NULL AS ONE_TO_FIVE_YEARS,
	NULL AS GREATER_THAN_FIVE_YEARS,
	NULL AS ACCOUNTING_CLASSIFICATION,
	NULL AS BA_CODE,
	NULL AS ENTITY_ENT_CODE,
	NULL AS COUNTERPARTY_ENT_CODE,
	NULL AS COVERED_MARKET_RISK_RULE,
	NULL AS AFFIRMED_REG_RPT_CAP_GUARANTEE,
	NULL AS SECURITY_DESCRIPTION,
	NULL AS INVESTMENT_GRADE,
	NULL AS SUBINVESTMENT_GRADE,
	NULL AS UMD4,
	NULL AS UMD5,
	NULL AS UMD6,
	NULL AS TRADE_ID,
	NULL AS CUSTOMER_ID,
	NULL AS RELATED_DEP_INST,
	NULL AS CUSTOMER_NAME,
	NULL AS CUSTOMER_TYPE,
	NULL AS CITY,
	NULL AS OPERATING_STATE,
	NULL AS FOREIGN_DOMESTIC,
	NULL AS COUNTRY_CODE,
	NULL AS COUNTRY_DESC,
	NULL AS RELATION_ID,
	NULL AS FX_RATE_REC,
	NULL AS FX_RATE_PAY,
	NULL AS STRIKE_PRICE,
	NULL AS FIXED_OR_VARIABLE,
	NULL AS RECEIVE_INTEREST_RATE,
	NULL AS PAY_INTEREST_RATE,
	NULL AS INDEX_RATE_ADD,
	NULL AS FLOAT_FREQ,
	NULL AS LAST_RATE_RESET_DATE,
	NULL AS NEXT_RATE_RESET_DATE,
	NULL AS BRANCH_SUBSIDIARY,
	NULL AS START_DATE,
	NULL AS TRADE_DATE,
	NULL AS SETTLE_DATE,
	NULL AS UMD7,
	NULL AS UMD8,
	NULL AS UMD9,
	NULL AS UMD10,
	DATA.COD_DEST1 AS ACCOUNT,
	DATA.COD_DEST3 AS PRODUCT,
	DATA.COD_DEST2 AS OPERATING_UNIT,
	DATA.COD_AZI_CTP AS AFFILIATE,
	DATA.COD_DEST4 AS CUST_CLASS,
	NULL AS CODEBLOCK,
	NULL AS ACCRUAL_CODEBLOCK,
	NULL AS UNREALIZED_CODEBLOCK,
	NULL AS CALL_CODE_CONCAT,
	NULL AS FILLER_1,
	NULL AS FILLER_2,
	NULL AS FILLER_3,
	NULL AS FILLER_4,
	NULL AS FILLER_5,
	NULL AS FILLER_6,
	NULL AS FILLER_7,
	NULL AS FILLER_8,
	NULL AS FILLER_9,
	NULL AS FILLER_10,
	NULL AS FILLER_11,
	NULL AS FILLER_12,
	NULL AS FILLER_13,
	NULL AS FILLER_14,
	NULL AS FILLER_15,
	NULL AS FILLER_16,
	NULL AS FILLER_17,
	NULL AS FILLER_18,
	NULL AS FILLER_19,
	NULL AS FILLER_20,
	NULL AS FILLER_21,
	NULL AS FILLER_22,
	NULL AS FILLER_23,
	NULL AS FILLER_24,
	NULL AS FILLER_25,
	${CONCATENATE($Account.code, " (", PARENT($Account(HIERARCHY("RE"))).code, " - ", PARENT($Account(HIERARCHY("RE"))).desc, ": ", $Account.attribute4, " - ", $Account.attribute5, ")")} AS LINE_ITEM
FROM
	DATI_RETT_RIGA DATA
	LEFT OUTER JOIN
	DATI_RETT A
	ON
		DATA.COD_SCENARIO = A.COD_SCENARIO
		AND DATA.COD_PERIODO = A.COD_PERIODO
		AND DATA.NUM_RETTIFICA = A.NUM_RETTIFICA
	LEFT OUTER JOIN
	SCENARIO_PERIODO SP
	ON
		DATA.COD_SCENARIO = SP.COD_SCENARIO
		AND DATA.COD_PERIODO = SP.COD_PERIODO
	LEFT OUTER JOIN
	CONTO C
	ON
		DATA.COD_CONTO = C.COD_CONTO
WHERE
  DATA.COD_SCENARIO IN (${$Scenario.code}) 
  AND DATA.COD_PERIODO IN (${$Period.code})
  AND DATA.COD_AZIENDA IN (${$Entity.code})
  AND DATA.COD_CONTO IN (${$Account.code})
  AND DATA.COD_DEST1 IN (${$Cust_Dim1.code})
  AND DATA.COD_DEST2 IN (${$Cust_Dim2.code})
  AND DATA.COD_DEST3 IN (${$Cust_Dim3.code})
  AND DATA.COD_DEST4 IN (${$Cust_Dim4.code})
  AND DATA.COD_DEST5 IN (${$Cust_Dim5.code})
  AND DATA.COD_CATEGORIA IN (${$Category.code})