SELECT
(
  SELECT
    SUM(ACCRUAL_VALUE) AS ACCRUAL_VALUE,
	SUM(CLEAN_PRICE_VALUE) AS CLEAN_PRICE_VALUE,
	SUM(DIRTY_PRICE_VALUE) AS DIRTY_PRICE_VALUE,
	SUM(CREDIT_VALUATION_ADJUSTMENT) AS CREDIT_VALUATION_ADJUSTMENT,
	SUM(USQ_NOTIONAL) AS USQ_NOTIONAL
  FROM
    RB_V_HST_DERIVATIVES S
  WHERE
    (
      USERUPD = ${user.code}
      AND (EXISTS(SELECT 1 FROM RB_V_HST_DERIVATIVES WHERE USERUPD = ${user.code}))
    )
    OR (
      DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_DERIVATIVES)
      AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_DERIVATIVES WHERE USERUPD = ${user.code}))
    )
) AS STG,
(
  SELECT
    SUM(IMPORTO_2) AS ACCRUAL_VALUE,
	SUM(IMPORTO_6) AS CLEAN_PRICE_VALUE,
	SUM(IMPORTO_7) AS DIRTY_PRICE_VALUE,
	SUM(IMPORTO_3) AS CREDIT_VALUATION_ADJUSTMENT,
	SUM(IMPORTO_5) AS USQ_NOTIONAL
  FROM
    FORM_DATI A
    INNER JOIN
    (
      SELECT DISTINCT
        RB_F_TGK_CREATE_SCENARIO_CODE(MONTH_END_DATE) AS COD_SCENARIO,
        RB_F_TGK_CREATE_PERIOD_CODE(MONTH_END_DATE) AS COD_PERIODO,
        REPORTING_ENTITY
      FROM
        RB_V_HST_DERIVATIVES S
      WHERE
        (
          USERUPD = ${user.code}
          AND (EXISTS(SELECT 1 FROM RB_V_HST_DERIVATIVES WHERE USERUPD = ${user.code}))
        )
        OR (
          DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_DERIVATIVES)
          AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_DERIVATIVES WHERE USERUPD = ${user.code}))
        )
    ) S
  ON
	A.COD_SCENARIO = S.COD_SCENARIO
	AND A.COD_PERIODO = S.COD_PERIODO
	AND A.TESTO_1 = S.REPORTING_ENTITY
  WHERE
    A.COD_PROSPETTO = 'DERIVATIVES'
) AS APP
FROM
  DUAL