SELECT
	FD.COD_PROSPETTO AS COD_TAPE,
	CAST(DATA.RB_ROWID AS VARCHAR(255)) AS RB_ROWID,
	DATA.MONTH_END_DATE,
	DATA.REPORTING_ENTITY,
	DATA.INSTRUMENT,
	DATA.CALL_CODE,
	DATA.CALL_CODE_DESC,
	DATA.GL_KEY_CODE,
	DATA.GL_KEY_CODE_DESC,
	DATA.CONSOL_NODE,
	DATA.BUSINESS_UNIT,
	DATA.CURRENCY_CODE,
	DATA.FOREIGN_AMOUNT,
	DATA.CURRENCY_USQ,
	DATA.BASE_EQUIVALENT,
	DATA.ORIGINATION_DATE,
	DATA.MATURITY_DATE,
	DATA.REMAINING_MATURITY_DAYS,
	DATA.FRONTED_UNFUNDED_PARTICIPANTS,
	DATA.CUSTOMER_ID,
	DATA.CUSTOMER_NAME,
	DATA."DEPO_NON-DEPO",
	DATA.FOREIGN_DOMESTIC,
	DATA.CANCELLABLE_Y_N,
	DATA.MATURITY_BUCKETS,
	DATA.SECURITIZATION_EXPO,
	DATA.CREDIT_CONVERSION_FACTOR,
	DATA.CREDIT_EQUIVALENT_AMT,
	DATA.RISK_COUNTRY,
	DATA.RISK_COUNTRY_CODE,
	DATA.RISK_WEIGHTED_CATEGORY,
	DATA.RISK_WEIGHTED_ALLOCATION,
	DATA.UMD_1,
	DATA.UMD_2,
	DATA.UMD_3,
	DATA.SECURED_Y_N,
	DATA.GUARANTEED_Y_N,
	DATA.GOVT_GUARANTEED_PERCENTAGE ,
	DATA.QUALIFIED_CENTRAL_CPT_Y_N,
	DATA.ABCP_CONDUITS_AMT,
	DATA.SOVERIGN_DEFAULT_Y_N,
	DATA.CRC_RATING_OF_OECD_EXPOSURES,
	DATA.US_GAAP_RISK_RATING,
	DATA.IFRS_RISK_RATING,
	DATA.FACILITY_LIMIT_AMOUNT,
	DATA.FACILITY_USED_AMOUNT,
	DATA.SYNDICATED_RABOSHARE,
	DATA."SYNDICATED_RABOSHARE_%",
	DATA.SYNDICATED_PARTICIPANTS,
	DATA."SYNDICATED_PARTICIPANTS_%",
	DATA.SOURCE,
	DATA.UMD_4,
	DATA.UMD_5,
	DATA.UMD_6,
	DATA.TRADE_ID,
	DATA.REPORTABLE_Y_N,
	DATA.BU ,
	DATA.ACCOUNT,
	DATA.PRODUCT,
	DATA.OPERATING_UNIT,
	DATA.DEPTID,
	DATA.CUST_CLASS,
	DATA.AFFILIATE,
	DATA.CIF_TYPE,
	DATA.CUSTOMER_TYPE,
	DATA.LOAN_CALL_CODE,
	DATA.PRODUCT_GROUP,
	DATA.FACILITY_TYPE,
	DATA.FACILITY_TYPE_DESC,
	DATA.CALL_CODE_CODEBLOCK,
	DATA.CCF_CODEBLOCK,
	DATA.FILLER_1,
	DATA.FILLER_2,
	DATA.FILLER_3,
	DATA.FILLER_4,
	DATA.FILLER_5,
	DATA.FILLER_6,
	DATA.FILLER_7,
	DATA.FILLER_8,
	DATA.FILLER_9,
	DATA.FILLER_10,
	DATA.FILLER_11,
	DATA.FILLER_12,
	DATA.FILLER_13,
	DATA.FILLER_14,
	DATA.FILLER_15,
	DATA.FILLER_16,
	DATA.FILLER_17,
	DATA.FILLER_18,
	DATA.FILLER_19,
	DATA.FILLER_20,
	DATA.FILLER_21,
	DATA.FILLER_22,
	DATA.FILLER_23,
	DATA.FILLER_24,
	DATA.FILLER_25,
	${CONCATENATE($Account.code, " (", PARENT($Account(HIERARCHY("RE"))).code, " - ", PARENT($Account(HIERARCHY("RE"))).desc, ": ", $Account.attribute4, " - ", $Account.attribute5, ")")} AS LINE_ITEM
FROM
  RB_DRILL_INSTRUMENT DRILL
  INNER JOIN
  FORM_DATI FD
  ON
    DRILL.OID_FORM_DATI = FD.OID_FORM_DATI
  INNER JOIN
  RB_V_OFF_BS DATA
  ON
	FD.DATA_1 = DATA.MONTH_END_DATE
	AND FD.TESTO_1 = DATA.REPORTING_ENTITY
	AND FD.IMPORTO_1 = DATA.RB_ROWID
WHERE
  DRILL.COD_SCENARIO IN (${$Scenario.code})
  AND DRILL.COD_PERIODO IN (${$Period.code})
  AND DRILL.COD_AZIENDA IN (${$Entity.code})
  AND DRILL.COD_CONTO IN (${$Account.code})
  AND DRILL.COD_DEST1 IN (${$Cust_Dim1.code})
  AND DRILL.COD_DEST2 IN (${$Cust_Dim2.code})
  AND DRILL.COD_DEST3 IN (${$Cust_Dim3.code})
  AND DRILL.COD_DEST4 IN (${$Cust_Dim4.code})
  AND DRILL.COD_DEST5 IN (${$Cust_Dim5.code})
  AND DRILL.COD_CATEGORIA IN (${$Category.code})
UNION ALL
SELECT
	'ADJUSTMENTS' AS COD_TAPE,
	DATA.NUM_RETTIFICA AS RB_ROWID,
	SP.DATA_FINE AS MONTH_END_DATE,
	NULL AS REPORTING_ENTITY,
	NULL AS INSTRUMENT,
	NULL AS CALL_CODE,
	NULL AS CALL_CODE_DESC,
	NULL AS GL_KEY_CODE,
	NULL AS GL_KEY_CODE_DESC,
	NULL AS CONSOL_NODE,
	DATA.COD_AZIENDA AS BUSINESS_UNIT,
	NULL AS CURRENCY_CODE,
	NULL AS FOREIGN_AMOUNT,
	NULL AS CURRENCY_USQ,
	CASE
        WHEN COALESCE(C.ATTRIBUTO1, 'BE') = 'BE'
            THEN DATA.IMPORTO2 * 1000
        ELSE NULL
  END AS BASE_EQUIVALENT,
	NULL AS ORIGINATION_DATE,
	NULL AS MATURITY_DATE,
	NULL AS REMAINING_MATURITY_DAYS,
	NULL AS FRONTED_UNFUNDED_PARTICIPANTS,
	NULL AS CUSTOMER_ID,
	NULL AS CUSTOMER_NAME,
	NULL AS "DEPO_NON-DEPO",
	NULL AS FOREIGN_DOMESTIC,
	NULL AS CANCELLABLE_Y_N,
	NULL AS MATURITY_BUCKETS,
	CASE
        WHEN COALESCE(C.ATTRIBUTO1, 'BE') = 'SEC'
            THEN DATA.IMPORTO2 * 1000
        ELSE NULL
  END AS SECURITIZATION_EXPO,
	NULL AS CREDIT_CONVERSION_FACTOR,
	CASE
        WHEN COALESCE(C.ATTRIBUTO1, 'BE') = 'CE'
            THEN DATA.IMPORTO2 * 1000
        ELSE NULL
  END AS CREDIT_EQUIVALENT_AMT,
	NULL AS RISK_COUNTRY,
	NULL AS RISK_COUNTRY_CODE,
	NULL AS RISK_WEIGHTED_CATEGORY,
	NULL AS RISK_WEIGHTED_ALLOCATION,
	NULL AS UMD_1,
	NULL AS UMD_2,
	NULL AS UMD_3,
	NULL AS SECURED_Y_N,
	NULL AS GUARANTEED_Y_N,
	NULL AS GOVT_GUARANTEED_PERCENTAGE ,
	NULL AS QUALIFIED_CENTRAL_CPT_Y_N,
	NULL AS ABCP_CONDUITS_AMT,
	NULL AS SOVERIGN_DEFAULT_Y_N,
	NULL AS CRC_RATING_OF_OECD_EXPOSURES,
	NULL AS US_GAAP_RISK_RATING,
	NULL AS IFRS_RISK_RATING,
	NULL AS FACILITY_LIMIT_AMOUNT,
	NULL AS FACILITY_USED_AMOUNT,
	NULL AS SYNDICATED_RABOSHARE,
	NULL AS "SYNDICATED_RABOSHARE_%",
	NULL AS SYNDICATED_PARTICIPANTS,
	NULL AS "SYNDICATED_PARTICIPANTS_%",
	A.NOTE AS SOURCE,
	NULL AS UMD_4,
	NULL AS UMD_5,
	NULL AS UMD_6,
	NULL AS TRADE_ID,
	NULL AS REPORTABLE_Y_N,
	NULL AS BU ,
	NULL AS ACCOUNT,
	DATA.COD_DEST3 AS PRODUCT,
	DATA.COD_DEST2 AS OPERATING_UNIT,
	NULL AS DEPTID,
	DATA.COD_DEST4 AS CUST_CLASS,
	DATA.COD_AZI_CTP AS AFFILIATE,
	NULL AS CIF_TYPE,
	NULL AS CUSTOMER_TYPE,
	NULL AS LOAN_CALL_CODE,
	NULL AS PRODUCT_GROUP,
	NULL AS FACILITY_TYPE,
	NULL AS FACILITY_TYPE_DESC,
	NULL AS CALL_CODE_CODEBLOCK,
	NULL AS CCF_CODEBLOCK,
	NULL AS FILLER_1,
	NULL AS FILLER_2,
	NULL AS FILLER_3,
	NULL AS FILLER_4,
	NULL AS FILLER_5,
	NULL AS FILLER_6,
	NULL AS FILLER_7,
	NULL AS FILLER_8,
	NULL AS FILLER_9,
	NULL AS FILLER_10,
	NULL AS FILLER_11,
	NULL AS FILLER_12,
	NULL AS FILLER_13,
	NULL AS FILLER_14,
	NULL AS FILLER_15,
	NULL AS FILLER_16,
	NULL AS FILLER_17,
	NULL AS FILLER_18,
	NULL AS FILLER_19,
	NULL AS FILLER_20,
	NULL AS FILLER_21,
	NULL AS FILLER_22,
	NULL AS FILLER_23,
	NULL AS FILLER_24,
	NULL AS FILLER_25,
	${CONCATENATE($Account.code, " (", PARENT($Account(HIERARCHY("RE"))).code, " - ", PARENT($Account(HIERARCHY("RE"))).desc, ": ", $Account.attribute4, " - ", $Account.attribute5, ")")} AS LINE_ITEM
FROM
	DATI_RETT_RIGA DATA
	LEFT OUTER JOIN
	DATI_RETT A
	ON
		DATA.COD_SCENARIO = A.COD_SCENARIO
		AND DATA.COD_PERIODO = A.COD_PERIODO
		AND DATA.NUM_RETTIFICA = A.NUM_RETTIFICA
	LEFT OUTER JOIN
	SCENARIO_PERIODO SP
	ON
		DATA.COD_SCENARIO = SP.COD_SCENARIO
		AND DATA.COD_PERIODO = SP.COD_PERIODO
  LEFT OUTER JOIN
	CONTO C
	ON
		DATA.COD_CONTO = C.COD_CONTO
WHERE
  DATA.COD_SCENARIO IN (${$Scenario.code}) 
  AND DATA.COD_PERIODO IN (${$Period.code})
  AND DATA.COD_AZIENDA IN (${$Entity.code})
  AND DATA.COD_CONTO IN (${$Account.code})
  AND DATA.COD_DEST1 IN (${$Cust_Dim1.code})
  AND DATA.COD_DEST2 IN (${$Cust_Dim2.code})
  AND DATA.COD_DEST3 IN (${$Cust_Dim3.code})
  AND DATA.COD_DEST4 IN (${$Cust_Dim4.code})
  AND DATA.COD_DEST5 IN (${$Cust_Dim5.code})
  AND DATA.COD_CATEGORIA IN (${$Category.code})