SELECT
(
  SELECT
    SUM(BASE_EQUIVALENT) AS BASE_EQUIVALENT,
	SUM(CREDIT_CONVERSION_FACTOR) AS CREDIT_CONVERSION_FACTOR,
	SUM(CREDIT_EQUIVALENT_AMT) AS CREDIT_EQUIVALENT_AMT,
	SUM(RISK_WEIGHTED_CATEGORY) AS RISK_WEIGHTED_CATEGORY,
	SUM(RISK_WEIGHTED_ALLOCATION) AS RISK_WEIGHTED_ALLOCATION
  FROM
    RB_V_HST_OFF_BS S
  WHERE
    (
      USERUPD = ${user.code}
      AND (EXISTS(SELECT 1 FROM RB_V_HST_OFF_BS WHERE USERUPD = ${user.code}))
    )
    OR (
      DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_OFF_BS)
      AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_OFF_BS WHERE USERUPD = ${user.code}))
    )
) AS STG,
(
  SELECT
    SUM(IMPORTO_3) AS BASE_EQUIVALENT,
	SUM(IMPORTO_7) AS CREDIT_CONVERSION_FACTOR,
	SUM(IMPORTO_8) AS CREDIT_EQUIVALENT_AMT,
	SUM(IMPORTO_9) AS RISK_WEIGHTED_CATEGORY,
	SUM(IMPORTO_10) AS RISK_WEIGHTED_ALLOCATION
  FROM
    FORM_DATI A
    INNER JOIN
    (
      SELECT DISTINCT
        RB_F_TGK_CREATE_SCENARIO_CODE(MONTH_END_DATE) AS COD_SCENARIO,
        RB_F_TGK_CREATE_PERIOD_CODE(MONTH_END_DATE) AS COD_PERIODO,
        REPORTING_ENTITY
      FROM
        RB_V_HST_OFF_BS S
      WHERE
        (
          USERUPD = ${user.code}
          AND (EXISTS(SELECT 1 FROM RB_V_HST_OFF_BS WHERE USERUPD = ${user.code}))
        )
        OR (
          DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_OFF_BS)
          AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_OFF_BS WHERE USERUPD = ${user.code}))
        )
    ) S
  ON
	A.COD_SCENARIO = S.COD_SCENARIO
	AND A.COD_PERIODO = S.COD_PERIODO
	AND A.TESTO_1 = S.REPORTING_ENTITY
  WHERE
    A.COD_PROSPETTO = 'OFF_BS'
) AS APP
FROM
  DUAL