SELECT
	H.RB_ROWID,
	H.MONTH_END_DATE,
	REPORTING_ENTITY,
	INSTRUMENT,
	CALL_CODE,
	CALL_CODE_DESC,
	GL_KEY_CODE,
	GL_KEY_CODE_DESC,
	CONSOL_NODE,
	H.BUSINESS_UNIT,
	CURRENCY_CODE,
	FOREIGN_AMOUNT,
	CURRENCY_USQ,
	BASE_EQUIVALENT,
	ORIGINATION_DATE,
	MATURITY_DATE,
	REMAINING_MATURITY_DAYS,
	FRONTED_UNFUNDED_PARTICIPANTS,
	CUSTOMER_ID,
	CUSTOMER_NAME,
	"DEPO_NON-DEPO",
	FOREIGN_DOMESTIC,
	CANCELLABLE_Y_N,
	MATURITY_BUCKETS,
	SECURITIZATION_EXPO,
	CREDIT_CONVERSION_FACTOR,
	CREDIT_EQUIVALENT_AMT,
	RISK_COUNTRY,
	RISK_COUNTRY_CODE,
	RISK_WEIGHTED_CATEGORY,
	RISK_WEIGHTED_ALLOCATION,
	UMD_1,
	UMD_2,
	UMD_3,
	SECURED_Y_N,
	GUARANTEED_Y_N,
	GOVT_GUARANTEED_PERCENTAGE ,
	QUALIFIED_CENTRAL_CPT_Y_N,
	ABCP_CONDUITS_AMT,
	SOVERIGN_DEFAULT_Y_N,
	CRC_RATING_OF_OECD_EXPOSURES,
	US_GAAP_RISK_RATING,
	IFRS_RISK_RATING,
	FACILITY_LIMIT_AMOUNT,
	FACILITY_USED_AMOUNT,
	SYNDICATED_RABOSHARE,
	"SYNDICATED_RABOSHARE_%",
	SYNDICATED_PARTICIPANTS,
	"SYNDICATED_PARTICIPANTS_%",
	SOURCE,
	UMD_4,
	UMD_5,
	UMD_6,
	TRADE_ID,
	REPORTABLE_Y_N,
	BU,
	ACCOUNT,
	PRODUCT,
	OPERATING_UNIT,
	DEPTID,
	CUST_CLASS,
	AFFILIATE,
	CIF_TYPE,
	CUSTOMER_TYPE,
	LOAN_CALL_CODE,
	PRODUCT_GROUP,
	FACILITY_TYPE,
	FACILITY_TYPE_DESC,
	CALL_CODE_CODEBLOCK,
	CCF_CODEBLOCK,
	FILLER_1,
	FILLER_2,
	FILLER_3,
	FILLER_4,
	FILLER_5,
	FILLER_6,
	FILLER_7,
	FILLER_8,
	FILLER_9,
	FILLER_10,
	FILLER_11,
	FILLER_12,
	FILLER_13,
	FILLER_14,
	FILLER_15,
	FILLER_16,
	FILLER_17,
	FILLER_18,
	FILLER_19,
	FILLER_20,
	FILLER_21,
	FILLER_22,
	FILLER_23,
	FILLER_24,
	FILLER_25
FROM
	RB_V_OFF_BS H
	INNER JOIN
	(
		SELECT DISTINCT
			DATA_1 as MONTH_END_DATE,
      COD_AZIENDA AS BUSINESS_UNIT
		FROM
			FORM_DATI
		WHERE
			COD_SCENARIO = ${A1}
			AND COD_PERIODO = ${B1}
			AND COD_PROSPETTO = 'OFF_BS'
      AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )
	) F
	ON
		H.MONTH_END_DATE = F.MONTH_END_DATE
    AND RB_F_TGK_SANITIZE_CODE(H.BUSINESS_UNIT) = F.BUSINESS_UNIT