SELECT
	A.COD_SCENARIO,
	A.COD_PERIODO,
	CGG.DESC_CONTO_ELEGER0 AS DESC_CONTO_ELEGER00,
	C.ATTRIBUTO5 AS FED_CALL_CODE,
	CG.DESC_CONTO_ELEGER0,
	A.DATA_SOURCE,
	A.RB_ROWID,
	A.MONTH_END_DATE,
	A.REPORTING_ENTITY,
	A.INSTRUMENT,
	A.SOURCE,
	A.FED_RESERVE,
	A.DEPOSIT_OR_NONDEP,
	A.CAPITAL_RISK_RATE,
	A.INTERCOMPANY,
	A.CALL_CODE,
	A.CURRENCY_CODE,
	A.FOREIGN_AMOUNT,
	A.BASE_EQUIVALENT,
	A.CASH_ACCT_NBR,
	A.CASH_ACCOUNT_NAME,
	A.CUSTOMER_ID,
	A.CUSTOMER_NAME,
	A.CUSTOMER_TYPE,
	A.BRANCH_AGENCY_002,
	A.HOLDING_COM_Y9C,
	A.FOREIGN_DOMESTIC,
	A.COUNTRY_DESC,
	A.CONSOL_NODE,
	A.LEGAL_ENTITY,
	A.PRIMARY_GL_NBR,
	A.GL_KEY_CODE,
	A.GL_AMNT_IFRS,
	A.GL_AMNT_USGAAP,
	A.ACCRUED_INTEREST,
	A.HIGHLVL_PROD_CAT,
	A.IN_COLLECTION,
	A.CURR_AND_COIN,
	A.INTEREST_BEARING,
	A.FOREIGN,
	A.DOMESTIC,
	A.OTHER_CASH,
	A.PRODUCT_TYPE,
	A.CUSTOMER_TYPE_PX,
	A.CUST_RELATION_PX,
	A.CUST_RELATION_GL,
	A.CUSTOMER_TYPE_GL,
	A.COUNTRY_CODE,
	A.CONSOL_BU_NODE,
	A.BUS_UNIT_NAME,
	A.BUSINESS_UNIT,
	A.ACCOUNT,
	A.ACCOUNT_NAME,
	A.PRODUCT,
	A.PRODUCT_NAME,
	A.OPERATING_UNIT,
	A.DEPTID,
	A.AFFILIATE,
	A.AFFILIATE_NAME,
	A.AFFL_CONSOL_NODE,
	A.CUST_CLASS
FROM 
(
	SELECT
		'ADJUSTMENTS' AS DATA_SOURCE,
		D.COD_CONTO AS COD_CONTO_REP,
		D.COD_SCENARIO,
		D.COD_PERIODO,
		NULL AS FED_RESERVE,
		NULL AS DEPOSIT_OR_NONDEP,
		NULL AS CAPITAL_RISK_RATE,
		NULL AS RB_ROWID,
		NULL AS MONTH_END_DATE,
		NULL AS REPORTING_ENTITY,
		NULL AS INSTRUMENT,
		NULL AS SOURCE,
		NULL AS INTERCOMPANY,
		D.COD_DEST5 AS CALL_CODE,
		D.COD_VALUTA2 AS CURRENCY_CODE,
		D.IMPORTO2 * 1000 AS FOREIGN_AMOUNT,
		D.IMPORTO2 * 1000 AS BASE_EQUIVALENT,
		NULL AS CASH_ACCT_NBR,
		NULL AS CASH_ACCOUNT_NAME,
		NULL AS CUSTOMER_ID,
		NULL AS CUSTOMER_NAME,
		NULL AS CUSTOMER_TYPE,
		NULL AS BRANCH_AGENCY_002,
		NULL AS HOLDING_COM_Y9C,
		NULL AS FOREIGN_DOMESTIC,
		NULL AS COUNTRY_DESC,
		NULL AS CONSOL_NODE,
		NULL AS LEGAL_ENTITY,
		NULL AS PRIMARY_GL_NBR,
		NULL AS GL_KEY_CODE,
		NULL AS GL_AMNT_IFRS,
		NULL AS GL_AMNT_USGAAP,
		NULL AS ACCRUED_INTEREST,
		NULL AS HIGHLVL_PROD_CAT,
		NULL AS IN_COLLECTION,
		NULL AS CURR_AND_COIN,
		NULL AS INTEREST_BEARING,
		NULL AS FOREIGN,
		NULL AS DOMESTIC,
		NULL AS OTHER_CASH,
		NULL AS PRODUCT_TYPE,
		NULL AS CUSTOMER_TYPE_PX,
		NULL AS CUST_RELATION_PX,
		NULL AS CUST_RELATION_GL,
		NULL AS CUSTOMER_TYPE_GL,
		NULL AS COUNTRY_CODE,
		NULL AS CONSOL_BU_NODE,
		A.DESC_AZIENDA0 AS BUS_UNIT_NAME,
		D.COD_AZIENDA AS BUSINESS_UNIT,
		NULL AS ACCOUNT,
		NULL AS ACCOUNT_NAME,
		D.COD_DEST3 AS PRODUCT,
		D3.DESC_DEST30 AS PRODUCT_NAME,
		CASE
			WHEN SUBSTR(D.COD_DEST2, 3) = 'BLC'
				THEN SUBSTR(D.COD_DEST2, 5)
			ELSE NULL
		END AS OPERATING_UNIT,
		CASE
			WHEN SUBSTR(D.COD_DEST2, 3) = 'DPT'
				THEN SUBSTR(D.COD_DEST2, 5)
			ELSE NULL
		END AS DEPTID,
		D.COD_AZI_CTP AS AFFILIATE,
		ACTP.DESC_AZIENDA0 AS AFFILIATE_NAME,
		NULL AS AFFL_CONSOL_NODE,
		D.COD_DEST4 AS CUST_CLASS
	FROM
		DATI_RETT_RIGA D
		INNER JOIN
		(
			SELECT DISTINCT
				DRILL.COD_SCENARIO,
				DRILL.COD_PERIODO,
				DRILL.COD_CONTO
			FROM
				RB_DRILL_INSTRUMENT DRILL
				INNER JOIN
				FORM_DATI FD
				ON
					DRILL.OID_FORM_DATI = FD.OID_FORM_DATI
			WHERE
				FD.COD_PROSPETTO = 'CASH'
        AND DRILL.COD_AZIENDA IN (${$Entity.code})
		) DRILL
		ON
			D.COD_SCENARIO = DRILL.COD_SCENARIO
			AND D.COD_PERIODO = DRILL.COD_PERIODO
			AND D.COD_CONTO = DRILL.COD_CONTO
		LEFT OUTER JOIN
		DEST3 D3
		ON
			D.COD_DEST3 = D3.COD_DEST3
		LEFT OUTER JOIN
		AZIENDA A
		ON
			D.COD_AZIENDA = A.COD_AZIENDA
		LEFT OUTER JOIN
		AZIENDA ACTP
		ON
			D.COD_AZI_CTP = ACTP.COD_AZIENDA
	WHERE
		D.COD_SCENARIO IN (${$Scenario.code})
		AND D.COD_PERIODO IN (${$Period.code})
    AND D.COD_AZIENDA IN (${$Entity.code})
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 3) = ${A1}
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 4) = ${B1}
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 7) IS NULL
		AND D.COD_CATEGORIA IN ('ADJ_REP_R', 'ADJ_REP_NR')
	UNION ALL
	SELECT
		'ORIGINAL' AS DATA_SOURCE,
		A.COD_CONTO AS COD_CONTO_REP,
		B.COD_SCENARIO,
		B.COD_PERIODO,
		TESTO_11 AS FED_RESERVE,
		TESTO_12 AS DEPOSIT_OR_NONDEP,
		IMPORTO_1 AS CAPITAL_RISK_RATE,
		IMPORTO_2 AS RB_ROWID,
		DATA_1 AS MONTH_END_DATE,
		TESTO_14 AS REPORTING_ENTITY,
		TESTO_15 AS INSTRUMENT,
		TESTO_16 AS SOURCE,
		TESTO_17 AS INTERCOMPANY,
		TESTO_18 AS CALL_CODE,
		TESTO_19 AS CURRENCY_CODE,
		IMPORTO_3 AS FOREIGN_AMOUNT,
		IMPORTO_4 AS BASE_EQUIVALENT,
		TESTO_20 AS CASH_ACCT_NBR,
		TESTO_21 AS CASH_ACCOUNT_NAME,
		TESTO_22 AS CUSTOMER_ID,
		TESTO_23 AS CUSTOMER_NAME,
		TESTO_24 AS CUSTOMER_TYPE,
		TESTO_25 AS BRANCH_AGENCY_002,
		TESTO_26 AS HOLDING_COM_Y9C,
		TESTO_27 AS FOREIGN_DOMESTIC,
		TESTO_28 AS COUNTRY_DESC,
		TESTO_29 AS CONSOL_NODE,
		TESTO_30 AS LEGAL_ENTITY,
		TESTO_31 AS PRIMARY_GL_NBR,
		TESTO_32 AS GL_KEY_CODE,
		TESTO_33 AS GL_AMNT_IFRS,
		TESTO_34 AS GL_AMNT_USGAAP,
		IMPORTO_5 AS ACCRUED_INTEREST,
		TESTO_35 AS HIGHLVL_PROD_CAT,
		TESTO_36 AS IN_COLLECTION,
		TESTO_37 AS CURR_AND_COIN,
		TESTO_38 AS INTEREST_BEARING,
		TESTO_39 AS FOREIGN,
		TESTO_40 AS DOMESTIC,
		TESTO_41 AS OTHER_CASH,
		TESTO_42 AS PRODUCT_TYPE,
		TESTO_43 AS CUSTOMER_TYPE_PX,
		TESTO_44 AS CUST_RELATION_PX,
		TESTO_45 AS CUST_RELATION_GL,
		TESTO_46 AS CUSTOMER_TYPE_GL,
		TESTO_47 AS COUNTRY_CODE,
		TESTO_48 AS CONSOL_BU_NODE,
		TESTO_49 AS BUS_UNIT_NAME,
		TESTO_50 AS BUSINESS_UNIT,
		TESTO_1 AS ACCOUNT,
		TESTO_2 AS ACCOUNT_NAME,
		TESTO_3 AS PRODUCT,
		TESTO_4 AS PRODUCT_NAME,
		TESTO_5 AS OPERATING_UNIT,
		TESTO_6 AS DEPTID,
		TESTO_7 AS AFFILIATE,
		TESTO_8 AS AFFILIATE_NAME,
		TESTO_9 AS AFFL_CONSOL_NODE,
		TESTO_10 AS CUST_CLASS
	FROM
		RB_DRILL_INSTRUMENT A
		INNER JOIN
		FORM_DATI B
		ON
			A.OID_FORM_DATI = B.OID_FORM_DATI
		INNER JOIN
		(
			SELECT DISTINCT
				COD_SCENARIO,
				COD_PERIODO,
				COD_CONTO
			FROM
				DATI_SALDI_LORDI
			WHERE
				COD_CATEGORIA = 'ORI_REP'
				AND PROVENIENZA LIKE REPLACE(
CASE
WHEN
${B1} = 'RAL'
THEN
'MAP_REP_' || ${A1} || '_' || SUBSTR(${B1},1,2) || '_%'
ELSE
'MAP_REP_' || ${A1} || '_' || ${B1} || '_%'
END
, '-', '_')
        AND COD_AZIENDA IN (${$Entity.code})
		) C
		ON
			A.COD_SCENARIO = C.COD_SCENARIO
			AND A.COD_PERIODO = C.COD_PERIODO
			AND A.COD_CONTO = C.COD_CONTO
		WHERE
			A.COD_SCENARIO IN (${$Scenario.code})
			AND A.COD_PERIODO IN (${$Period.code})
      AND A.COD_AZIENDA IN (${$Entity.code})
			AND A.PROVENIENZA LIKE REPLACE(
CASE
WHEN
${B1} = 'RAL'
THEN
'MAP_REP_' || ${A1} || '_' || SUBSTR(${B1},1,2) || '_%'
ELSE
'MAP_REP_' || ${A1} || '_' || ${B1} || '_%'
END
, '-', '_')
			AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 3) = ${A1}
			AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 4) = ${B1}
			AND RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO, 'RE', 7) IS NULL
			AND A.COD_CATEGORIA IN ('ORI_REP')
			AND B.COD_PROSPETTO = 'CASH'
  UNION ALL
  SELECT
		'ROUNDING' AS DATA_SOURCE,
		D.COD_CONTO AS COD_CONTO_REP,
		D.COD_SCENARIO,
		D.COD_PERIODO,
		NULL AS FED_RESERVE,
		NULL AS DEPOSIT_OR_NONDEP,
		NULL AS CAPITAL_RISK_RATE,
		NULL AS RB_ROWID,
		NULL AS MONTH_END_DATE,
		NULL AS REPORTING_ENTITY,
		NULL AS INSTRUMENT,
		NULL AS SOURCE,
		NULL AS INTERCOMPANY,
		D.COD_DEST5 AS CALL_CODE,
		D.COD_VALUTA_ORIGINARIA AS CURRENCY_CODE,
		D.IMPORTO_VALUTA_ORIGINARIA * 1000 AS FOREIGN_AMOUNT,
		D.IMPORTO * 1000 AS BASE_EQUIVALENT,
		NULL AS CASH_ACCT_NBR,
		NULL AS CASH_ACCOUNT_NAME,
		NULL AS CUSTOMER_ID,
		NULL AS CUSTOMER_NAME,
		NULL AS CUSTOMER_TYPE,
		NULL AS BRANCH_AGENCY_002,
		NULL AS HOLDING_COM_Y9C,
		NULL AS FOREIGN_DOMESTIC,
		NULL AS COUNTRY_DESC,
		NULL AS CONSOL_NODE,
		NULL AS LEGAL_ENTITY,
		NULL AS PRIMARY_GL_NBR,
		NULL AS GL_KEY_CODE,
		NULL AS GL_AMNT_IFRS,
		NULL AS GL_AMNT_USGAAP,
		NULL AS ACCRUED_INTEREST,
		NULL AS HIGHLVL_PROD_CAT,
		NULL AS IN_COLLECTION,
		NULL AS CURR_AND_COIN,
		NULL AS INTEREST_BEARING,
		NULL AS FOREIGN,
		NULL AS DOMESTIC,
		NULL AS OTHER_CASH,
		NULL AS PRODUCT_TYPE,
		NULL AS CUSTOMER_TYPE_PX,
		NULL AS CUST_RELATION_PX,
		NULL AS CUST_RELATION_GL,
		NULL AS CUSTOMER_TYPE_GL,
		NULL AS COUNTRY_CODE,
		NULL AS CONSOL_BU_NODE,
		A.DESC_AZIENDA0 AS BUS_UNIT_NAME,
		D.COD_AZIENDA AS BUSINESS_UNIT,
		NULL AS ACCOUNT,
		NULL AS ACCOUNT_NAME,
		D.COD_DEST3 AS PRODUCT,
		D3.DESC_DEST30 AS PRODUCT_NAME,
		CASE
			WHEN SUBSTR(D.COD_DEST2, 3) = 'BLC'
				THEN SUBSTR(D.COD_DEST2, 5)
			ELSE NULL
		END AS OPERATING_UNIT,
		CASE
			WHEN SUBSTR(D.COD_DEST2, 3) = 'DPT'
				THEN SUBSTR(D.COD_DEST2, 5)
			ELSE NULL
		END AS DEPTID,
    NULL AS AFFILIATE,
		NULL AS AFFILIATE_NAME,
		NULL AS AFFL_CONSOL_NODE,
		D.COD_DEST4 AS CUST_CLASS
	FROM
		DATI_SALDI_LORDI D
		INNER JOIN
		(
			SELECT DISTINCT
				DRILL.COD_SCENARIO,
				DRILL.COD_PERIODO,
				DRILL.COD_CONTO
			FROM
				RB_DRILL_INSTRUMENT DRILL
				INNER JOIN
				FORM_DATI FD
				ON
					DRILL.OID_FORM_DATI = FD.OID_FORM_DATI
			WHERE
				FD.COD_PROSPETTO = 'CASH'
        AND DRILL.COD_AZIENDA IN (${$Entity.code})
		) DRILL
		ON
			D.COD_SCENARIO = DRILL.COD_SCENARIO
			AND D.COD_PERIODO = DRILL.COD_PERIODO
			AND D.COD_CONTO = DRILL.COD_CONTO
		LEFT OUTER JOIN
		DEST3 D3
		ON
			D.COD_DEST3 = D3.COD_DEST3
		LEFT OUTER JOIN
		AZIENDA A
		ON
			D.COD_AZIENDA = A.COD_AZIENDA
	WHERE
		D.COD_SCENARIO IN (${$Scenario.code})
		AND D.COD_PERIODO IN (${$Period.code})
    AND D.COD_AZIENDA IN (${$Entity.code})
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 3) = ${A1}
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 4) = ${B1}
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 7) IS NULL
		AND D.COD_CATEGORIA IN ('ORI_REP')
		AND D.PROVENIENZA = 'PROC_BALANCING'
  UNION ALL
  SELECT
		'OVERWRITE' AS DATA_SOURCE,
		D.COD_CONTO AS COD_CONTO_REP,
		D.COD_SCENARIO,
		D.COD_PERIODO,
		NULL AS FED_RESERVE,
		NULL AS DEPOSIT_OR_NONDEP,
		NULL AS CAPITAL_RISK_RATE,
		NULL AS RB_ROWID,
		NULL AS MONTH_END_DATE,
		NULL AS REPORTING_ENTITY,
		NULL AS INSTRUMENT,
		NULL AS SOURCE,
		NULL AS INTERCOMPANY,
		D.COD_DEST5 AS CALL_CODE,
		D.COD_VALUTA_ORIGINARIA AS CURRENCY_CODE,
		D.IMPORTO_VALUTA_ORIGINARIA * 1000 AS FOREIGN_AMOUNT,
		D.IMPORTO * 1000 AS BASE_EQUIVALENT,
		NULL AS CASH_ACCT_NBR,
		NULL AS CASH_ACCOUNT_NAME,
		NULL AS CUSTOMER_ID,
		NULL AS CUSTOMER_NAME,
		NULL AS CUSTOMER_TYPE,
		NULL AS BRANCH_AGENCY_002,
		NULL AS HOLDING_COM_Y9C,
		NULL AS FOREIGN_DOMESTIC,
		NULL AS COUNTRY_DESC,
		NULL AS CONSOL_NODE,
		NULL AS LEGAL_ENTITY,
		NULL AS PRIMARY_GL_NBR,
		NULL AS GL_KEY_CODE,
		NULL AS GL_AMNT_IFRS,
		NULL AS GL_AMNT_USGAAP,
		NULL AS ACCRUED_INTEREST,
		NULL AS HIGHLVL_PROD_CAT,
		NULL AS IN_COLLECTION,
		NULL AS CURR_AND_COIN,
		NULL AS INTEREST_BEARING,
		NULL AS FOREIGN,
		NULL AS DOMESTIC,
		NULL AS OTHER_CASH,
		NULL AS PRODUCT_TYPE,
		NULL AS CUSTOMER_TYPE_PX,
		NULL AS CUST_RELATION_PX,
		NULL AS CUST_RELATION_GL,
		NULL AS CUSTOMER_TYPE_GL,
		NULL AS COUNTRY_CODE,
		NULL AS CONSOL_BU_NODE,
		A.DESC_AZIENDA0 AS BUS_UNIT_NAME,
		D.COD_AZIENDA AS BUSINESS_UNIT,
		NULL AS ACCOUNT,
		NULL AS ACCOUNT_NAME,
		D.COD_DEST3 AS PRODUCT,
		D3.DESC_DEST30 AS PRODUCT_NAME,
		CASE
			WHEN SUBSTR(D.COD_DEST2, 3) = 'BLC'
				THEN SUBSTR(D.COD_DEST2, 5)
			ELSE NULL
		END AS OPERATING_UNIT,
		CASE
			WHEN SUBSTR(D.COD_DEST2, 3) = 'DPT'
				THEN SUBSTR(D.COD_DEST2, 5)
			ELSE NULL
		END AS DEPTID,
    NULL AS AFFILIATE,
		NULL AS AFFILIATE_NAME,
		NULL AS AFFL_CONSOL_NODE,
		D.COD_DEST4 AS CUST_CLASS
	FROM
		DATI_SALDI_LORDI D
		INNER JOIN
		(
			SELECT DISTINCT
				DRILL.COD_SCENARIO,
				DRILL.COD_PERIODO,
				DRILL.COD_CONTO
			FROM
				RB_DRILL_INSTRUMENT DRILL
				INNER JOIN
				FORM_DATI FD
				ON
					DRILL.OID_FORM_DATI = FD.OID_FORM_DATI
			WHERE
				FD.COD_PROSPETTO = 'CASH'
        AND DRILL.COD_AZIENDA IN (${$Entity.code})
		) DRILL
		ON
			D.COD_SCENARIO = DRILL.COD_SCENARIO
			AND D.COD_PERIODO = DRILL.COD_PERIODO
			AND D.COD_CONTO = DRILL.COD_CONTO
		LEFT OUTER JOIN
		DEST3 D3
		ON
			D.COD_DEST3 = D3.COD_DEST3
		LEFT OUTER JOIN
		AZIENDA A
		ON
			D.COD_AZIENDA = A.COD_AZIENDA
	WHERE
		D.COD_SCENARIO IN (${$Scenario.code})
		AND D.COD_PERIODO IN (${$Period.code})
    AND D.COD_AZIENDA IN (${$Entity.code})
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 3) = ${A1}
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 4) = ${B1}
		AND RB_F_TGK_GET_ACCOUNT_NODE(D.COD_CONTO, 'RE', 7) IS NULL
		AND D.COD_CATEGORIA = 'ORI_REP'
		AND D.PROVENIENZA NOT LIKE REPLACE(
CASE
WHEN
${B1} = 'RAL'
THEN
'MAP_REP_' || ${A1} || '_' || SUBSTR(${B1},1,2) || '_%'
ELSE
'MAP_REP_' || ${A1} || '_' || ${B1} || '_%'
END
, '-', '_')
		AND D.PROVENIENZA <> 'PROC_BALANCING'
) A
LEFT OUTER JOIN
CONTO_GERARCHIA CG
ON
  RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO_REP, 'RE', 6) = CG.COD_CONTO_ELEGER
LEFT OUTER JOIN
CONTO_GERARCHIA CGG
ON
  RB_F_TGK_GET_ACCOUNT_NODE(A.COD_CONTO_REP, 'RE', 5) = CGG.COD_CONTO_ELEGER
LEFT OUTER JOIN
CONTO C
ON
  A.COD_CONTO_REP = C.COD_CONTO
WHERE
    CG.COD_CONTO_GERARCHIA = 'RE'
    AND CGG.COD_CONTO_GERARCHIA = 'RE'
ORDER BY
	CGG.DESC_CONTO_ELEGER0 ASC,
	C.ATTRIBUTO5 ASC,
	CG.DESC_CONTO_ELEGER0 ASC,
	CASE
		WHEN A.MONTH_END_DATE IS NOT NULL
			THEN TO_CHAR(MONTH_END_DATE, 'MMDDYYYY')
		ELSE A.COD_SCENARIO
	END ASC,
	CASE
		WHEN A.MONTH_END_DATE IS NOT NULL
			THEN TO_CHAR(MONTH_END_DATE, 'MMDDYYYY')
		ELSE A.COD_PERIODO
	END ASC,
	A.DATA_SOURCE DESC,
	A.RB_ROWID,	
	A.REPORTING_ENTITY,
	A.INSTRUMENT,
	A.SOURCE