  SELECT
    TESTO_14 AS REPORTING_ENTITY,
    TESTO_15 AS INSTRUMENT,
    TESTO_18 AS CALL_CODE,
    TESTO_19 AS CURRENCY_CODE,
    TESTO_20 AS CASH_ACCOUNT_NBR,
    TESTO_2 AS ACCOUNT_NAME,
    TESTO_22 AS CUSTOMER_ID,
    TESTO_23 AS CUSTOMER_NAME,
    TESTO_24 AS CUSTOMER_TYPE,
    TESTO_27 AS FOREIGN_DOMESTIC,
    TESTO_28 AS COUNTRY_DESC,
    TESTO_49 AS BUSINESS_UNIT,
    TESTO_32 AS GL_KEY_CODE,
    IMPORTO_4 AS BASE_EQUIVALENT,
    TESTO_35 AS HIGHLVL_PROD_CAT,
    TESTO_36 AS IN_COLLECTION,
    TESTO_37 AS CURR_AND_COIN,
    TESTO_38 AS INTEREST_BEARING,
    TESTO_11 AS FED_RESERVE,
    TESTO_12 AS DEPOSIT_OR_NONDEP,
    IMPORTO_1 AS CAPITAL_RISK_RATE,
    TESTO_3 AS PRODUCT,
    TESTO_4 AS PRODUCT_NAME,
    TESTO_5 AS OPERATING_UNIT,
    TESTO_7 AS AFFILIATE,
    TESTO_10 AS CUST_CLASS
  FROM
    FORM_DATI
  WHERE
      COD_PROSPETTO = 'CASH'
  AND COD_SCENARIO = ${A1}
  AND COD_PERIODO = ${B1}