SELECT
  COALESCE(A.REPORTING_ENTITY, P.REPORTING_ENTITY) AS REPORTING_ENTITY,
  COALESCE(A.INSTRUMENT, P.INSTRUMENT) AS INSTRUMENT,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CALL_CODE <> P.CALL_CODE
          OR A.CALL_CODE IS NULL AND P.CALL_CODE IS NOT NULL
          OR A.CALL_CODE IS NOT NULL AND P.CALL_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CALL_CODE,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CURRENCY_CODE <> P.CURRENCY_CODE
          OR A.CURRENCY_CODE IS NULL AND P.CURRENCY_CODE IS NOT NULL
          OR A.CURRENCY_CODE IS NOT NULL AND P.CURRENCY_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CURRENCY_CODE,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CASH_ACCOUNT_NBR <> P.CASH_ACCOUNT_NBR
          OR A.CASH_ACCOUNT_NBR IS NULL AND P.CASH_ACCOUNT_NBR IS NOT NULL
          OR A.CASH_ACCOUNT_NBR IS NOT NULL AND P.CASH_ACCOUNT_NBR IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CASH_ACCOUNT_NBR,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.ACCOUNT_NAME <> P.ACCOUNT_NAME
          OR A.ACCOUNT_NAME IS NULL AND P.ACCOUNT_NAME IS NOT NULL
          OR A.ACCOUNT_NAME IS NOT NULL AND P.ACCOUNT_NAME IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS ACCOUNT_NAME,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSTOMER_ID <> P.CUSTOMER_ID
          OR A.CUSTOMER_ID IS NULL AND P.CUSTOMER_ID IS NOT NULL
          OR A.CUSTOMER_ID IS NOT NULL AND P.CUSTOMER_ID IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSTOMER_ID,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSTOMER_NAME <> P.CUSTOMER_NAME
          OR A.CUSTOMER_NAME IS NULL AND P.CUSTOMER_NAME IS NOT NULL
          OR A.CUSTOMER_NAME IS NOT NULL AND P.CUSTOMER_NAME IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSTOMER_NAME,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSTOMER_TYPE <> P.CUSTOMER_TYPE
          OR A.CUSTOMER_TYPE IS NULL AND P.CUSTOMER_TYPE IS NOT NULL
          OR A.CUSTOMER_TYPE IS NOT NULL AND P.CUSTOMER_TYPE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSTOMER_TYPE,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FOREIGN_DOMESTIC <> P.FOREIGN_DOMESTIC
          OR A.FOREIGN_DOMESTIC IS NULL AND P.FOREIGN_DOMESTIC IS NOT NULL
          OR A.FOREIGN_DOMESTIC IS NOT NULL AND P.FOREIGN_DOMESTIC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FOREIGN_DOMESTIC,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.COUNTRY_DESC <> P.COUNTRY_DESC
          OR A.COUNTRY_DESC IS NULL AND P.COUNTRY_DESC IS NOT NULL
          OR A.COUNTRY_DESC IS NOT NULL AND P.COUNTRY_DESC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS COUNTRY_DESC,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.BUSINESS_UNIT <> P.BUSINESS_UNIT
          OR A.BUSINESS_UNIT IS NULL AND P.BUSINESS_UNIT IS NOT NULL
          OR A.BUSINESS_UNIT IS NOT NULL AND P.BUSINESS_UNIT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS BUSINESS_UNIT,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.GL_KEY_CODE <> P.GL_KEY_CODE
          OR A.GL_KEY_CODE IS NULL AND P.GL_KEY_CODE IS NOT NULL
          OR A.GL_KEY_CODE IS NOT NULL AND P.GL_KEY_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS GL_KEY_CODE,
  COALESCE(A.BASE_EQUIVALENT, 0) - COALESCE(P.BASE_EQUIVALENT, 0) AS BASE_EQUIVALENT,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.HIGHLVL_PROD_CAT <> P.HIGHLVL_PROD_CAT
          OR A.HIGHLVL_PROD_CAT IS NULL AND P.HIGHLVL_PROD_CAT IS NOT NULL
          OR A.HIGHLVL_PROD_CAT IS NOT NULL AND P.HIGHLVL_PROD_CAT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS HIGHLVL_PROD_CAT,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.IN_COLLECTION <> P.IN_COLLECTION
          OR A.IN_COLLECTION IS NULL AND P.IN_COLLECTION IS NOT NULL
          OR A.IN_COLLECTION IS NOT NULL AND P.IN_COLLECTION IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS IN_COLLECTION,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CURR_AND_COIN <> P.CURR_AND_COIN
          OR A.CURR_AND_COIN IS NULL AND P.CURR_AND_COIN IS NOT NULL
          OR A.CURR_AND_COIN IS NOT NULL AND P.CURR_AND_COIN IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CURR_AND_COIN,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.INTEREST_BEARING <> P.INTEREST_BEARING
          OR A.INTEREST_BEARING IS NULL AND P.INTEREST_BEARING IS NOT NULL
          OR A.INTEREST_BEARING IS NOT NULL AND P.INTEREST_BEARING IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS INTEREST_BEARING,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FED_RESERVE <> P.FED_RESERVE
          OR A.FED_RESERVE IS NULL AND P.FED_RESERVE IS NOT NULL
          OR A.FED_RESERVE IS NOT NULL AND P.FED_RESERVE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FED_RESERVER,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.DEPOSIT_OR_NONDEP <> P.DEPOSIT_OR_NONDEP
          OR A.DEPOSIT_OR_NONDEP IS NULL AND P.DEPOSIT_OR_NONDEP IS NOT NULL
          OR A.DEPOSIT_OR_NONDEP IS NOT NULL AND P.DEPOSIT_OR_NONDEP IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS DEPOSIT_OR_NONDEP,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CAPITAL_RISK_RATE <> P.CAPITAL_RISK_RATE
          OR A.CAPITAL_RISK_RATE IS NULL AND P.CAPITAL_RISK_RATE IS NOT NULL
          OR A.CAPITAL_RISK_RATE IS NOT NULL AND P.CAPITAL_RISK_RATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CAPITAL_RISK_RATE,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PRODUCT <> P.PRODUCT
          OR A.PRODUCT IS NULL AND P.PRODUCT IS NOT NULL
          OR A.PRODUCT IS NOT NULL AND P.PRODUCT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PRODUCT,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PRODUCT_NAME <> P.PRODUCT_NAME
          OR A.PRODUCT_NAME IS NULL AND P.PRODUCT_NAME IS NOT NULL
          OR A.PRODUCT_NAME IS NOT NULL AND P.PRODUCT_NAME IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PRODUCT_NAME,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.OPERATING_UNIT <> P.OPERATING_UNIT
          OR A.OPERATING_UNIT IS NULL AND P.OPERATING_UNIT IS NOT NULL
          OR A.OPERATING_UNIT IS NOT NULL AND P.OPERATING_UNIT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS OPERATING_UNIT,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.AFFILIATE <> P.AFFILIATE
          OR A.AFFILIATE IS NULL AND P.AFFILIATE IS NOT NULL
          OR A.AFFILIATE IS NOT NULL AND P.AFFILIATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS AFFILIATE,
  CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUST_CLASS <> P.CUST_CLASS
          OR A.CUST_CLASS IS NULL AND P.CUST_CLASS IS NOT NULL
          OR A.CUST_CLASS IS NOT NULL AND P.CUST_CLASS IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUST_CLASS
FROM
(
  SELECT
    ROW_NUMBER() OVER (PARTITION BY
      TESTO_14,
      TESTO_15
      ORDER BY
        TESTO_18,
        TESTO_19,
        TESTO_20,
        TESTO_2,
        TESTO_22,
        TESTO_23,
        TESTO_24,
        TESTO_27,
        TESTO_28,
        TESTO_50,
        TESTO_32,
        IMPORTO_4,
        TESTO_35,
        TESTO_36,
        TESTO_37,
        TESTO_38,
        TESTO_11,
        TESTO_12,
        IMPORTO_1,
        TESTO_3,
        TESTO_4,
        TESTO_5,
        TESTO_7,
        TESTO_10
    ) AS ROW_ID,
    TESTO_14 AS REPORTING_ENTITY,
    TESTO_15 AS INSTRUMENT,
    TESTO_18 AS CALL_CODE,
    TESTO_19 AS CURRENCY_CODE,
    TESTO_20 AS CASH_ACCOUNT_NBR,
    TESTO_2 AS ACCOUNT_NAME,
    TESTO_22 AS CUSTOMER_ID,
    TESTO_23 AS CUSTOMER_NAME,
    TESTO_24 AS CUSTOMER_TYPE,
    TESTO_27 AS FOREIGN_DOMESTIC,
    TESTO_28 AS COUNTRY_DESC,
    TESTO_50 AS BUSINESS_UNIT,
    TESTO_32 AS GL_KEY_CODE,
    IMPORTO_4 AS BASE_EQUIVALENT,
    TESTO_35 AS HIGHLVL_PROD_CAT,
    TESTO_36 AS IN_COLLECTION,
    TESTO_37 AS CURR_AND_COIN,
    TESTO_38 AS INTEREST_BEARING,
    TESTO_11 AS FED_RESERVE,
    TESTO_12 AS DEPOSIT_OR_NONDEP,
    IMPORTO_1 AS CAPITAL_RISK_RATE,
    TESTO_3 AS PRODUCT,
    TESTO_4 AS PRODUCT_NAME,
    TESTO_5 AS OPERATING_UNIT,
    TESTO_7 AS AFFILIATE,
    TESTO_10 AS CUST_CLASS
  FROM
    FORM_DATI
  WHERE
      COD_PROSPETTO = 'CASH'
  AND COD_SCENARIO = ${A1}
  AND COD_PERIODO = ${B1}
  AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )
) A
FULL OUTER JOIN
(
  SELECT
    ROW_NUMBER() OVER (PARTITION BY
      TESTO_14,
      TESTO_15
      ORDER BY
        TESTO_18,
        TESTO_19,
        TESTO_20,
        TESTO_2,
        TESTO_22,
        TESTO_23,
        TESTO_24,
        TESTO_27,
        TESTO_28,
        TESTO_50,
        TESTO_32,
        IMPORTO_4,
        TESTO_35,
        TESTO_36,
        TESTO_37,
        TESTO_38,
        TESTO_11,
        TESTO_12,
        IMPORTO_1,
        TESTO_3,
        TESTO_4,
        TESTO_5,
        TESTO_7,
        TESTO_10
    ) AS ROW_ID,
    TESTO_14 AS REPORTING_ENTITY,
    TESTO_15 AS INSTRUMENT,
    TESTO_18 AS CALL_CODE,
    TESTO_19 AS CURRENCY_CODE,
    TESTO_20 AS CASH_ACCOUNT_NBR,
    TESTO_2 AS ACCOUNT_NAME,
    TESTO_22 AS CUSTOMER_ID,
    TESTO_23 AS CUSTOMER_NAME,
    TESTO_24 AS CUSTOMER_TYPE,
    TESTO_27 AS FOREIGN_DOMESTIC,
    TESTO_28 AS COUNTRY_DESC,
    TESTO_50 AS BUSINESS_UNIT,
    TESTO_32 AS GL_KEY_CODE,
    IMPORTO_4 AS BASE_EQUIVALENT,
    TESTO_35 AS HIGHLVL_PROD_CAT,
    TESTO_36 AS IN_COLLECTION,
    TESTO_37 AS CURR_AND_COIN,
    TESTO_38 AS INTEREST_BEARING,
    TESTO_11 AS FED_RESERVE,
    TESTO_12 AS DEPOSIT_OR_NONDEP,
    IMPORTO_1 AS CAPITAL_RISK_RATE,
    TESTO_3 AS PRODUCT,
    TESTO_4 AS PRODUCT_NAME,
    TESTO_5 AS OPERATING_UNIT,
    TESTO_7 AS AFFILIATE,
    TESTO_10 AS CUST_CLASS
  FROM
    FORM_DATI
  WHERE
      COD_PROSPETTO = 'CASH'
  AND COD_SCENARIO = ${A2}
  AND COD_PERIODO = ${B2}
  AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )
) P
ON
  A.ROW_ID = P.ROW_ID
  AND A.REPORTING_ENTITY = P.REPORTING_ENTITY
  AND (A.INSTRUMENT = P.INSTRUMENT OR (A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NULL))