SELECT
(
  SELECT
    SUM(AMORTIZED_COST) AS AMORTIZED_COST,
	SUM(FAIR_VALUE) AS FAIR_VALUE,
	SUM(PRINCIPAL_GL_US_GAAP_BASE_EQ) AS PRINCIPAL_GL_US_GAAP_BASE_EQ,
	SUM(DISCOUNT_GL_US_GAAP_BASE_EQ) AS DISCOUNT_GL_US_GAAP_BASE_EQ,
	SUM(UNREALIZED_PL_GL_US_GAAP_BASE_EQ) AS UNREALIZED_PL_GL_US_GAAP_BASE_EQ
  FROM
    RB_V_HST_SECURITY S
  WHERE
    (
      USERUPD = ${user.code}
      AND (EXISTS(SELECT 1 FROM RB_V_HST_SECURITY WHERE USERUPD = ${user.code}))
    )
    OR (
      DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_SECURITY)
      AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_SECURITY WHERE USERUPD = ${user.code}))
    )
) AS STG,
(
  SELECT
    SUM(IMPORTO_1) AS AMORTIZED_COST,
	SUM(IMPORTO_2) AS FAIR_VALUE,
	SUM(IMPORTO_3) AS PRINCIPAL_GL_US_GAAP_BASE_EQ,
	SUM(IMPORTO_4) AS DISCOUNT_GL_US_GAAP_BASE_EQ,
	SUM(IMPORTO_6) AS UNREALIZED_PL_GL_US_GAAP_BASE_EQ
  FROM
    FORM_DATI A
    INNER JOIN
    (
      SELECT DISTINCT
        RB_F_TGK_CREATE_SCENARIO_CODE(MONTH_END_DATE) AS COD_SCENARIO,
        RB_F_TGK_CREATE_PERIOD_CODE(MONTH_END_DATE) AS COD_PERIODO,
        REPORTING_ENTITY
      FROM
        RB_V_HST_SECURITY S
      WHERE
        (
          USERUPD = ${user.code}
          AND (EXISTS(SELECT 1 FROM RB_V_HST_SECURITY WHERE USERUPD = ${user.code}))
        )
        OR (
          DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_SECURITY)
          AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_SECURITY WHERE USERUPD = ${user.code}))
        )
    ) S
  ON
	A.COD_SCENARIO = S.COD_SCENARIO
	AND A.COD_PERIODO = S.COD_PERIODO
	AND A.TESTO_1 = S.REPORTING_ENTITY
  WHERE
    A.COD_PROSPETTO = 'SECURITIES'
) AS APP
FROM
  DUAL