SELECT
  COALESCE(A.REPORTING_ENTITY, P.REPORTING_ENTITY) AS REPORTING_ENTITY,
  COALESCE(A.INSTRUMENT, P.INSTRUMENT) AS INSTRUMENT,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.INTERCOMPANY <> P.INTERCOMPANY
          OR A.INTERCOMPANY IS NULL AND P.INTERCOMPANY IS NOT NULL
          OR A.INTERCOMPANY IS NOT NULL AND P.INTERCOMPANY IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS INTERCOMPANY,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CONSOL_NODE <> P.CONSOL_NODE
          OR A.CONSOL_NODE IS NULL AND P.CONSOL_NODE IS NOT NULL
          OR A.CONSOL_NODE IS NOT NULL AND P.CONSOL_NODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CONSOL_NODE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.BUSINESS_UNIT <> P.BUSINESS_UNIT
          OR A.BUSINESS_UNIT IS NULL AND P.BUSINESS_UNIT IS NOT NULL
          OR A.BUSINESS_UNIT IS NOT NULL AND P.BUSINESS_UNIT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS BUSINESS_UNIT,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.GL_KEY_CODE <> P.GL_KEY_CODE
          OR A.GL_KEY_CODE IS NULL AND P.GL_KEY_CODE IS NOT NULL
          OR A.GL_KEY_CODE IS NOT NULL AND P.GL_KEY_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS GL_KEY_CODE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.GL_KEY_CODE_DESC <> P.GL_KEY_CODE_DESC
          OR A.GL_KEY_CODE_DESC IS NULL AND P.GL_KEY_CODE_DESC IS NOT NULL
          OR A.GL_KEY_CODE_DESC IS NOT NULL AND P.GL_KEY_CODE_DESC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS GL_KEY_CODE_DESC,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CALL_CODE <> P.CALL_CODE
          OR A.CALL_CODE IS NULL AND P.CALL_CODE IS NOT NULL
          OR A.CALL_CODE IS NOT NULL AND P.CALL_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CALL_CODE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CALL_CODE_DESC <> P.CALL_CODE_DESC
          OR A.CALL_CODE_DESC IS NULL AND P.CALL_CODE_DESC IS NOT NULL
          OR A.CALL_CODE_DESC IS NOT NULL AND P.CALL_CODE_DESC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CALL_CODE_DESC,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PRODUCT_GROUP_DESC <> P.PRODUCT_GROUP_DESC
          OR A.PRODUCT_GROUP_DESC IS NULL AND P.PRODUCT_GROUP_DESC IS NOT NULL
          OR A.PRODUCT_GROUP_DESC IS NOT NULL AND P.PRODUCT_GROUP_DESC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PRODUCT_GROUP_DESC,
COALESCE(A.AMORTIZED_COST, 0) - COALESCE(P.AMORTIZED_COST, 0) AS AMORTIZED_COST,
COALESCE(A.FAIR_VALUE, 0) - COALESCE(P.FAIR_VALUE, 0) AS FAIR_VALUE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PRICE <> P.PRICE
          OR A.PRICE IS NULL AND P.PRICE IS NOT NULL
          OR A.PRICE IS NOT NULL AND P.PRICE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PRICE,
COALESCE(A.PRINCIPAL_GL_US_GAAP_BASE_EQ, 0) - COALESCE(P.PRINCIPAL_GL_US_GAAP_BASE_EQ, 0) AS PRINCIPAL_GL_US_GAAP_BASE_EQ,
COALESCE(A.DISCOUNT_GL_US_GAAP_BASE_EQ, 0) - COALESCE(P.DISCOUNT_GL_US_GAAP_BASE_EQ, 0) AS DISCOUNT_GL_US_GAAP_BASE_EQ,
COALESCE(A.PREMIUM_GL_US_GAAP_BASE_EQ, 0) - COALESCE(P.PREMIUM_GL_US_GAAP_BASE_EQ, 0) AS PREMIUM_GL_US_GAAP_BASE_EQ,
COALESCE(A.UNRLZED_PL_GL_US_GAAP_BASE_EQ, 0) - COALESCE(P.UNRLZED_PL_GL_US_GAAP_BASE_EQ, 0) AS UNRLZED_PL_GL_US_GAAP_BASE_EQ,
COALESCE(A.LTD_IMPAIRMENT_US_GAAP_BASE_EQ, 0) - COALESCE(P.LTD_IMPAIRMENT_US_GAAP_BASE_EQ, 0) AS LTD_IMPAIRMENT_US_GAAP_BASE_EQ,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.SOURCE <> P.SOURCE
          OR A.SOURCE IS NULL AND P.SOURCE IS NOT NULL
          OR A.SOURCE IS NOT NULL AND P.SOURCE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS SOURCE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.IBF_ONLY_RAL_COLUMN_B_YN <> P.IBF_ONLY_RAL_COLUMN_B_YN
          OR A.IBF_ONLY_RAL_COLUMN_B_YN IS NULL AND P.IBF_ONLY_RAL_COLUMN_B_YN IS NOT NULL
          OR A.IBF_ONLY_RAL_COLUMN_B_YN IS NOT NULL AND P.IBF_ONLY_RAL_COLUMN_B_YN IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS IBF_ONLY_RAL_COLUMN_B_YN,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CURRENCY_CODE <> P.CURRENCY_CODE
          OR A.CURRENCY_CODE IS NULL AND P.CURRENCY_CODE IS NOT NULL
          OR A.CURRENCY_CODE IS NOT NULL AND P.CURRENCY_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CURRENCY_CODE,
COALESCE(A.REGULATORY_RISK_RATINGS, 0) - COALESCE(P.REGULATORY_RISK_RATINGS, 0) AS REGULATORY_RISK_RATINGS,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.LEVEL_FAIR_VALUE <> P.LEVEL_FAIR_VALUE
          OR A.LEVEL_FAIR_VALUE IS NULL AND P.LEVEL_FAIR_VALUE IS NOT NULL
          OR A.LEVEL_FAIR_VALUE IS NOT NULL AND P.LEVEL_FAIR_VALUE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS LEVEL_FAIR_VALUE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.ORIGINAL_PRICE <> P.ORIGINAL_PRICE
          OR A.ORIGINAL_PRICE IS NULL AND P.ORIGINAL_PRICE IS NOT NULL
          OR A.ORIGINAL_PRICE IS NOT NULL AND P.ORIGINAL_PRICE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS ORIGINAL_PRICE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.MATURITY_DATE <> P.MATURITY_DATE
          OR A.MATURITY_DATE IS NULL AND P.MATURITY_DATE IS NOT NULL
          OR A.MATURITY_DATE IS NOT NULL AND P.MATURITY_DATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS MATURITY_DATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.REMAINING_MATURITY <> P.REMAINING_MATURITY
          OR A.REMAINING_MATURITY IS NULL AND P.REMAINING_MATURITY IS NOT NULL
          OR A.REMAINING_MATURITY IS NOT NULL AND P.REMAINING_MATURITY IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS REMAINING_MATURITY,
COALESCE(A.INT_RATE, 0) - COALESCE(P.INT_RATE, 0) AS INT_RATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FIXED_OR_VARIABLE <> P.FIXED_OR_VARIABLE
          OR A.FIXED_OR_VARIABLE IS NULL AND P.FIXED_OR_VARIABLE IS NOT NULL
          OR A.FIXED_OR_VARIABLE IS NOT NULL AND P.FIXED_OR_VARIABLE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FIXED_OR_VARIABLE,
COALESCE(A.FLOATING_RATE, 0) - COALESCE(P.FLOATING_RATE, 0) AS FLOATING_RATE,
COALESCE(A.FIXED_RATE, 0) - COALESCE(P.FIXED_RATE, 0) AS FIXED_RATE,
COALESCE(A.INDEX_RATE_ADD, 0) - COALESCE(P.INDEX_RATE_ADD, 0) AS INDEX_RATE_ADD,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FLOAT_FREQ <> P.FLOAT_FREQ
          OR A.FLOAT_FREQ IS NULL AND P.FLOAT_FREQ IS NOT NULL
          OR A.FLOAT_FREQ IS NOT NULL AND P.FLOAT_FREQ IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FLOAT_FREQ,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.MATURITY_BUCKETS <> P.MATURITY_BUCKETS
          OR A.MATURITY_BUCKETS IS NULL AND P.MATURITY_BUCKETS IS NOT NULL
          OR A.MATURITY_BUCKETS IS NOT NULL AND P.MATURITY_BUCKETS IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS MATURITY_BUCKETS,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.LAST_RATE_RESET_DATE <> P.LAST_RATE_RESET_DATE
          OR A.LAST_RATE_RESET_DATE IS NULL AND P.LAST_RATE_RESET_DATE IS NOT NULL
          OR A.LAST_RATE_RESET_DATE IS NOT NULL AND P.LAST_RATE_RESET_DATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS LAST_RATE_RESET_DATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.NEXT_RATE_RESET_DATE <> P.NEXT_RATE_RESET_DATE
          OR A.NEXT_RATE_RESET_DATE IS NULL AND P.NEXT_RATE_RESET_DATE IS NOT NULL
          OR A.NEXT_RATE_RESET_DATE IS NOT NULL AND P.NEXT_RATE_RESET_DATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS NEXT_RATE_RESET_DATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.DAY_COUNT_BASIS <> P.DAY_COUNT_BASIS
          OR A.DAY_COUNT_BASIS IS NULL AND P.DAY_COUNT_BASIS IS NOT NULL
          OR A.DAY_COUNT_BASIS IS NOT NULL AND P.DAY_COUNT_BASIS IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS DAY_COUNT_BASIS,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PLEDGED_SECURITIES_YN <> P.PLEDGED_SECURITIES_YN
          OR A.PLEDGED_SECURITIES_YN IS NULL AND P.PLEDGED_SECURITIES_YN IS NOT NULL
          OR A.PLEDGED_SECURITIES_YN IS NOT NULL AND P.PLEDGED_SECURITIES_YN IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PLEDGED_SECURITIES_YN,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CMMP_TO_PURCHASE_SEC_YN <> P.CMMP_TO_PURCHASE_SEC_YN
          OR A.CMMP_TO_PURCHASE_SEC_YN IS NULL AND P.CMMP_TO_PURCHASE_SEC_YN IS NOT NULL
          OR A.CMMP_TO_PURCHASE_SEC_YN IS NOT NULL AND P.CMMP_TO_PURCHASE_SEC_YN IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CMMP_TO_PURCHASE_SEC_YN,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.GUARANTOR <> P.GUARANTOR
          OR A.GUARANTOR IS NULL AND P.GUARANTOR IS NOT NULL
          OR A.GUARANTOR IS NOT NULL AND P.GUARANTOR IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS GUARANTOR,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSTOMER_NAME <> P.CUSTOMER_NAME
          OR A.CUSTOMER_NAME IS NULL AND P.CUSTOMER_NAME IS NOT NULL
          OR A.CUSTOMER_NAME IS NOT NULL AND P.CUSTOMER_NAME IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSTOMER_NAME,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSTOMER_TYPE <> P.CUSTOMER_TYPE
          OR A.CUSTOMER_TYPE IS NULL AND P.CUSTOMER_TYPE IS NOT NULL
          OR A.CUSTOMER_TYPE IS NOT NULL AND P.CUSTOMER_TYPE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSTOMER_TYPE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CITY <> P.CITY
          OR A.CITY IS NULL AND P.CITY IS NOT NULL
          OR A.CITY IS NOT NULL AND P.CITY IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CITY,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.OPERATING_STATE <> P.OPERATING_STATE
          OR A.OPERATING_STATE IS NULL AND P.OPERATING_STATE IS NOT NULL
          OR A.OPERATING_STATE IS NOT NULL AND P.OPERATING_STATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS OPERATING_STATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.COUNTRY_CODE <> P.COUNTRY_CODE
          OR A.COUNTRY_CODE IS NULL AND P.COUNTRY_CODE IS NOT NULL
          OR A.COUNTRY_CODE IS NOT NULL AND P.COUNTRY_CODE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS COUNTRY_CODE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
     THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.COUNTRY_DESC <> P.COUNTRY_DESC
          OR A.COUNTRY_DESC IS NULL AND P.COUNTRY_DESC IS NOT NULL
          OR A.COUNTRY_DESC IS NOT NULL AND P.COUNTRY_DESC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS COUNTRY_DESC,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FOREIGN_DOMESTIC <> P.FOREIGN_DOMESTIC
          OR A.FOREIGN_DOMESTIC IS NULL AND P.FOREIGN_DOMESTIC IS NOT NULL
          OR A.FOREIGN_DOMESTIC IS NOT NULL AND P.FOREIGN_DOMESTIC IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FOREIGN_DOMESTIC,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.SECURITY_DESCRIPTION <> P.SECURITY_DESCRIPTION
          OR A.SECURITY_DESCRIPTION IS NULL AND P.SECURITY_DESCRIPTION IS NOT NULL
          OR A.SECURITY_DESCRIPTION IS NOT NULL AND P.SECURITY_DESCRIPTION IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS SECURITY_DESCRIPTION,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A."S&P_RATING" <> P."S&P_RATING"
          OR A."S&P_RATING" IS NULL AND P."S&P_RATING" IS NOT NULL
          OR A."S&P_RATING" IS NOT NULL AND P."S&P_RATING" IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS "S&P_RATING",
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.MOODYS_RATING <> P.MOODYS_RATING
          OR A.MOODYS_RATING IS NULL AND P.MOODYS_RATING IS NOT NULL
          OR A.MOODYS_RATING IS NOT NULL AND P.MOODYS_RATING IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS MOODYS_RATING,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSIP <> P.CUSIP
          OR A.CUSIP IS NULL AND P.CUSIP IS NOT NULL
          OR A.CUSIP IS NOT NULL AND P.CUSIP IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSIP,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.ISIN <> P.ISIN
          OR A.ISIN IS NULL AND P.ISIN IS NOT NULL
          OR A.ISIN IS NOT NULL AND P.ISIN IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS ISIN,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
     THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.TRADE_ID <> P.TRADE_ID
          OR A.TRADE_ID IS NULL AND P.TRADE_ID IS NOT NULL
          OR A.TRADE_ID IS NOT NULL AND P.TRADE_ID IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS TRADE_ID,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUSTOMER_ID <> P.CUSTOMER_ID
          OR A.CUSTOMER_ID IS NULL AND P.CUSTOMER_ID IS NOT NULL
          OR A.CUSTOMER_ID IS NOT NULL AND P.CUSTOMER_ID IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUSTOMER_ID,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.RELATED_DEP_INST <> P.RELATED_DEP_INST
          OR A.RELATED_DEP_INST IS NULL AND P.RELATED_DEP_INST IS NOT NULL
          OR A.RELATED_DEP_INST IS NOT NULL AND P.RELATED_DEP_INST IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS RELATED_DEP_INST,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.BRANCH_SUBSIDIARY <> P.BRANCH_SUBSIDIARY
          OR A.BRANCH_SUBSIDIARY IS NULL AND P.BRANCH_SUBSIDIARY IS NOT NULL
          OR A.BRANCH_SUBSIDIARY IS NOT NULL AND P.BRANCH_SUBSIDIARY IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS BRANCH_SUBSIDIARY,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.VAL_DATE <> P.VAL_DATE
          OR A.VAL_DATE IS NULL AND P.VAL_DATE IS NOT NULL
          OR A.VAL_DATE IS NOT NULL AND P.VAL_DATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS VAL_DATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.TRADE_DATE <> P.TRADE_DATE
          OR A.TRADE_DATE IS NULL AND P.TRADE_DATE IS NOT NULL
         OR A.TRADE_DATE IS NOT NULL AND P.TRADE_DATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS TRADE_DATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.SETTLE_DATE <> P.SETTLE_DATE
          OR A.SETTLE_DATE IS NULL AND P.SETTLE_DATE IS NOT NULL
          OR A.SETTLE_DATE IS NOT NULL AND P.SETTLE_DATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS SETTLE_DATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.LAST_PRIN_PMT <> P.LAST_PRIN_PMT
          OR A.LAST_PRIN_PMT IS NULL AND P.LAST_PRIN_PMT IS NOT NULL
          OR A.LAST_PRIN_PMT IS NOT NULL AND P.LAST_PRIN_PMT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS LAST_PRIN_PMT,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD1 <> P.UMD1
          OR A.UMD1 IS NULL AND P.UMD1 IS NOT NULL
          OR A.UMD1 IS NOT NULL AND P.UMD1 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD1,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD2 <> P.UMD2
          OR A.UMD2 IS NULL AND P.UMD2 IS NOT NULL
          OR A.UMD2 IS NOT NULL AND P.UMD2 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD2,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD3 <> P.UMD3
          OR A.UMD3 IS NULL AND P.UMD3 IS NOT NULL
          OR A.UMD3 IS NOT NULL AND P.UMD3 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD3,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD4 <> P.UMD4
          OR A.UMD4 IS NULL AND P.UMD4 IS NOT NULL
          OR A.UMD4 IS NOT NULL AND P.UMD4 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD4,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD5 <> P.UMD5
          OR A.UMD5 IS NULL AND P.UMD5 IS NOT NULL
          OR A.UMD5 IS NOT NULL AND P.UMD5 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD5,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD6 <> P.UMD6
          OR A.UMD6 IS NULL AND P.UMD6 IS NOT NULL
          OR A.UMD6 IS NOT NULL AND P.UMD6 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD6,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD7 <> P.UMD7
          OR A.UMD7 IS NULL AND P.UMD7 IS NOT NULL
          OR A.UMD7 IS NOT NULL AND P.UMD7 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD7,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD8 <> P.UMD8
          OR A.UMD8 IS NULL AND P.UMD8 IS NOT NULL
          OR A.UMD8 IS NOT NULL AND P.UMD8 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD8,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD9 <> P.UMD9
          OR A.UMD9 IS NULL AND P.UMD9 IS NOT NULL
          OR A.UMD9 IS NOT NULL AND P.UMD9 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD9,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UMD10 <> P.UMD10
          OR A.UMD10 IS NULL AND P.UMD10 IS NOT NULL
          OR A.UMD10 IS NOT NULL AND P.UMD10 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UMD10,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.SYMB_POOL <> P.SYMB_POOL
          OR A.SYMB_POOL IS NULL AND P.SYMB_POOL IS NOT NULL
          OR A.SYMB_POOL IS NOT NULL AND P.SYMB_POOL IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS SYMB_POOL,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PORTFOLIO <> P.PORTFOLIO
          OR A.PORTFOLIO IS NULL AND P.PORTFOLIO IS NOT NULL
          OR A.PORTFOLIO IS NOT NULL AND P.PORTFOLIO IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PORTFOLIO,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.ACCOUNT_CAMRA <> P.ACCOUNT_CAMRA
          OR A.ACCOUNT_CAMRA IS NULL AND P.ACCOUNT_CAMRA IS NOT NULL
          OR A.ACCOUNT_CAMRA IS NOT NULL AND P.ACCOUNT_CAMRA IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS ACCOUNT_CAMRA,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PRODUCT_CAMRA <> P.PRODUCT_CAMRA
          OR A.PRODUCT_CAMRA IS NULL AND P.PRODUCT_CAMRA IS NOT NULL
          OR A.PRODUCT_CAMRA IS NOT NULL AND P.PRODUCT_CAMRA IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PRODUCT_CAMRA,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.ACCOUNT <> P.ACCOUNT
          OR A.ACCOUNT IS NULL AND P.ACCOUNT IS NOT NULL
          OR A.ACCOUNT IS NOT NULL AND P.ACCOUNT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS ACCOUNT,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PRODUCT <> P.PRODUCT
          OR A.PRODUCT IS NULL AND P.PRODUCT IS NOT NULL
          OR A.PRODUCT IS NOT NULL AND P.PRODUCT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PRODUCT,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.OPERATING_UNIT <> P.OPERATING_UNIT
          OR A.OPERATING_UNIT IS NULL AND P.OPERATING_UNIT IS NOT NULL
          OR A.OPERATING_UNIT IS NOT NULL AND P.OPERATING_UNIT IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS OPERATING_UNIT,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.AFFILIATE <> P.AFFILIATE
          OR A.AFFILIATE IS NULL AND P.AFFILIATE IS NOT NULL
          OR A.AFFILIATE IS NOT NULL AND P.AFFILIATE IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS AFFILIATE,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.CUST_CLASS <> P.CUST_CLASS
          OR A.CUST_CLASS IS NULL AND P.CUST_CLASS IS NOT NULL
          OR A.CUST_CLASS IS NOT NULL AND P.CUST_CLASS IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS CUST_CLASS,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.DISCOUNT_CODEBLOCK <> P.DISCOUNT_CODEBLOCK
          OR A.DISCOUNT_CODEBLOCK IS NULL AND P.DISCOUNT_CODEBLOCK IS NOT NULL
          OR A.DISCOUNT_CODEBLOCK IS NOT NULL AND P.DISCOUNT_CODEBLOCK IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS DISCOUNT_CODEBLOCK,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.PREMIUM_CODEBLOCK <> P.PREMIUM_CODEBLOCK
          OR A.PREMIUM_CODEBLOCK IS NULL AND P.PREMIUM_CODEBLOCK IS NOT NULL
          OR A.PREMIUM_CODEBLOCK IS NOT NULL AND P.PREMIUM_CODEBLOCK IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS PREMIUM_CODEBLOCK,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.UNRLZED_CODEBLOCK <> P.UNRLZED_CODEBLOCK
          OR A.UNRLZED_CODEBLOCK IS NULL AND P.UNRLZED_CODEBLOCK IS NOT NULL
          OR A.UNRLZED_CODEBLOCK IS NOT NULL AND P.UNRLZED_CODEBLOCK IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS UNRLZED_CODEBLOCK,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.LTD_IMPAIRMENT_CODEBLOCK <> P.LTD_IMPAIRMENT_CODEBLOCK
          OR A.LTD_IMPAIRMENT_CODEBLOCK IS NULL AND P.LTD_IMPAIRMENT_CODEBLOCK IS NOT NULL
          OR A.LTD_IMPAIRMENT_CODEBLOCK IS NOT NULL AND P.LTD_IMPAIRMENT_CODEBLOCK IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS LTD_IMPAIRMENT_CODEBLOCK,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_1 <> P.FILLER_1
          OR A.FILLER_1 IS NULL AND P.FILLER_1 IS NOT NULL
          OR A.FILLER_1 IS NOT NULL AND P.FILLER_1 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_1,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_2 <> P.FILLER_2
          OR A.FILLER_2 IS NULL AND P.FILLER_2 IS NOT NULL
          OR A.FILLER_2 IS NOT NULL AND P.FILLER_2 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_2,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_3 <> P.FILLER_3
          OR A.FILLER_3 IS NULL AND P.FILLER_3 IS NOT NULL
          OR A.FILLER_3 IS NOT NULL AND P.FILLER_3 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_3,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_4 <> P.FILLER_4
          OR A.FILLER_4 IS NULL AND P.FILLER_4 IS NOT NULL
          OR A.FILLER_4 IS NOT NULL AND P.FILLER_4 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_4,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_5 <> P.FILLER_5
          OR A.FILLER_5 IS NULL AND P.FILLER_5 IS NOT NULL
          OR A.FILLER_5 IS NOT NULL AND P.FILLER_5 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_5,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_6 <> P.FILLER_6
          OR A.FILLER_6 IS NULL AND P.FILLER_6 IS NOT NULL
          OR A.FILLER_6 IS NOT NULL AND P.FILLER_6 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_6,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_7 <> P.FILLER_7
          OR A.FILLER_7 IS NULL AND P.FILLER_7 IS NOT NULL
          OR A.FILLER_7 IS NOT NULL AND P.FILLER_7 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_7,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_8 <> P.FILLER_8
          OR A.FILLER_8 IS NULL AND P.FILLER_8 IS NOT NULL
          OR A.FILLER_8 IS NOT NULL AND P.FILLER_8 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_8,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_9 <> P.FILLER_9
          OR A.FILLER_9 IS NULL AND P.FILLER_9 IS NOT NULL
          OR A.FILLER_9 IS NOT NULL AND P.FILLER_9 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_9,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_10 <> P.FILLER_10
          OR A.FILLER_10 IS NULL AND P.FILLER_10 IS NOT NULL
          OR A.FILLER_10 IS NOT NULL AND P.FILLER_10 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_10,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_11 <> P.FILLER_11
          OR A.FILLER_11 IS NULL AND P.FILLER_11 IS NOT NULL
          OR A.FILLER_11 IS NOT NULL AND P.FILLER_11 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_11,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_12 <> P.FILLER_12
          OR A.FILLER_12 IS NULL AND P.FILLER_12 IS NOT NULL
          OR A.FILLER_12 IS NOT NULL AND P.FILLER_12 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_12,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_13 <> P.FILLER_13
          OR A.FILLER_13 IS NULL AND P.FILLER_13 IS NOT NULL
          OR A.FILLER_13 IS NOT NULL AND P.FILLER_13 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_13,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_14 <> P.FILLER_14
          OR A.FILLER_14 IS NULL AND P.FILLER_14 IS NOT NULL
          OR A.FILLER_14 IS NOT NULL AND P.FILLER_14 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_14,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_15 <> P.FILLER_15
          OR A.FILLER_15 IS NULL AND P.FILLER_15 IS NOT NULL
          OR A.FILLER_15 IS NOT NULL AND P.FILLER_15 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_15,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_16 <> P.FILLER_16
          OR A.FILLER_16 IS NULL AND P.FILLER_16 IS NOT NULL
          OR A.FILLER_16 IS NOT NULL AND P.FILLER_16 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_16,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_17 <> P.FILLER_17
          OR A.FILLER_17 IS NULL AND P.FILLER_17 IS NOT NULL
          OR A.FILLER_17 IS NOT NULL AND P.FILLER_17 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_17,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_18 <> P.FILLER_18
          OR A.FILLER_18 IS NULL AND P.FILLER_18 IS NOT NULL
          OR A.FILLER_18 IS NOT NULL AND P.FILLER_18 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_18,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_19 <> P.FILLER_19
          OR A.FILLER_19 IS NULL AND P.FILLER_19 IS NOT NULL
          OR A.FILLER_19 IS NOT NULL AND P.FILLER_19 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_19,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_20 <> P.FILLER_20
          OR A.FILLER_20 IS NULL AND P.FILLER_20 IS NOT NULL
          OR A.FILLER_20 IS NOT NULL AND P.FILLER_20 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_20,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_21 <> P.FILLER_21
          OR A.FILLER_21 IS NULL AND P.FILLER_21 IS NOT NULL
          OR A.FILLER_21 IS NOT NULL AND P.FILLER_21 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_21,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_22 <> P.FILLER_22
          OR A.FILLER_22 IS NULL AND P.FILLER_22 IS NOT NULL
          OR A.FILLER_22 IS NOT NULL AND P.FILLER_22 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_22,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_23 <> P.FILLER_23
          OR A.FILLER_23 IS NULL AND P.FILLER_23 IS NOT NULL
          OR A.FILLER_23 IS NOT NULL AND P.FILLER_23 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_23,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_24 <> P.FILLER_24
          OR A.FILLER_24 IS NULL AND P.FILLER_24 IS NOT NULL
          OR A.FILLER_24 IS NOT NULL AND P.FILLER_24 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_24,
CASE
    WHEN A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NOT NULL
      THEN CAST('OLD' AS VARCHAR(8))
   WHEN P.INSTRUMENT IS NULL AND A.INSTRUMENT IS NOT NULL
      THEN CAST('NEW' AS VARCHAR(8))
    WHEN  A.FILLER_25 <> P.FILLER_25
          OR A.FILLER_25 IS NULL AND P.FILLER_25 IS NOT NULL
          OR A.FILLER_25 IS NOT NULL AND P.FILLER_25 IS NULL
      THEN CAST('VARIANCE' AS VARCHAR(8))
    ELSE CAST('OK' AS VARCHAR(8))
  END AS FILLER_25
FROM
(
  SELECT
    ROW_NUMBER() OVER (PARTITION BY
      H.REPORTING_ENTITY,
      H.INSTRUMENT
      ORDER BY
        H.INTERCOMPANY,
        H.CONSOL_NODE,
        H.BUSINESS_UNIT,
        H.GL_KEY_CODE,
        H.GL_KEY_CODE_DESC,
        H.CALL_CODE,
        H.CALL_CODE_DESC,
        H.PRODUCT_GROUP_DESC,
        H.AMORTIZED_COST,
        H.FAIR_VALUE,
        H.PRICE,
        H.PRINCIPAL_GL_US_GAAP_BASE_EQ,
        H.DISCOUNT_GL_US_GAAP_BASE_EQ,
        H.PREMIUM_GL_US_GAAP_BASE_EQ,
        H.UNRLZED_PL_GL_US_GAAP_BASE_EQ,
        H.LTD_IMPAIRMENT_US_GAAP_BASE_EQ,
        H.SOURCE,
        H.IBF_ONLY_RAL_COLUMN_B_YN,
        H.CURRENCY_CODE,
        H.REGULATORY_RISK_RATINGS,
        H.LEVEL_FAIR_VALUE,
        H.ORIGINAL_PRICE,
        H.MATURITY_DATE,
        H.REMAINING_MATURITY,
        H.INT_RATE,
        H.FIXED_OR_VARIABLE,
        H.FLOATING_RATE,
        H.FIXED_RATE,
        H.INDEX_RATE_ADD,
        H.FLOAT_FREQ,
        H.MATURITY_BUCKETS,
        H.LAST_RATE_RESET_DATE,
        H.NEXT_RATE_RESET_DATE,
        H.DAY_COUNT_BASIS,
        H.PLEDGED_SECURITIES_YN,
        H.CMMP_TO_PURCHASE_SEC_YN,
        H.GUARANTOR,
        H.CUSTOMER_NAME,
        H.CUSTOMER_TYPE,
        H.CITY,
        H.OPERATING_STATE,
        H.COUNTRY_CODE,
        H.COUNTRY_DESC,
        H.FOREIGN_DOMESTIC,
        H.SECURITY_DESCRIPTION,
        H."S&P_RATING",
        H.MOODYS_RATING,
        H.CUSIP,
        H.ISIN,
        H.TRADE_ID,
        H.CUSTOMER_ID,
        H.RELATED_DEP_INST,
        H.BRANCH_SUBSIDIARY,
        H.VAL_DATE,
        H.TRADE_DATE,
        H.SETTLE_DATE,
        H.LAST_PRIN_PMT,
        H.UMD1,
        H.UMD2,
        H.UMD3,
        H.UMD4,
        H.UMD5,
        H.UMD6,
        H.UMD7,
        H.UMD8,
        H.UMD9,
        H.UMD10,
        H.SYMB_POOL,
        H.PORTFOLIO,
        H.ACCOUNT_CAMRA,
        H.PRODUCT_CAMRA,
        H.ACCOUNT,
        H.PRODUCT,
        H.OPERATING_UNIT,
        H.AFFILIATE,
        H.CUST_CLASS,
        H.DISCOUNT_CODEBLOCK,
        H.PREMIUM_CODEBLOCK,
        H.UNRLZED_CODEBLOCK,
        H.LTD_IMPAIRMENT_CODEBLOCK,
        H.FILLER_1,
        H.FILLER_2,
        H.FILLER_3,
        H.FILLER_4,
        H.FILLER_5,
        H.FILLER_6,
        H.FILLER_7,
        H.FILLER_8,
        H.FILLER_9,
        H.FILLER_10,
        H.FILLER_11,
        H.FILLER_12,
        H.FILLER_13,
        H.FILLER_14,
        H.FILLER_15,
        H.FILLER_16,
        H.FILLER_17,
        H.FILLER_18,
        H.FILLER_19,
        H.FILLER_20,
        H.FILLER_21,
        H.FILLER_22,
        H.FILLER_23,
        H.FILLER_24,
        H.FILLER_25
    ) AS ROW_ID,
    H.MONTH_END_DATE,
    REPORTING_ENTITY,
    INSTRUMENT,
    INTERCOMPANY,
    CONSOL_NODE,
    BUSINESS_UNIT,
    GL_KEY_CODE,
    GL_KEY_CODE_DESC,
    CALL_CODE,
    CALL_CODE_DESC,
    PRODUCT_GROUP_DESC,
    AMORTIZED_COST,
    FAIR_VALUE,
    PRICE,
    PRINCIPAL_GL_US_GAAP_BASE_EQ,
    DISCOUNT_GL_US_GAAP_BASE_EQ,
    PREMIUM_GL_US_GAAP_BASE_EQ,
    UNRLZED_PL_GL_US_GAAP_BASE_EQ,
    LTD_IMPAIRMENT_US_GAAP_BASE_EQ,
    SOURCE,
    IBF_ONLY_RAL_COLUMN_B_YN,
    CURRENCY_CODE,
    REGULATORY_RISK_RATINGS,
    LEVEL_FAIR_VALUE,
    ORIGINAL_PRICE,
    MATURITY_DATE,
    REMAINING_MATURITY,
    INT_RATE,
    FIXED_OR_VARIABLE,
    FLOATING_RATE,
    FIXED_RATE,
    INDEX_RATE_ADD,
    FLOAT_FREQ,
    MATURITY_BUCKETS,
    LAST_RATE_RESET_DATE,
    NEXT_RATE_RESET_DATE,
    DAY_COUNT_BASIS,
    PLEDGED_SECURITIES_YN,
    CMMP_TO_PURCHASE_SEC_YN,
    GUARANTOR,
    CUSTOMER_NAME,
    CUSTOMER_TYPE,
    CITY,
    OPERATING_STATE,
    COUNTRY_CODE,
    COUNTRY_DESC,
    FOREIGN_DOMESTIC,
    SECURITY_DESCRIPTION,
    "S&P_RATING",
    MOODYS_RATING,
    CUSIP,
    ISIN,
    TRADE_ID,
    CUSTOMER_ID,
    RELATED_DEP_INST,
    BRANCH_SUBSIDIARY,
    VAL_DATE,
    TRADE_DATE,
    SETTLE_DATE,
    LAST_PRIN_PMT,
    UMD1,
    UMD2,
    UMD3,
    UMD4,
    UMD5,
    UMD6,
    UMD7,
    UMD8,
    UMD9,
    UMD10,
    SYMB_POOL,
    PORTFOLIO,
    ACCOUNT_CAMRA,
    PRODUCT_CAMRA,
    ACCOUNT,
    PRODUCT,
    OPERATING_UNIT,
    AFFILIATE,
    CUST_CLASS,
    DISCOUNT_CODEBLOCK,
    PREMIUM_CODEBLOCK,
    UNRLZED_CODEBLOCK,
    LTD_IMPAIRMENT_CODEBLOCK,
    FILLER_1,
    FILLER_2,
    FILLER_3,
    FILLER_4,
    FILLER_5,
    FILLER_6,
    FILLER_7,
    FILLER_8,
    FILLER_9,
    FILLER_10,
    FILLER_11,
    FILLER_12,
    FILLER_13,
    FILLER_14,
    FILLER_15,
    FILLER_16,
    FILLER_17,
    FILLER_18,
    FILLER_19,
    FILLER_20,
    FILLER_21,
    FILLER_22,
    FILLER_23,
    FILLER_24,
    FILLER_25
  FROM
    RB_HST_SECURITY H
    INNER JOIN
    (
      SELECT DISTINCT
        DATA_1 AS MONTH_END_DATE
      FROM
        FORM_DATI
      WHERE
        COD_SCENARIO = ${A1}
        AND COD_PERIODO = ${B1}
        AND COD_PROSPETTO = 'SECURITIES'
    ) F
   ON
     H.MONTH_END_DATE = F.MONTH_END_DATE
  ) A
FULL OUTER JOIN
(
  SELECT
    ROW_NUMBER() OVER (PARTITION BY
      REPORTING_ENTITY,
      INSTRUMENT
      ORDER BY
        INTERCOMPANY,
        CONSOL_NODE,
        BUSINESS_UNIT,
        GL_KEY_CODE,
        GL_KEY_CODE_DESC,
        CALL_CODE,
        CALL_CODE_DESC,
        PRODUCT_GROUP_DESC,
        AMORTIZED_COST,
        FAIR_VALUE,
        PRICE,
        PRINCIPAL_GL_US_GAAP_BASE_EQ,
        DISCOUNT_GL_US_GAAP_BASE_EQ,
        PREMIUM_GL_US_GAAP_BASE_EQ,
        UNRLZED_PL_GL_US_GAAP_BASE_EQ,
        LTD_IMPAIRMENT_US_GAAP_BASE_EQ,
        SOURCE,
        IBF_ONLY_RAL_COLUMN_B_YN,
        CURRENCY_CODE,
        REGULATORY_RISK_RATINGS,
        LEVEL_FAIR_VALUE,
        ORIGINAL_PRICE,
        MATURITY_DATE,
        REMAINING_MATURITY,
        INT_RATE,
        FIXED_OR_VARIABLE,
        FLOATING_RATE,
        FIXED_RATE,
        INDEX_RATE_ADD,
        FLOAT_FREQ,
        MATURITY_BUCKETS,
        LAST_RATE_RESET_DATE,
        NEXT_RATE_RESET_DATE,
        DAY_COUNT_BASIS,
        PLEDGED_SECURITIES_YN,
        CMMP_TO_PURCHASE_SEC_YN,
        GUARANTOR,
        CUSTOMER_NAME,
        CUSTOMER_TYPE,
        CITY,
        OPERATING_STATE,
        COUNTRY_CODE,
        COUNTRY_DESC,
        FOREIGN_DOMESTIC,
        SECURITY_DESCRIPTION,
        "S&P_RATING",
        MOODYS_RATING,
        CUSIP,
        ISIN,
        TRADE_ID,
        CUSTOMER_ID,
        RELATED_DEP_INST,
        BRANCH_SUBSIDIARY,
        VAL_DATE,
        TRADE_DATE,
        SETTLE_DATE,
        LAST_PRIN_PMT,
        UMD1,
        UMD2,
        UMD3,
        UMD4,
        UMD5,
        UMD6,
        UMD7,
        UMD8,
        UMD9,
        UMD10,
        SYMB_POOL,
        PORTFOLIO,
        ACCOUNT_CAMRA,
        PRODUCT_CAMRA,
        ACCOUNT,
        PRODUCT,
        OPERATING_UNIT,
        AFFILIATE,
        CUST_CLASS,
        DISCOUNT_CODEBLOCK,
        PREMIUM_CODEBLOCK,
        UNRLZED_CODEBLOCK,
        LTD_IMPAIRMENT_CODEBLOCK,
        FILLER_1,
        FILLER_2,
        FILLER_3,
        FILLER_4,
        FILLER_5,
        FILLER_6,
        FILLER_7,
        FILLER_8,
        FILLER_9,
        FILLER_10,
        FILLER_11,
        FILLER_12,
        FILLER_13,
        FILLER_14,
        FILLER_15,
        FILLER_16,
        FILLER_17,
        FILLER_18,
        FILLER_19,
        FILLER_20,
        FILLER_21,
        FILLER_22,
        FILLER_23,
        FILLER_24,
        FILLER_25
    ) AS ROW_ID,
    H.MONTH_END_DATE,
    REPORTING_ENTITY,
    INSTRUMENT,
    INTERCOMPANY,
    CONSOL_NODE,
    BUSINESS_UNIT,
    GL_KEY_CODE,
    GL_KEY_CODE_DESC,
    CALL_CODE,
    CALL_CODE_DESC,
    PRODUCT_GROUP_DESC,
    AMORTIZED_COST,
    FAIR_VALUE,
    PRICE,
    PRINCIPAL_GL_US_GAAP_BASE_EQ,
    DISCOUNT_GL_US_GAAP_BASE_EQ,
    PREMIUM_GL_US_GAAP_BASE_EQ,
    UNRLZED_PL_GL_US_GAAP_BASE_EQ,
    LTD_IMPAIRMENT_US_GAAP_BASE_EQ,
    SOURCE,
    IBF_ONLY_RAL_COLUMN_B_YN,
    CURRENCY_CODE,
    REGULATORY_RISK_RATINGS,
    LEVEL_FAIR_VALUE,
    ORIGINAL_PRICE,
    MATURITY_DATE,
    REMAINING_MATURITY,
    INT_RATE,
    FIXED_OR_VARIABLE,
    FLOATING_RATE,
    FIXED_RATE,
    INDEX_RATE_ADD,
    FLOAT_FREQ,
    MATURITY_BUCKETS,
    LAST_RATE_RESET_DATE,
    NEXT_RATE_RESET_DATE,
    DAY_COUNT_BASIS,
    PLEDGED_SECURITIES_YN,
    CMMP_TO_PURCHASE_SEC_YN,
    GUARANTOR,
    CUSTOMER_NAME,
    CUSTOMER_TYPE,
    CITY,
    OPERATING_STATE,
    COUNTRY_CODE,
    COUNTRY_DESC,
    FOREIGN_DOMESTIC,
    SECURITY_DESCRIPTION,
    "S&P_RATING",
    MOODYS_RATING,
    CUSIP,
    ISIN,
    TRADE_ID,
    CUSTOMER_ID,
    RELATED_DEP_INST,
    BRANCH_SUBSIDIARY,
    VAL_DATE,
    TRADE_DATE,
    SETTLE_DATE,
    LAST_PRIN_PMT,
    UMD1,
    UMD2,
    UMD3,
    UMD4,
    UMD5,
    UMD6,
    UMD7,
    UMD8,
    UMD9,
    UMD10,
    SYMB_POOL,
    PORTFOLIO,
    ACCOUNT_CAMRA,
    PRODUCT_CAMRA,
    ACCOUNT,
    PRODUCT,
    OPERATING_UNIT,
    AFFILIATE,
    CUST_CLASS,
    DISCOUNT_CODEBLOCK,
    PREMIUM_CODEBLOCK,
    UNRLZED_CODEBLOCK,
    LTD_IMPAIRMENT_CODEBLOCK,
    FILLER_1,
    FILLER_2,
    FILLER_3,
    FILLER_4,
    FILLER_5,
    FILLER_6,
    FILLER_7,
    FILLER_8,
    FILLER_9,
    FILLER_10,
    FILLER_11,
    FILLER_12,
    FILLER_13,
    FILLER_14,
    FILLER_15,
    FILLER_16,
    FILLER_17,
    FILLER_18,
    FILLER_19,
    FILLER_20,
    FILLER_21,
    FILLER_22,
    FILLER_23,
    FILLER_24,
    FILLER_25
  FROM
    RB_HST_SECURITY H
    INNER JOIN
    (
      SELECT DISTINCT
        DATA_1 AS MONTH_END_DATE
     FROM
        FORM_DATI
      WHERE
        COD_SCENARIO = ${A2}
        AND COD_PERIODO = ${B2}
        AND COD_PROSPETTO = 'SECURITIES'
    ) F
   ON
     H.MONTH_END_DATE = F.MONTH_END_DATE
) P
ON
  A.ROW_ID = P.ROW_ID
  AND A.REPORTING_ENTITY = P.REPORTING_ENTITY
  AND (A.INSTRUMENT = P.INSTRUMENT OR (A.INSTRUMENT IS NULL AND P.INSTRUMENT IS NULL))