SELECT
(
  SELECT
    SUM(BASE_EQUIVALENT),
	SUM(PRINCIPAL_GL_US_GAAP_BASE_EQ),
	SUM(DEF_FEES_GL_US_GAAP_BASE_EQ),
	SUM(SPCFC_RESRV_GL_US_GAAP_BASE_EQ),
	SUM(FAC_OUTSTANDING_AVAILABLE_AMT)
  FROM
    RB_V_HST_LOAN S
  WHERE
    (
      USERUPD = ${user.code}
      AND (EXISTS(SELECT 1 FROM RB_V_HST_LOAN WHERE USERUPD = ${user.code}))
    )
    OR (
      DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_LOAN)
      AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_LOAN WHERE USERUPD = ${user.code}))
    )
) AS STG,
(
  SELECT
    SUM(IMPORTO_1) AS BASE_EQUIVALENT,
	SUM(IMPORTO_2) AS PRINCIPAL_GL_US_GAAP_BASE_EQ,
	SUM(IMPORTO_4) AS DEF_FEES_GL_US_GAAP_BASE_EQ,
	SUM(IMPORTO_6) AS SPCFC_RESRV_GL_US_GAAP_BASE_EQ,
	SUM(IMPORTO_24) AS FAC_OUTSTANDING_AVAILABLE_AMT
  FROM
    FORM_DATI A
    INNER JOIN
    (
      SELECT DISTINCT
        RB_F_TGK_CREATE_SCENARIO_CODE(MONTH_END_DATE) AS COD_SCENARIO,
        RB_F_TGK_CREATE_PERIOD_CODE(MONTH_END_DATE) AS COD_PERIODO,
        REPORTING_ENTITY
      FROM
        RB_V_HST_LOAN S
      WHERE
        (
          USERUPD = ${user.code}
          AND (EXISTS(SELECT 1 FROM RB_V_HST_LOAN WHERE USERUPD = ${user.code}))
        )
        OR (
          DATEUPD = (SELECT MAX(DATEUPD) FROM RB_V_HST_LOAN)
          AND (NOT EXISTS(SELECT 1 FROM RB_V_HST_LOAN WHERE USERUPD = ${user.code}))
        )
    ) S
  ON
	A.COD_SCENARIO = S.COD_SCENARIO
	AND A.COD_PERIODO = S.COD_PERIODO
	AND A.TESTO_1 = S.REPORTING_ENTITY
  WHERE
    A.COD_PROSPETTO = 'LOAN'
) AS APP
FROM
  DUAL