SELECT
  TESTO_1 AS REPORTING_ENTITY,
  TESTO_2 AS INSTRUMENT,
  TESTO_3 AS INTERCOMPANY,
  TESTO_4 AS CALL_CODE,
  IMPORTO_1 AS BASE_EQUIVALENT,
  TESTO_5 AS CUSTOMER_ID,
  TESTO_6 AS CUSTOMER_NAME,
  TESTO_7 AS CUSTOMER_TYPE,
  TESTO_8 AS RELATED_DEP_INST_YESNO,
  TESTO_9 AS PURPOSE_CODE,
  TESTO_10 AS FOREIGN_DOMESTIC,
  TESTO_11 AS COUNTRY_DESC,
  TESTO_12 AS RISK_COUNTRY,
  TESTO_13 AS OPERATING_STATE,
  TESTO_14 AS DAY_COUNT_BASIS,
  TESTO_15 AS HIGHLVL_PROD_CAT,
  TESTO_16 AS GL_KEY_CODE,
  IMPORTO_2 AS PRINCIPAL_GL_US_GAAP_BASE_EQ,
  IMPORTO_3 AS ACC_INT_GL_US_GAAP_BASE_EQ,
  IMPORTO_4 AS DEF_FEES_GL_US_GAAP_BASE_EQ,
  IMPORTO_5 AS UNEARNED_FEES_GL_IFRS_BASE_EQ,
  IMPORTO_6 AS SPCFC_RESRV_GL_US_GAAP_BASE_EQ,
  IMPORTO_7 AS INT_INC_GL_US_GAAP_BASE_EQ,
  IMPORTO_8 AS FEES_GL_US_GAAP_BASE_EQ,
  TESTO_17 AS CONSOL_NODE,
  TESTO_18 AS SUB_LE1,
  TESTO_19 AS SUB_LE2,
  TESTO_20 AS BUSINESS_UNIT,
  IMPORTO_9 AS LEGAL_CUST_TOTAL_COMMIT,
  IMPORTO_10 AS LEGAL_CUST_PRINC_FUNDED,
  IMPORTO_11 AS LEGAL_CUST_UNFUNDED_COMMIT,
  IMPORTO_12 AS BANK_SHARE_PRINC_US_GAAP,
  IMPORTO_13 AS BANK_SHARE_TOTAL_COMMIT,
  IMPORTO_14 AS BANK_SHARE_UNFUNDED_COMMIT,
  IMPORTO_15 AS BANK_SPECIFIC_RESRV_US_GAAP,
  IMPORTO_16 AS UNEARNED_FEES_US_GAAP,
  IMPORTO_17 AS CHARGED_OFF_US_GAAP,
  IMPORTO_18 AS ORIGINAL_PREMIUM_DISCOUNT,
  IMPORTO_19 AS REMAINING_PREMIUM_DISCOUNT,
  DATA_2 AS ORIGINATION_DATE,
  DATA_3 AS MATURITY_DATE,
  TESTO_21 AS REVOLVER_YN,
  DATA_4 AS RATE_EFFECTIVE_DATE,
  DATA_5 AS RATE_EXPIRATION_DATE,
  IMPORTO_20 AS INTEREST_RATE,
  TESTO_22 AS FIXED_OR_VARIABLE,
  TESTO_23 AS CUSTOMER_PARENT,
  IMPORTO_21 AS COF_FTP_RATE,
  IMPORTO_22 AS SPREAD,
  TESTO_24 AS PAST_DUE_YN,
  TESTO_25 AS TDR_YN,
  TESTO_33 AS DATE_TDR,
  TESTO_26 AS US_GAAP_RISK_RATING,
  IMPORTO_23 AS SYNDICATED_PARTICIPATED_LOAN,
  TESTO_27 AS AGENT_PARTICIPANT,
  TESTO_28 AS FACILITY_BORROWER_CIF,
  TESTO_29 AS FACILITY_TRADE_ID,
  IMPORTO_24 AS FAC_OUTSTANDING_AVAILABLE_AMT,
  TESTO_30 AS ACCOUNT,
  TESTO_31 AS PRODUCT,
  TESTO_32 AS CUST_CLASS
FROM
  FORM_DATI
WHERE
      COD_PROSPETTO = 'LOAN'
  AND COD_SCENARIO = ${A1}
  AND COD_PERIODO = ${B1}
  AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )