--------------------------------------------------------
--  DDL for View RB_V_OREO
--------------------------------------------------------
SET DEFINE OFF;


CREATE OR REPLACE NOFORCE VIEW "RB_V_OREO" (COD_SCENARIO,
                                            COD_PERIODO,
                                            COD_AZIENDA,
                                            COD_AZI_CTP,
                                            COD_CONTO,
                                            COD_CATEGORIA,
                                            COD_DEST1,
                                            COD_DEST2,
                                            COD_DEST2_CTP,
                                            COD_DEST3,
                                            COD_DEST4,
                                            COD_DEST5,
                                            COD_VALUTA,
                                            COD_VALUTA_ORIGINARIA,
                                            COD_REPORTING_ENTITY,
                                            "RB_ROWID",
                                            "MONTH_END_DATE",
                                            "REPORTING_ENTITY",
                                            "INTERCOMPANY",
                                            "CONSOL_NODE",
                                            "BUSINESS_UNIT",
                                            "GL_KEY_CODE",
                                            "GL_KEY_CODE_DESC",
                                            "CALL_CODE",
                                            "CALL_CODE_DESC",
                                            "LOAN_NUMBER",
                                            "INSTRUMENT_ID",
                                            "CONVERTED_INSTRUMENT_ID",
                                            "CALL_CODE_LOOKUP",
                                            "CURRENT_OREO_ASSET_NUMBER",
                                            "ENTITY_CHANGE",
                                            "DUPLICATE_LOAN_ON_ONE_PROPERTY",
                                            "FORECLOSURE_INDICATOR_DESCRPTN",
                                            "OREO_NEW_OREO_EVENT",
                                            "OREO_COST_CENTER",
                                            "OREO_INDICATOR",
                                            "OREO_NET_LIDQUIDATION_PROCEEDS",
                                            "OREO_NET_LIDQUIDATION_AMT",
                                            "OREO_SALE_DATE",
                                            "OREO_OFFSET_TO_CHARGE_OFF",
                                            "OREO_OPER_EXP_CLOSING_STMT",
                                            "OREO_VALUATION_ADJUSTMENT",
                                            "OREO_FINAL_SALE",
                                            "OREO_EVENT_DATE",
                                            "OREO_APPRAISAL_VALUE",
                                            "OREO_APPRAISAL_DATE",
                                            "OREO_CURRENT_BAL_ACCUMULATOR",
                                            "OREO_LOSS_ON_SALE",
                                            "OREO_PROJCTED_LIQUIDATION_DATE",
                                            "OREO_LOAN_PRIN_BAL_PRPTY_REV",
                                            "OREO_BEG_BAL_AT_CURRENT_YEAR",
                                            "OREO_NOTES",
                                            "OREO_COMPANY",
                                            "FORECLOSURE_START_DATE",
                                            "FORECLOSURE_SALE_DATE",
                                            "LOSS_SHARE_VALUE",
                                            "MATURITY_DATE",
                                            "MATURITY_BUCKETS",
                                            "LOSS_SHARING_AGREEMENT_YN",
                                            "SPV_YN",
                                            "ABCP_CONDUITS_YN",
                                            "VIE_YN",
                                            "REGULATORY_RISK_RATINGS",
                                            "LEVEL_FAIR_VALUE",
                                            "ACCOUNT",
                                            "PRODUCT",
                                            "OPERATING_UNIT",
                                            "AFFILIATE",
                                            "CUST_CLASS",
                                            "UMD1",
                                            "UMD2",
                                            "UMD3",
                                            "UMD4",
                                            "UMD5",
                                            "FILLER_1",
                                            "FILLER_2",
                                            "FILLER_3",
                                            "FILLER_4",
                                            "FILLER_5",
                                            "FILLER_6",
                                            "FILLER_7",
                                            "FILLER_8",
                                            "FILLER_9",
                                            "FILLER_10",
                                            "FILLER_11",
                                            "FILLER_12",
                                            "FILLER_13",
                                            "FILLER_14",
                                            "FILLER_15",
                                            "FILLER_16",
                                            "FILLER_17",
                                            "FILLER_18",
                                            "FILLER_19",
                                            "FILLER_20",
                                            "FILLER_21",
                                            "FILLER_22",
                                            "FILLER_23",
                                            "FILLER_24",
                                            "FILLER_25",
                                            PROVENIENZA,
                                            USERUPD,
                                            DATEUPD) AS
SELECT RB_F_TGK_CREATE_SCENARIO_CODE(KEYS.MONTH_END_DATE) AS COD_SCENARIO,
       RB_F_TGK_CREATE_PERIOD_CODE(KEYS.MONTH_END_DATE) AS COD_PERIODO,
       RB_F_TGK_SANITIZE_CODE(DATA01.BUSINESS_UNIT) AS COD_AZIENDA,
       RB_F_TGK_SANITIZE_CODE(DATA01.AFFILIATE) AS COD_AZI_CTP,
       RB_F_TGK_SANITIZE_CODE(DATA01.GL_KEY_CODE) AS COD_CONTO,
       'ORI' AS COD_CATEGORIA,
       RB_F_TGK_SANITIZE_CODE(DATA01.ACCOUNT) AS COD_DEST1,
       CASE
           WHEN DATA01.OPERATING_UNIT IS NOT NULL THEN 'BLC_'||RB_F_TGK_SANITIZE_CODE(DATA01.OPERATING_UNIT)
           WHEN NULL IS NOT NULL THEN 'DPT_'||RB_F_TGK_SANITIZE_CODE(NULL)
           ELSE RB_F_TGK_SANITIZE_CODE(NULL)
       END AS COD_DEST2,
       RB_F_TGK_SANITIZE_CODE(NULL) AS COD_DEST2_CTP,
       RB_F_TGK_SANITIZE_CODE(DATA01.PRODUCT) AS COD_DEST3,
       RB_F_TGK_SANITIZE_CODE(DATA01.CUST_CLASS) AS COD_DEST4,
       RB_F_TGK_SANITIZE_CODE(DATA01.CALL_CODE) AS COD_DEST5,
       RB_F_TGK_SANITIZE_CODE(A.COD_VALUTA) AS COD_VALUTA,
       RB_F_TGK_SANITIZE_CODE(A.COD_VALUTA) AS COD_VALUTA_ORIGINARIA,
       RB_F_TGK_SANITIZE_CODE(KEYS.REPORTING_ENTITY) AS COD_REPORTING_ENTITY,
       KEYS.RB_ROWID,
       KEYS.MONTH_END_DATE,
       KEYS.REPORTING_ENTITY,
       DATA01."INTERCOMPANY",
       DATA01."CONSOL_NODE",
       DATA01."BUSINESS_UNIT",
       DATA01."GL_KEY_CODE",
       DATA01."GL_KEY_CODE_DESC",
       DATA01."CALL_CODE",
       DATA01."CALL_CODE_DESC",
       DATA01."LOAN_NUMBER",
       DATA01."INSTRUMENT_ID",
       DATA01."CONVERTED_INSTRUMENT_ID",
       DATA01."CALL_CODE_LOOKUP",
       DATA01."CURRENT_OREO_ASSET_NUMBER",
       DATA01."ENTITY_CHANGE",
       DATA01."DUPLICATE_LOAN_ON_ONE_PROPERTY",
       DATA01."FORECLOSURE_INDICATOR_DESCRPTN",
       DATA01."OREO_NEW_OREO_EVENT",
       DATA01."OREO_COST_CENTER",
       DATA01."OREO_INDICATOR",
       DATA01."OREO_NET_LIDQUIDATION_PROCEEDS",
       DATA01."OREO_NET_LIDQUIDATION_AMT",
       DATA01."OREO_SALE_DATE",
       DATA01."OREO_OFFSET_TO_CHARGE_OFF",
       DATA01."OREO_OPER_EXP_CLOSING_STMT",
       DATA01."OREO_VALUATION_ADJUSTMENT",
       DATA01."OREO_FINAL_SALE",
       DATA01."OREO_EVENT_DATE",
       DATA01."OREO_APPRAISAL_VALUE",
       DATA01."OREO_APPRAISAL_DATE",
       DATA01."OREO_CURRENT_BAL_ACCUMULATOR",
       DATA01."OREO_LOSS_ON_SALE",
       DATA01."OREO_PROJCTED_LIQUIDATION_DATE",
       DATA01."OREO_LOAN_PRIN_BAL_PRPTY_REV",
       DATA01."OREO_BEG_BAL_AT_CURRENT_YEAR",
       DATA01."OREO_NOTES",
       DATA01."OREO_COMPANY",
       DATA01."FORECLOSURE_START_DATE",
       DATA01."FORECLOSURE_SALE_DATE",
       DATA01."LOSS_SHARE_VALUE",
       DATA01."MATURITY_DATE",
       DATA01."MATURITY_BUCKETS",
       DATA01."LOSS_SHARING_AGREEMENT_YN",
       DATA01."SPV_YN",
       DATA01."ABCP_CONDUITS_YN",
       DATA01."VIE_YN",
       DATA01."REGULATORY_RISK_RATINGS",
       DATA01."LEVEL_FAIR_VALUE",
       DATA01."ACCOUNT",
       DATA01."PRODUCT",
       DATA01."OPERATING_UNIT",
       DATA01."AFFILIATE",
       DATA01."CUST_CLASS",
       DATA01."UMD1",
       DATA01."UMD2",
       DATA01."UMD3",
       DATA01."UMD4",
       DATA01."UMD5",
       DATA01."FILLER_1",
       DATA01."FILLER_2",
       DATA01."FILLER_3",
       DATA01."FILLER_4",
       DATA01."FILLER_5",
       DATA01."FILLER_6",
       DATA01."FILLER_7",
       DATA01."FILLER_8",
       DATA01."FILLER_9",
       DATA01."FILLER_10",
       DATA01."FILLER_11",
       DATA01."FILLER_12",
       DATA01."FILLER_13",
       DATA01."FILLER_14",
       DATA01."FILLER_15",
       DATA01."FILLER_16",
       DATA01."FILLER_17",
       DATA01."FILLER_18",
       DATA01."FILLER_19",
       DATA01."FILLER_20",
       DATA01."FILLER_21",
       DATA01."FILLER_22",
       DATA01."FILLER_23",
       DATA01."FILLER_24",
       DATA01."FILLER_25",
       DATA01.PROVENIENZA,
       DATA01.USERUPD,
       DATA01.DATEUPD
FROM
  (SELECT DISTINCT MONTH_END_DATE,
                   REPORTING_ENTITY,
                   RB_ROWID
   FROM RB_HST_OREO_01) KEYS
INNER JOIN
  (SELECT "RB_ROWID",
          "MONTH_END_DATE",
          "REPORTING_ENTITY",
          "INTERCOMPANY",
          "CONSOL_NODE",
          "BUSINESS_UNIT",
          "GL_KEY_CODE",
          "GL_KEY_CODE_DESC",
          "CALL_CODE",
          "CALL_CODE_DESC",
          "LOAN_NUMBER",
          "INSTRUMENT_ID",
          "CONVERTED_INSTRUMENT_ID",
          "CALL_CODE_LOOKUP",
          "CURRENT_OREO_ASSET_NUMBER",
          "ENTITY_CHANGE",
          "DUPLICATE_LOAN_ON_ONE_PROPERTY",
          "FORECLOSURE_INDICATOR_DESCRPTN",
          "OREO_NEW_OREO_EVENT",
          "OREO_COST_CENTER",
          "OREO_INDICATOR",
          "OREO_NET_LIDQUIDATION_PROCEEDS",
          "OREO_NET_LIDQUIDATION_AMT",
          "OREO_SALE_DATE",
          "OREO_OFFSET_TO_CHARGE_OFF",
          "OREO_OPER_EXP_CLOSING_STMT",
          "OREO_VALUATION_ADJUSTMENT",
          "OREO_FINAL_SALE",
          "OREO_EVENT_DATE",
          "OREO_APPRAISAL_VALUE",
          "OREO_APPRAISAL_DATE",
          "OREO_CURRENT_BAL_ACCUMULATOR",
          "OREO_LOSS_ON_SALE",
          "OREO_PROJCTED_LIQUIDATION_DATE",
          "OREO_LOAN_PRIN_BAL_PRPTY_REV",
          "OREO_BEG_BAL_AT_CURRENT_YEAR",
          "OREO_NOTES",
          "OREO_COMPANY",
          "FORECLOSURE_START_DATE",
          "FORECLOSURE_SALE_DATE",
          "LOSS_SHARE_VALUE",
          "MATURITY_DATE",
          "MATURITY_BUCKETS",
          "LOSS_SHARING_AGREEMENT_YN",
          "SPV_YN",
          "ABCP_CONDUITS_YN",
          "VIE_YN",
          "REGULATORY_RISK_RATINGS",
          "LEVEL_FAIR_VALUE",
          "ACCOUNT",
          "PRODUCT",
          "OPERATING_UNIT",
          "AFFILIATE",
          "CUST_CLASS",
          "UMD1",
          "UMD2",
          "UMD3",
          "UMD4",
          "UMD5",
          "FILLER_1",
          "FILLER_2",
          "FILLER_3",
          "FILLER_4",
          "FILLER_5",
          "FILLER_6",
          "FILLER_7",
          "FILLER_8",
          "FILLER_9",
          "FILLER_10",
          "FILLER_11",
          "FILLER_12",
          "FILLER_13",
          "FILLER_14",
          "FILLER_15",
          "FILLER_16",
          "FILLER_17",
          "FILLER_18",
          "FILLER_19",
          "FILLER_20",
          "FILLER_21",
          "FILLER_22",
          "FILLER_23",
          "FILLER_24",
          "FILLER_25",
          PROVENIENZA,
          USERUPD,
          DATEUPD
   FROM RB_HST_OREO_01) DATA01 ON KEYS.MONTH_END_DATE = DATA01.MONTH_END_DATE
AND KEYS.REPORTING_ENTITY = DATA01.REPORTING_ENTITY
AND KEYS.RB_ROWID = DATA01.RB_ROWID
LEFT OUTER JOIN
AZIENDA A 
ON RB_F_TGK_SANITIZE_CODE(DATA01.BUSINESS_UNIT) = A.COD_AZIENDA