--------------------------------------------------------
--  DDL for View RB_V_GL
--------------------------------------------------------

CREATE OR REPLACE NOFORCE VIEW "RB_V_GL" (
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_AZI_CTP,
  COD_CONTO,
  COD_CATEGORIA,
  COD_DEST1,
  COD_DEST2,
  COD_DEST2_CTP,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  IMPORTO,
  IMPORTO_VALUTA_ORIGINARIA,
  PROJECT_ID,
  DEPTID,
  OPERATING_UNIT,
  US_COA_ACCOUNT,
  REPORTING_ENTITY,
  PROVENIENZA,
  USERUPD,
  DATEUPD
) AS
SELECT
  RB_F_TGK_CREATE_SCENARIO_CODE(TO_DATE(FISCAL_YEAR||'12'||'31', 'YYYYMMDD')) AS COD_SCENARIO,
  RB_F_TGK_SANITIZE_CODE(COD_PERIODO) AS COD_PERIODO,
  RB_F_TGK_SANITIZE_CODE(BUSINESS_UNIT) AS COD_AZIENDA,
  RB_F_TGK_SANITIZE_CODE(AFFILIATE) AS COD_AZI_CTP,
  RB_F_TGK_SANITIZE_CODE(ACCOUNT) AS COD_CONTO,
  CASE
	WHEN RB_BALANCE_TYPE = 'EOM' THEN 'GL_DATA'
	WHEN RB_BALANCE_TYPE = 'MTDAVG' THEN 'MTD_AVG'
	WHEN RB_BALANCE_TYPE = 'QTDAVG' THEN 'QTD_AVG'
	WHEN RB_BALANCE_TYPE = 'YTDAVG' THEN 'YTD_AVG'
	ELSE NULL
  END AS COD_CATEGORIA,
  RB_F_TGK_SANITIZE_CODE(GL_KEY_CODE) AS COD_DEST1,
  CASE
	WHEN OPERATING_UNIT IS NOT NULL THEN 'BLC_'||RB_F_TGK_SANITIZE_CODE(OPERATING_UNIT) 
	WHEN DEPTID IS NOT NULL THEN 'DPT_'||RB_F_TGK_SANITIZE_CODE(DEPTID) 
	ELSE RB_F_TGK_SANITIZE_CODE(NULL)
  END AS COD_DEST2,
  CASE
	WHEN OBU_AFFILIATE IS NOT NULL THEN 'BLC_'||RB_F_TGK_SANITIZE_CODE(OBU_AFFILIATE) 
	ELSE RB_F_TGK_SANITIZE_CODE(NULL)
  END AS COD_DEST2_CTP,
  RB_F_TGK_SANITIZE_CODE(PRODUCT) AS COD_DEST3,
  RB_F_TGK_SANITIZE_CODE(CUST_CLASS) AS COD_DEST4,
  RB_F_TGK_SANITIZE_CODE(CAST(NULL AS VARCHAR(30))) AS COD_DEST5,
  BASE_CURRENCY AS COD_VALUTA,
  CURRENCY_CODE AS COD_VALUTA_ORIGINARIA,
  IMPORTO,
  IMPORTO_VALUTA_ORIGINARIA AS IMPORTO_VALUTA_ORIGINARIA,
  RB_F_TGK_SANITIZE_CODE(PROJECT_ID) AS PROJECT_ID,
	RB_F_TGK_SANITIZE_CODE(DEPTID) AS DEPTID,
  RB_F_TGK_SANITIZE_CODE(OPERATING_UNIT) AS OPERATING_UNIT,
  RB_F_TGK_SANITIZE_CODE(US_COA_ACCOUNT, 1) AS US_COA_ACCOUNT,
  RB_F_TGK_SANITIZE_CODE(REPORTING_ENTITY) AS REPORTING_ENTITY,
  PROVENIENZA,
  USERUPD,
  DATEUPD
FROM
  (
        SELECT
          DATA.REPORTING_ENTITY,
          DATA.GL_KEY_CODE,
          DATA.CONSOL_NODE,
          DATA.BUSINESS_UNIT,
          DATA.OPERATING_UNIT,
          DATA.RB_BALANCE_TYPE,
          DATA.SOURCE,
          DATA.FISCAL_YEAR,
          DATA.BASE_CURRENCY,
         COALESCE(DATA.JAN_BASE, 0) AS JAN_BASE,
          COALESCE(DATA.FEB_BASE, 0) AS FEB_BASE,
          COALESCE(DATA.MAR_BASE, 0) AS MAR_BASE,
          COALESCE(DATA.APR_BASE, 0) AS APR_BASE,
          COALESCE(DATA.MAY_BASE, 0) AS MAY_BASE,
          COALESCE(DATA.JUNE_BASE, 0) AS JUNE_BASE,
          COALESCE(DATA.JULY_BASE, 0) AS JULY_BASE,
          COALESCE(DATA.AUG_BASE, 0) AS AUG_BASE,
          COALESCE(DATA.SEP_BASE, 0) AS SEP_BASE,
          COALESCE(DATA.OCT_BASE, 0) AS OCT_BASE,
          COALESCE(DATA.NOV_BASE, 0) AS NOV_BASE,
          COALESCE(DATA.DEC_BASE, 0) AS DEC_BASE,
          DATA.CURRENCY_CODE,
          COALESCE(DATA.JAN_ORIG, 0) AS JAN_ORIG,
          COALESCE(DATA.FEB_ORIG, 0) AS FEB_ORIG,
          COALESCE(DATA.MAR_ORIG, 0) AS MAR_ORIG,
          COALESCE(DATA.APR_ORIG, 0) AS APR_ORIG,
          COALESCE(DATA.MAY_ORIG, 0) AS MAY_ORIG,
          COALESCE(DATA.JUNE_ORIG, 0) AS JUNE_ORIG,
          COALESCE(DATA.JULY_ORIG, 0) AS JULY_ORIG,
          COALESCE(DATA.AUG_ORIG, 0) AS AUG_ORIG,
          COALESCE(DATA.SEP_ORIG, 0) AS SEP_ORIG,
          COALESCE(DATA.OCT_ORIG, 0) AS OCT_ORIG,
          COALESCE(DATA.NOV_ORIG, 0) AS NOV_ORIG,
          COALESCE(DATA.DEC_ORIG, 0) AS DEC_ORIG,
          DATA.ACCOUNT,
          DATA.DEPTID,
          DATA.PRODUCT,
          DATA.CUST_CLASS,
          DATA.AFFILIATE,
          DATA.OBU_AFFILIATE,
          DATA.PROJECT_ID,
          DATA.US_COA_ACCOUNT,
          DATA.PROVENIENZA,
          DATA.USERUPD,
          DATA.DATEUPD
        FROM
              RB_HST_GL_01 DATA
        )
        UNPIVOT (
          (IMPORTO, IMPORTO_VALUTA_ORIGINARIA) FOR COD_PERIODO IN (
            (JAN_BASE, JAN_ORIG) AS '01',
            (FEB_BASE, FEB_ORIG) AS '02',
            (MAR_BASE, MAR_ORIG) AS '03',
            (APR_BASE, APR_ORIG) AS '04',
            (MAY_BASE, MAY_ORIG) AS '05',
            (JUNE_BASE, JUNE_ORIG) AS '06',
            (JULY_BASE, JULY_ORIG) AS '07',
            (AUG_BASE, AUG_ORIG) AS '08',
            (SEP_BASE, SEP_ORIG) AS '09',
            (OCT_BASE, OCT_ORIG) AS '10',
            (NOV_BASE, NOV_ORIG) AS '11',
            (DEC_BASE, DEC_ORIG) AS '12'
          )
        )
;
