--------------------------------------------------------
--  DDL for View RB_V_APP_GL
--------------------------------------------------------

CREATE OR REPLACE NOFORCE VIEW "RB_V_APP_GL" (
	OID_DATI_SALDI_LORDI,
	COD_SCENARIO,
	COD_PERIODO,
	COD_CONTO,
	COD_AZIENDA,
	COD_AZI_CTP,
	COD_CATEGORIA,
	COD_DEST1,
	COD_DEST2,
	COD_DEST2_CTP,
	COD_DEST3,
	COD_DEST4,
	COD_DEST5,
	COD_VALUTA,
	COD_VALUTA_ORIGINARIA,
	NOTE,
	IMPORTO,
	IMPORTO_VALUTA_ORIGINARIA
) AS
SELECT
	OID_FORM_DATI AS OID_DATI_SALDI_LORDI,
	COD_SCENARIO,
	COD_PERIODO,
	COD_CONTO,
	COD_AZIENDA,
	COD_AZI_CTP,
	COD_CATEGORIA,
	COD_DEST1,
	COD_DEST2,
	COD_DEST2_CTP,
	COD_DEST3,
	COD_DEST4,
	COD_DEST5,
	COD_VALUTA,
	COD_VALUTA_ORIGINARIA,
	TESTO_1 AS NOTE,
	IMPORTO_1 AS IMPORTO,
	IMPORTO_2 AS IMPORTO_VALUTA_ORIGINARIA
FROM
	FORM_DATI
 WHERE
	COD_PROSPETTO = 'GL'