DELETE FORM_DATI
WHERE
  COD_PROSPETTO = 'GL'
;

INSERT INTO FORM_DATI (
  OID_FORM_DATI,
  COD_PROSPETTO,
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_CATEGORIA,
  COD_AZI_CTP,
  COD_DEST2_CTP,
  COD_VALUTA_ORIGINARIA,
  IMPORTO_2,
  COD_VALUTA,
  IMPORTO_1,
  TESTO_1,
  PROVENIENZA,
  USERUPD,
  DATEUPD
)
SELECT
  sys_guid() AS OID_FORM_DATI,
  'GL' AS COD_PROSPETTO,
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_CATEGORIA,
  COD_AZI_CTP,
  COD_DEST2_CTP,
  COD_VALUTA_ORIGINARIA,
  SUM(IMPORTO_VALUTA_ORIGINARIA) AS IMPORTO_VALUTA_ORIGINARIA,
  COD_VALUTA,
  SUM(IMPORTO) AS IMPORTO,
  NOTE,
  'MAP_RB_AL_GL_30' AS PROVENIENZA,
  MAX(USERUPD) AS USERUPD,
  MAX(DATEUPD) AS DATEUPD
FROM
  (
    SELECT
      COD_SCENARIO,
      COD_PERIODO,
      COD_AZIENDA,
      COD_CONTO,
      COD_DEST1,
      COD_DEST2,
      COD_DEST3,
      COD_DEST4,
      COD_DEST5,
      COD_CATEGORIA,
      RB_F_TGK_SANITIZE_CODE(NULL) AS COD_AZI_CTP,
      RB_F_TGK_SANITIZE_CODE(NULL) AS COD_DEST2_CTP,
      COD_VALUTA_ORIGINARIA,
      IMPORTO_VALUTA_ORIGINARIA,
      COD_VALUTA,
      IMPORTO,
      NOTE,
      USERUPD,
      DATEUPD
    FROM
      DATI_SALDI_LORDI
    WHERE
      PROVENIENZA LIKE ('MAP_RB_AL_GL_%')
    UNION ALL
    SELECT
      COD_SCENARIO,
      COD_PERIODO,
      COD_AZIENDA,
      COD_CONTO,
      COD_DEST1,
      COD_DEST2,
      COD_DEST3,
      COD_DEST4,
      COD_DEST5,
      COD_CATEGORIA,
      RB_F_TGK_SANITIZE_CODE(NULL) AS COD_AZI_CTP,
      RB_F_TGK_SANITIZE_CODE(NULL) AS COD_DEST2_CTP,
      COD_VALUTA_DOC AS COD_VALUTA_ORIGINARIA,
      -IMPORTO_VALUTA_DOC AS IMPORTO_VALUTA_ORIGINARIA,
      COD_VALUTA,
      -IMPORTO,
      NOTE,
      USERUPD,
      DATEUPD
    FROM
      DATI_SALDI_IC
    WHERE
      PROVENIENZA LIKE ('MAP_RB_AL_GL_%')
    UNION ALL
    SELECT
      COD_SCENARIO,
      COD_PERIODO,
      COD_AZIENDA,
      COD_CONTO,
      COD_DEST1,
      COD_DEST2,
      COD_DEST3,
      COD_DEST4,
      COD_DEST5,
      COD_CATEGORIA,
      COD_AZI_CTP,
      COD_DEST2_CTP,
      COD_VALUTA_DOC AS COD_VALUTA_ORIGINARIA,
      IMPORTO_VALUTA_DOC AS IMPORTO_VALUTA_ORIGINARIA,
      COD_VALUTA,
      IMPORTO,
      NOTE,
      USERUPD,
      DATEUPD
    FROM
      DATI_SALDI_IC
    WHERE
      PROVENIENZA LIKE ('MAP_RB_AL_GL_%')
  ) GL
GROUP BY
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_CATEGORIA,
  COD_AZI_CTP,
  COD_DEST2_CTP,
  COD_VALUTA_ORIGINARIA,
  COD_VALUTA,
  NOTE
HAVING
  SUM(IMPORTO) <> 0
  OR SUM(IMPORTO_VALUTA_ORIGINARIA) <> 0
;