DROP INDEX IX_RB_HST_CASH_01_GLKC;
CREATE INDEX IX_RB_HST_CASH_01_GLKC
ON RB_HST_CASH_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_CASH_01_CC;
CREATE INDEX IX_RB_HST_CASH_01_CC
ON RB_HST_CASH_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_LOAN_01_GLKC;
CREATE INDEX IX_RB_HST_LOAN_01_GLKC
ON RB_HST_LOAN_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_LOAN_01_CC;
CREATE INDEX IX_RB_HST_LOAN_01_CC
ON RB_HST_LOAN_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_SECURITY_GLKC;
CREATE INDEX IX_RB_HST_SECURITY_GLKC
ON RB_HST_SECURITY (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_SECURITY_CC;
CREATE INDEX IX_RB_HST_SECURITY_CC
ON RB_HST_SECURITY (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_OFF_BS_01_GLKC;
CREATE INDEX IX_RB_HST_OFF_BS_01_GLKC
ON RB_HST_OFF_BS_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_OFF_BS_01_CC;
CREATE INDEX IX_RB_HST_OFF_BS_01_CC
ON RB_HST_OFF_BS_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_DERIVATIVES_01_GLKC;
CREATE INDEX IX_RB_HST_DERIVATIVES_01_GLKC
ON RB_HST_DERIVATIVES_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_DERIVATIVES_01_CC;
CREATE INDEX IX_RB_HST_DERIVATIVES_01_CC
ON RB_HST_DERIVATIVES_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_BORROWINGS_01_GLKC;
CREATE INDEX IX_RB_HST_BORROWINGS_01_GLKC
ON RB_HST_BORROWINGS_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_BORROWINGS_01_CC;
CREATE INDEX IX_RB_HST_BORROWINGS_01_CC
ON RB_HST_BORROWINGS_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_GL_01_GLKC;
CREATE INDEX IX_RB_HST_GL_01_GLKC
ON RB_HST_GL_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING; 
DROP INDEX IX_RB_HST_CASH_01_GLKC;
CREATE INDEX IX_RB_HST_CASH_01_GLKC
ON RB_HST_CASH_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_CASH_01_CC;
CREATE INDEX IX_RB_HST_CASH_01_CC
ON RB_HST_CASH_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_LOAN_01_GLKC;
CREATE INDEX IX_RB_HST_LOAN_01_GLKC
ON RB_HST_LOAN_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_LOAN_01_CC;
CREATE INDEX IX_RB_HST_LOAN_01_CC
ON RB_HST_LOAN_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_SECURITY_GLKC;
CREATE INDEX IX_RB_HST_SECURITY_GLKC
ON RB_HST_SECURITY (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_SECURITY_CC;
CREATE INDEX IX_RB_HST_SECURITY_CC
ON RB_HST_SECURITY (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_OFF_BS_01_GLKC;
CREATE INDEX IX_RB_HST_OFF_BS_01_GLKC
ON RB_HST_OFF_BS_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_OFF_BS_01_CC;
CREATE INDEX IX_RB_HST_OFF_BS_01_CC
ON RB_HST_OFF_BS_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_DERIVATIVES_01_GLKC;
CREATE INDEX IX_RB_HST_DERIVATIVES_01_GLKC
ON RB_HST_DERIVATIVES_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_DERIVATIVES_01_CC;
CREATE INDEX IX_RB_HST_DERIVATIVES_01_CC
ON RB_HST_DERIVATIVES_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_BORROWINGS_01_GLKC;
CREATE INDEX IX_RB_HST_BORROWINGS_01_GLKC
ON RB_HST_BORROWINGS_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_BORROWINGS_01_CC;
CREATE INDEX IX_RB_HST_BORROWINGS_01_CC
ON RB_HST_BORROWINGS_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

DROP INDEX IX_RB_HST_GL_01_GLKC;
CREATE INDEX IX_RB_HST_GL_01_GLKC
ON RB_HST_GL_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;