CREATE TABLE T_NEW AS 
SELECT
  OID_FORM_DATI,
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_CATEGORIA,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  TESTO_1 AS NOTE
FROM
  FORM_DATI
WHERE
  COD_PROSPETTO = 'GL'
;

CREATE UNIQUE INDEX UI_T_NEW_ALL
ON T_NEW (
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_CATEGORIA,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  NOTE,
  OID_FORM_DATI
)
;

CREATE TABLE T_OLD AS
SELECT DISTINCT
  DRILL.OID_FORM_DATI,
  DSL.COD_SCENARIO,
  DSL.COD_PERIODO,
  DSL.COD_AZIENDA,
  DSL.COD_CONTO,
  DSL.COD_DEST1,
  DSL.COD_DEST2,
  DSL.COD_DEST3,
  DSL.COD_DEST4,
  DSL.COD_DEST5,
  DSL.COD_CATEGORIA,
  DSL.COD_VALUTA,
  DSL.COD_VALUTA_ORIGINARIA,
  DSL.NOTE
FROM
  RB_DRILL_INSTRUMENT DRILL
  INNER JOIN
  DATI_SALDI_LORDI DSL
  ON
    DRILL.OID_FORM_DATI = DSL.OID_DATI_SALDI_LORDI
;

CREATE UNIQUE INDEX UI_T_OLD_ALL
ON T_OLD (
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_CATEGORIA,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  NOTE,
  OID_FORM_DATI
)
;

CREATE TABLE T AS
SELECT DISTINCT
  O.OID_FORM_DATI AS OID_FORM_DATI_O,
  N.OID_FORM_DATI AS OID_FORM_DATI_N
FROM
  T_OLD O
  INNER JOIN
  T_NEW N
  ON
    O.COD_SCENARIO = N.COD_SCENARIO
    AND O.COD_PERIODO = N.COD_PERIODO
    AND O.COD_AZIENDA = N.COD_AZIENDA
    AND O.COD_CONTO = N.COD_CONTO
    AND O.COD_DEST1 = N.COD_DEST1
    AND O.COD_DEST2 = N.COD_DEST2
    AND O.COD_DEST3 = N.COD_DEST3
    AND O.COD_DEST4 = N.COD_DEST4
    AND O.COD_DEST5 = N.COD_DEST5
    AND O.COD_CATEGORIA = N.COD_CATEGORIA
    AND O.COD_VALUTA = N.COD_VALUTA
    AND O.COD_VALUTA_ORIGINARIA = N.COD_VALUTA_ORIGINARIA
    AND O.NOTE = N.NOTE
;

DROP TABLE T_OLD;
DROP TABLE T_NEW;

CREATE UNIQUE INDEX UI_T_ALL
ON T (OID_FORM_DATI_O, OID_FORM_DATI_N)
;

CREATE TABLE T_TR AS
SELECT 
  DRILL.*,
  T.OID_FORM_DATI_N
FROM
  RB_DRILL_INSTRUMENT DRILL
  INNER JOIN
  T
  ON
    DRILL.OID_FORM_DATI = T.OID_FORM_DATI_O
;

DELETE RB_DRILL_INSTRUMENT
WHERE
  OID_FORM_DATI IN (SELECT DISTINCT OID_FORM_DATI_O FROM T)
;

DROP TABLE T;

INSERT INTO RB_DRILL_INSTRUMENT (
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_AZI_CTP,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_DEST2_CTP,
  COD_CATEGORIA,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  OID_FORM_DATI,
  PROVENIENZA,
  USERUPD,
  DATEUPD
)
SELECT DISTINCT
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_AZI_CTP,
  COD_CONTO,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_DEST2_CTP,
  COD_CATEGORIA,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  OID_FORM_DATI_N AS OID_FORM_DATI,
  PROVENIENZA,
  USERUPD,
  DATEUPD
FROM
  T_TR
;

DROP TABLE T_TR;