--------------------------------------------------------
--  DDL - DROP for Table RB_HST_DEPOSITS_01
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_DEPOSITS_01"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;

  /
--------------------------------------------------------
--  DDL for Table RB_HST_DEPOSITS_01
--------------------------------------------------------

CREATE TABLE "RB_HST_DEPOSITS_01" (
  "ACCOUNT_DEPOSIT_CATEGORY_DESC" VARCHAR2(25 BYTE), 
  "ACCOUNT_TYPE_DESCRIPTION" VARCHAR2(50 BYTE), 
  "INSTRUMENT_ID" VARCHAR2(30 BYTE), 
  "CUSTOMER_NAME" VARCHAR2(150 BYTE), 
  "ACCOUNT_LEDGER_BALANCE" NUMBER(23,3), 
  "ACCT_AVG_YTD_LEDGER_BAL_AMT" NUMBER(23,3), 
  "ACCT_WAR_AVG_MTD_LGR_BAL" NUMBER(23,3), 
  "ACCT_CTD_INT_ACCRUAL" NUMBER(23,3), 
  "CALL_CODE" VARCHAR2(15 BYTE), 
  "CALL_CODE_DESC" VARCHAR2(150 BYTE), 
  "UMD_1" NUMBER(23,3), 
  "UMD_2" NUMBER(23,3), 
  "UMD_3" NUMBER(23,3), 
  "REMAINING_MATURITY_DAYS" NUMBER(23,0), 
  "MATURITY_BUCKETS" VARCHAR2(50 BYTE), 
  "UNDER_OVER_BALANCE" VARCHAR2(50 BYTE), 
  "UMD_4" NUMBER(23,3), 
  "UMD_5" NUMBER(23,3), 
  "UMD_6" VARCHAR2(250 BYTE), 
  "INSTRUMENT" VARCHAR2(27 BYTE), 
  "INTERCOMPANY" VARCHAR2(15 BYTE), 
  "CONSOL_NODE" VARCHAR2(20 BYTE), 
  "BUSINESS_UNIT" VARCHAR2(5 BYTE), 
  "GL_KEY_CODE" VARCHAR2(15 BYTE), 
  "GL_KEY_CODE_DESC" VARCHAR2(150 BYTE), 
  "BASE_EQUIVALENT" NUMBER(23,3), 
  "PRINCIPAL_ORIG_CCY" NUMBER(23,3), 
  "DISCOUNT_GIVEN_ORIG_CCY" NUMBER(23,3), 
  "TRANS_ACCT_ORIG_CCY" NUMBER(23,3), 
  "PRINCIPAL_BASE_EQ" NUMBER(23,3), 
  "DISCOUNT_GIVEN_BASE_EQ" NUMBER(23,3), 
  "TRANS_ACCT_BASE_EQ" NUMBER(23,3), 
  "DISCOUNT_RECEIVED_ORIG_CCY" NUMBER(23,3), 
  "ACCRUED_INTEREST_ORIG_CCY" NUMBER(23,3), 
  "ACCRUED_INTEREST_ORIG_CCY_2" NUMBER(23,3), 
  "DISCOUNT_RECEIVED_BASE_EQ" NUMBER(23,3), 
  "ACCRUED_INTEREST_BASE_EQ" NUMBER(23,3), 
  "ACCRUED_INTEREST_BASE_EQ_2" NUMBER(23,3), 
  "INCOME_EXPENSE_ORIG_CCY_1" NUMBER(23,3), 
  "INCOME_EXPENSE_ORIG_CCY_2" NUMBER(23,3), 
  "INCOME_EXPENSE_ORIG_CCY_3" NUMBER(23,3), 
  "INCOME_EXPENSE_ORIG_CCY_4" NUMBER(23,3), 
  "INCOME_EXPENSE_ORIG_CCY_5" NUMBER(23,3), 
  "INCOME_EXPENSE_BASE_EQ_1" NUMBER(23,3), 
  "INCOME_EXPENSE_BASE_EQ_2" NUMBER(23,3), 
  "INCOME_EXPENSE_BASE_EQ_3" NUMBER(23,3), 
  "INCOME_EXPENSE_BASE_EQ_4" NUMBER(23,3), 
  "INCOME_EXPENSE_BASE_EQ_5" NUMBER(23,3), 
  "IRA_INDICATOR" VARCHAR2(10 BYTE), 
  "UNDER_OVER_BALANCE_2" VARCHAR2(50 BYTE), 
  "MATURITY_BUCKETS_2" VARCHAR2(50 BYTE), 
  "MATURITY_BUCKETS_3" VARCHAR2(50 BYTE), 
  "CUSTOMER_TYPE" VARCHAR2(30 BYTE), 
  "COUNTRY_DESC" VARCHAR2(30 BYTE), 
  "CIF_TYPE" VARCHAR2(20 BYTE), 
  "CIF_TYPE_DESCRIPTION" VARCHAR2(50 BYTE), 
  "DEPO_NON-DEPO" VARCHAR2(25 BYTE), 
  "TRADE_ID" VARCHAR2(20 BYTE), 
  "REPORTABLE_Y_N" VARCHAR2(10 BYTE), 
  "ACCOUNT" VARCHAR2(30 BYTE), 
  "PRODUCT" VARCHAR2(10 BYTE), 
  "DEPTID" VARCHAR2(15 BYTE), 
  "DISC_GIVEN_CALL_CODE_CODEBLOCK" VARCHAR2(100 BYTE), 
  "TRANS_ACCT_CALL_CODE_CODEBLK" VARCHAR2(100 BYTE), 
  "UMD_7" VARCHAR2(250 BYTE), 
  "UMD_8" VARCHAR2(250 BYTE), 
  "UMD_9" NUMBER(23,3), 
  "FILLER_1" VARCHAR2(250 BYTE), 
  "FILLER_2" VARCHAR2(250 BYTE), 
  "FILLER_3" VARCHAR2(250 BYTE), 
  "FILLER_4" VARCHAR2(250 BYTE), 
  "FILLER_5" VARCHAR2(250 BYTE), 
  "FILLER_6" VARCHAR2(250 BYTE), 
  "FILLER_7" VARCHAR2(250 BYTE), 
  "FILLER_8" VARCHAR2(250 BYTE), 
  "FILLER_9" VARCHAR2(250 BYTE), 
  "FILLER_10" VARCHAR2(250 BYTE), 
  "FILLER_11" VARCHAR2(250 BYTE), 
  "FILLER_12" VARCHAR2(250 BYTE), 
  "FILLER_13" VARCHAR2(250 BYTE), 
  "FILLER_14" VARCHAR2(250 BYTE), 
  "FILLER_15" VARCHAR2(250 BYTE), 
  "FILLER_16" VARCHAR2(250 BYTE), 
  "FILLER_17" VARCHAR2(250 BYTE), 
  "FILLER_18" VARCHAR2(250 BYTE), 
  "FILLER_19" VARCHAR2(250 BYTE), 
  "FILLER_20" VARCHAR2(250 BYTE), 
  "FILLER_21" VARCHAR2(250 BYTE), 
  "FILLER_22" VARCHAR2(250 BYTE), 
  "FILLER_23" VARCHAR2(250 BYTE), 
  "FILLER_24" VARCHAR2(250 BYTE), 
  "FILLER_25" VARCHAR2(250 BYTE), 
  "RB_ROWID" NUMBER, 
  "MONTH_END_DATE" DATE, 
  "REPORTING_ENTITY" VARCHAR2(6 BYTE), 
  "PROVENIENZA" VARCHAR2(30 BYTE), 
  "USERUPD" VARCHAR2(30 BYTE), 
  "DATEUPD" DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_DEPOSITS_01
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_DEPOSITS_01
ON RB_HST_DEPOSITS_01 (
  MONTH_END_DATE,
  REPORTING_ENTITY,
  RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_DEPOSITS_01_GLKC ON RB_HST_DEPOSITS_01 (GL_KEY_CODE, BUSINESS_UNIT) INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;
CREATE INDEX IX_RB_HST_DEPOSITS_01_CC ON RB_HST_DEPOSITS_01 (CALL_CODE, BUSINESS_UNIT) INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;
--------------------------------------------------------
--  Constraints for Table RB_HST_DEPOSITS_01
--------------------------------------------------------

ALTER TABLE RB_HST_DEPOSITS_01 ADD CONSTRAINT PK_RB_HST_DEPOSITS_01
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_DEPOSITS_01 ENABLE VALIDATE;