--------------------------------------------------------
--  DDL - DROP for Table RB_HST_OREO_01
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_OREO_01"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;

  /
--------------------------------------------------------
--  DDL for Table RB_HST_OREO_01
--------------------------------------------------------

CREATE TABLE "RB_HST_OREO_01" (
"INTERCOMPANY" VARCHAR2(15),
"CONSOL_NODE" VARCHAR2(20),
"BUSINESS_UNIT" VARCHAR2(5),
"GL_KEY_CODE" VARCHAR2(15),
"GL_KEY_CODE_DESC" VARCHAR2(150),
"CALL_CODE" VARCHAR2(15),
"CALL_CODE_DESC" VARCHAR2(150),
"LOAN_NUMBER" VARCHAR2(15),
"INSTRUMENT_ID" VARCHAR2(27),
"CONVERTED_INSTRUMENT_ID" VARCHAR2(27),
"CALL_CODE_LOOKUP" VARCHAR2(5),
"CURRENT_OREO_ASSET_NUMBER" VARCHAR2(250),
"ENTITY_CHANGE" VARCHAR2(3),
"DUPLICATE_LOAN_ON_ONE_PROPERTY" VARCHAR2(3),
"FORECLOSURE_INDICATOR_DESCRPTN" VARCHAR2(250),
"OREO_NEW_OREO_EVENT" VARCHAR2(3),
"OREO_COST_CENTER" VARCHAR2(15),
"OREO_INDICATOR" VARCHAR2(3),
"OREO_NET_LIDQUIDATION_PROCEEDS" NUMBER(23,3),
"OREO_NET_LIDQUIDATION_AMT" NUMBER(23,3),
"OREO_SALE_DATE" DATE,
"OREO_OFFSET_TO_CHARGE_OFF" NUMBER(23,3),
"OREO_OPER_EXP_CLOSING_STMT" NUMBER(23,3),
"OREO_VALUATION_ADJUSTMENT" NUMBER(23,3),
"OREO_FINAL_SALE" NUMBER(23,3),
"OREO_EVENT_DATE" DATE,
"OREO_APPRAISAL_VALUE" NUMBER(23,3),
"OREO_APPRAISAL_DATE" DATE,
"OREO_CURRENT_BAL_ACCUMULATOR" NUMBER(23,3),
"OREO_LOSS_ON_SALE" NUMBER(23,3),
"OREO_PROJCTED_LIQUIDATION_DATE" DATE,
"OREO_LOAN_PRIN_BAL_PRPTY_REV" NUMBER(23,3),
"OREO_BEG_BAL_AT_CURRENT_YEAR" NUMBER(23,3),
"OREO_NOTES" VARCHAR2(250),
"OREO_COMPANY" VARCHAR2(5),
"FORECLOSURE_START_DATE" DATE,
"FORECLOSURE_SALE_DATE" DATE,
"LOSS_SHARE_VALUE" NUMBER(23,3),
"MATURITY_DATE" DATE,
"MATURITY_BUCKETS" VARCHAR2(20),
"LOSS_SHARING_AGREEMENT_YN" VARCHAR2(3),
"SPV_YN" VARCHAR2(3),
"ABCP_CONDUITS_YN" VARCHAR2(3),
"VIE_YN" VARCHAR2(3),
"REGULATORY_RISK_RATINGS" NUMBER(3,3),
"LEVEL_FAIR_VALUE" VARCHAR2(10),
"ACCOUNT" VARCHAR2(10),
"PRODUCT" VARCHAR2(6),
"OPERATING_UNIT" VARCHAR2(8),
"AFFILIATE" VARCHAR2(5),
"CUST_CLASS" VARCHAR2(10),
"UMD1" VARCHAR2(250),
"UMD2" VARCHAR2(250),
"UMD3" VARCHAR2(250),
"UMD4" VARCHAR2(250),
"UMD5" VARCHAR2(250),
"FILLER_1" VARCHAR2(250),
"FILLER_2" VARCHAR2(250),
"FILLER_3" VARCHAR2(250),
"FILLER_4" VARCHAR2(250),
"FILLER_5" VARCHAR2(250),
"FILLER_6" VARCHAR2(250),
"FILLER_7" VARCHAR2(250),
"FILLER_8" VARCHAR2(250),
"FILLER_9" VARCHAR2(250),
"FILLER_10" VARCHAR2(250),
"FILLER_11" VARCHAR2(250),
"FILLER_12" VARCHAR2(250),
"FILLER_13" VARCHAR2(250),
"FILLER_14" VARCHAR2(250),
"FILLER_15" VARCHAR2(250),
"FILLER_16" VARCHAR2(250),
"FILLER_17" VARCHAR2(250),
"FILLER_18" VARCHAR2(250),
"FILLER_19" VARCHAR2(250),
"FILLER_20" VARCHAR2(250),
"FILLER_21" VARCHAR2(250),
"FILLER_22" VARCHAR2(250),
"FILLER_23" VARCHAR2(250),
"FILLER_24" VARCHAR2(250),
"FILLER_25" VARCHAR2(250),
"RB_ROWID" NUMBER,
"MONTH_END_DATE" DATE,
"REPORTING_ENTITY" VARCHAR2(6),
"PROVENIENZA" VARCHAR2(30 BYTE), 
"USERUPD" VARCHAR2(30 BYTE), 
"DATEUPD" DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_OREO_01
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_OREO_01
ON RB_HST_OREO_01 (
MONTH_END_DATE,
REPORTING_ENTITY,
RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_OREO_01_RE
ON RB_HST_OREO_01 (REPORTING_ENTITY)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;
CREATE INDEX IX_RB_HST_OREO_01_GLKC ON RB_HST_OREO_01 (GL_KEY_CODE, BUSINESS_UNIT) INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;
CREATE INDEX IX_RB_HST_OREO_01_CC ON RB_HST_OREO_01 (CALL_CODE, BUSINESS_UNIT) INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;
--------------------------------------------------------
--  Constraints for Table RB_HST_OREO_01
--------------------------------------------------------

ALTER TABLE RB_HST_OREO_01 ADD CONSTRAINT PK_RB_HST_OREO_01
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_OREO_01 ENABLE VALIDATE;