--------------------------------------------------------
--  DDL - DROP for Table RB_HST_DEPOSITS_02
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_DEPOSITS_02"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;

  /
--------------------------------------------------------
--  DDL for Table RB_HST_DEPOSITS_02
--------------------------------------------------------

CREATE TABLE "RB_HST_DEPOSITS_02" (
  "BANK_NUMBER" VARCHAR2(6 BYTE), 
  "ACCOUNT_DEPOSIT_CATEGORY_CODE" VARCHAR2(3 BYTE), 
  "ACCOUNT_TYPE_CODE" VARCHAR2(3 BYTE), 
  "ACCOUNT_RETIREMENT_PLAN_TYPE" VARCHAR2(3 BYTE), 
  "OPERATING_UNIT" VARCHAR2(10 BYTE), 
  "BRANCH_NUMBER" VARCHAR2(10 BYTE), 
  "ACCT_INST_OPEN_DATE" DATE, 
  "ACCT_LAST_INT_DATE" DATE, 
  "ACCT_INST_CLOSED_DATE" DATE, 
  "MATURITY_DATE" DATE, 
  "CURRENCY_CODE" VARCHAR2(3 BYTE), 
  "ORIGINATION_DATE" DATE, 
  "BROKERED_DEPOSITS" VARCHAR2(10 BYTE), 
  "TRANSACTION_NON_TRANSACTION_YN" VARCHAR2(3 BYTE), 
  "INTEREST_BEARING_YN" VARCHAR2(3 BYTE), 
  "CURRENCY_USQ" VARCHAR2(3 BYTE), 
  "FED_FUNDS_YN" VARCHAR2(3 BYTE), 
  "CUSTOMER_ID" VARCHAR2(10 BYTE), 
  "FOREIGN_DOMESTIC" VARCHAR2(8 BYTE), 
  "COUNTRY_CODE" VARCHAR2(5 BYTE), 
  "SOURCE" VARCHAR2(4 BYTE), 
  "IBF_DEPOSIT_COLUMN_YN" VARCHAR2(3 BYTE), 
  "CUST_CLASS" VARCHAR2(10 BYTE), 
  "AFFILIATE" VARCHAR2(10 BYTE), 
  "X_1" VARCHAR2(255 BYTE), 
  "X_2" VARCHAR2(255 BYTE), 
  "X_3" VARCHAR2(255 BYTE), 
  "X_4" VARCHAR2(255 BYTE), 
  "X_5" VARCHAR2(255 BYTE), 
  "X_6" VARCHAR2(255 BYTE), 
  "X_7" VARCHAR2(255 BYTE), 
  "X_8" VARCHAR2(255 BYTE), 
  "X_9" VARCHAR2(255 BYTE), 
  "X_10" VARCHAR2(255 BYTE), 
  "X_11" VARCHAR2(255 BYTE), 
  "X_12" VARCHAR2(255 BYTE), 
  "X_13" VARCHAR2(255 BYTE), 
  "X_14" VARCHAR2(255 BYTE), 
  "X_15" VARCHAR2(255 BYTE), 
  "X_16" VARCHAR2(255 BYTE), 
  "X_17" VARCHAR2(255 BYTE), 
  "X_18" VARCHAR2(255 BYTE), 
  "X_19" VARCHAR2(255 BYTE), 
  "X_20" VARCHAR2(255 BYTE), 
  "X_21" VARCHAR2(255 BYTE), 
  "X_22" VARCHAR2(255 BYTE), 
  "X_23" VARCHAR2(255 BYTE), 
  "X_24" VARCHAR2(255 BYTE), 
  "X_25" VARCHAR2(255 BYTE), 
  "X_26" VARCHAR2(255 BYTE), 
  "X_27" VARCHAR2(255 BYTE), 
  "X_28" VARCHAR2(255 BYTE), 
  "X_29" VARCHAR2(255 BYTE), 
  "X_30" VARCHAR2(255 BYTE), 
  "X_31" VARCHAR2(255 BYTE), 
  "X_32" VARCHAR2(255 BYTE), 
  "X_33" VARCHAR2(255 BYTE), 
  "X_34" VARCHAR2(255 BYTE), 
  "X_35" VARCHAR2(255 BYTE), 
  "X_36" VARCHAR2(255 BYTE), 
  "X_37" VARCHAR2(255 BYTE), 
  "X_38" VARCHAR2(255 BYTE), 
  "X_39" VARCHAR2(255 BYTE), 
  "RB_ROWID" NUMBER, 
  "MONTH_END_DATE" DATE, 
  "REPORTING_ENTITY" VARCHAR2(6 BYTE), 
  "PROVENIENZA" VARCHAR2(30 BYTE), 
  "USERUPD" VARCHAR2(30 BYTE), 
  "DATEUPD" DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_DEPOSITS_02
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_DEPOSITS_02
ON RB_HST_DEPOSITS_02 (
  MONTH_END_DATE,
  REPORTING_ENTITY,
  RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_HST_DEPOSITS_02
--------------------------------------------------------

ALTER TABLE RB_HST_DEPOSITS_02 ADD CONSTRAINT PK_RB_HST_DEPOSITS_02
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_DEPOSITS_02 ENABLE VALIDATE;