--------------------------------------------------------
--  DDL - DROP for Table RB_HST_OFF_BS_01
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_OFF_BS_01"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
  
--------------------------------------------------------
--  DDL for Table RB_HST_OFF_BS_01
--------------------------------------------------------

CREATE TABLE "RB_HST_OFF_BS_01" (
	TGK_TABLE_SEGMENT VARCHAR(2),
	RB_ROWID NUMBER(38,0),
	MONTH_END_DATE DATE,
	REPORTING_ENTITY VARCHAR2(6),
	INSTRUMENT VARCHAR2(27),
	CALL_CODE VARCHAR2(15),
	CALL_CODE_DESC VARCHAR2(150),
	GL_KEY_CODE VARCHAR2(15),
	GL_KEY_CODE_DESC VARCHAR2(150),
	CONSOL_NODE VARCHAR2(20),
	BUSINESS_UNIT VARCHAR2(5),
	CURRENCY_CODE VARCHAR2(3),
	FOREIGN_AMOUNT NUMBER(23,3),
	CURRENCY_USQ VARCHAR2(3),
	BASE_EQUIVALENT NUMBER(23,3),
	ORIGINATION_DATE DATE,
	MATURITY_DATE DATE,
	REMAINING_MATURITY_DAYS NUMBER(23,0),
	FRONTED_UNFUNDED_PARTICIPANTS NUMBER(23,3),
	CUSTOMER_ID VARCHAR2(10),
	CUSTOMER_NAME VARCHAR2(50),
	"DEPO_NON-DEPO" VARCHAR2(25),
	FOREIGN_DOMESTIC VARCHAR2(8),
	CANCELLABLE_Y_N VARCHAR2(50),
	MATURITY_BUCKETS VARCHAR2(50),
	SECURITIZATION_EXPO NUMBER(23,3),
	CREDIT_CONVERSION_FACTOR NUMBER(23,3),
	CREDIT_EQUIVALENT_AMT NUMBER(23,3),
	RISK_COUNTRY VARCHAR2(50),
	RISK_COUNTRY_CODE VARCHAR2(10),
	RISK_WEIGHTED_CATEGORY NUMBER(23,3),
	RISK_WEIGHTED_ALLOCATION NUMBER(23,3),
	UMD_1 NUMBER(23,3),
	UMD_2 NUMBER(23,3),
	UMD_3 NUMBER(23,3),
	SECURED_Y_N VARCHAR2(25),
	GUARANTEED_Y_N VARCHAR2(25),
	GOVT_GUARANTEED_PERCENTAGE  NUMBER(23,3),
	QUALIFIED_CENTRAL_CPT_Y_N VARCHAR2(25),
	ABCP_CONDUITS_AMT NUMBER(28,3),
	SOVERIGN_DEFAULT_Y_N VARCHAR2(25),
	CRC_RATING_OF_OECD_EXPOSURES NUMBER(28,3),
	US_GAAP_RISK_RATING VARCHAR2(20),
	IFRS_RISK_RATING VARCHAR2(20),
	FACILITY_LIMIT_AMOUNT NUMBER(23,3),
	FACILITY_USED_AMOUNT NUMBER(23,3),
	SYNDICATED_RABOSHARE NUMBER(23,3),
	"SYNDICATED_RABOSHARE_%" NUMBER(23,3),
	SYNDICATED_PARTICIPANTS NUMBER(23,3),
	"SYNDICATED_PARTICIPANTS_%" NUMBER(23,3),
	SOURCE VARCHAR2(4),
	UMD_4 VARCHAR2(250),
	UMD_5 VARCHAR2(250),
	UMD_6 VARCHAR2(250),
	TRADE_ID VARCHAR2(20),
	REPORTABLE_Y_N VARCHAR2(20),
	BU  VARCHAR2(10),
	ACCOUNT VARCHAR2(10),
	PRODUCT VARCHAR2(6),
	OPERATING_UNIT VARCHAR2(8),
	DEPTID VARCHAR2(15),
	CUST_CLASS VARCHAR2(10),
	AFFILIATE VARCHAR2(5),
	CIF_TYPE VARCHAR2(20),
	CUSTOMER_TYPE VARCHAR2(30),
	LOAN_CALL_CODE VARCHAR2(50),
	PRODUCT_GROUP VARCHAR2(50),
	FACILITY_TYPE VARCHAR2(30),
	FACILITY_TYPE_DESC VARCHAR2(100),
	CALL_CODE_CODEBLOCK VARCHAR2(100),
	CCF_CODEBLOCK VARCHAR2(100),
	FILLER_1 VARCHAR2(250),
	FILLER_2 VARCHAR2(250),
	FILLER_3 VARCHAR2(250),
	FILLER_4 VARCHAR2(250),
	FILLER_5 VARCHAR2(250),
	FILLER_6 VARCHAR2(250),
	FILLER_7 VARCHAR2(250),
	FILLER_8 VARCHAR2(250),
	FILLER_9 VARCHAR2(250),
	FILLER_10 VARCHAR2(250),
	FILLER_11 VARCHAR2(250),
	FILLER_12 VARCHAR2(250),
	FILLER_13 VARCHAR2(250),
	FILLER_14 VARCHAR2(250),
	FILLER_15 VARCHAR2(250),
	FILLER_16 VARCHAR2(250),
	FILLER_17 VARCHAR2(250),
	FILLER_18 VARCHAR2(250),
	FILLER_19 VARCHAR2(250),
	FILLER_20 VARCHAR2(250),
	FILLER_21 VARCHAR2(250),
	FILLER_22 VARCHAR2(250),
	FILLER_23 VARCHAR2(250),
	FILLER_24 VARCHAR2(250),
	FILLER_25 VARCHAR2(250),
	PROVENIENZA VARCHAR2(30),
	USERUPD VARCHAR2(30 BYTE),
	DATEUPD DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_OFF_BS_01
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_OFF_BS_01
ON RB_HST_OFF_BS_01 (
	MONTH_END_DATE,
	REPORTING_ENTITY,
	RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_OFF_BS_01_RE
ON RB_HST_OFF_BS_01 (REPORTING_ENTITY)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_OFF_BS_01_GLKC
ON RB_HST_OFF_BS_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_OFF_BS_01_CC
ON RB_HST_OFF_BS_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_HST_OFF_BS_01
--------------------------------------------------------

ALTER TABLE RB_HST_OFF_BS_01 ADD CONSTRAINT PK_RB_HST_OFF_BS_01
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_OFF_BS_01 ENABLE VALIDATE;