--------------------------------------------------------
--  DDL - DROP for Table RB_HST_DERIVATIVES_02
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_DERIVATIVES_02"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
  
--------------------------------------------------------
--  DDL for Table RB_HST_DERIVATIVES_02
--------------------------------------------------------

CREATE TABLE "RB_HST_DERIVATIVES_02" (
	RB_ROWID NUMBER,
	MONTH_END_DATE DATE,
	REPORTING_ENTITY VARCHAR2(6),
	MANUAL_ADJUSTMENTS NUMBER(23,3),
	FILLER_20 VARCHAR2(250),
	FILLER_21 VARCHAR2(250),
	FILLER_22 VARCHAR2(250),
	FILLER_23 VARCHAR2(250),
	FILLER_24 VARCHAR2(250),
	FILLER_25 VARCHAR2(250),
	PROVENIENZA VARCHAR2(30),
	USERUPD VARCHAR2(30 BYTE),
	DATEUPD DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_DERIVATIVES_02
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_DERIVATIVES_02
ON RB_HST_DERIVATIVES_02 (
	MONTH_END_DATE,
	REPORTING_ENTITY,
	RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_DERIVATIVES_02_RE
ON RB_HST_DERIVATIVES_02 (REPORTING_ENTITY)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_HST_DERIVATIVES_02
--------------------------------------------------------

ALTER TABLE RB_HST_DERIVATIVES_02 ADD CONSTRAINT PK_RB_HST_DERIVATIVES_02
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_DERIVATIVES_02 ENABLE VALIDATE;