--------------------------------------------------------
--  DDL - DROP for Table RB_HST_LOAN_01
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_LOAN_01"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
  
--------------------------------------------------------
--  DDL for Table RB_HST_LOAN_01
--------------------------------------------------------

CREATE TABLE "RB_HST_LOAN_01" (
	"RB_ROWID" NUMBER(*,0), 
    "MONTH_END_DATE" DATE, 
    "REPORTING_ENTITY" VARCHAR2(6 BYTE), 
    "INSTRUMENT" VARCHAR2(27 BYTE), 
    "INTERCOMPANY" VARCHAR2(15 BYTE), 
    "CALL_CODE" VARCHAR2(15 BYTE), 
    "CALL_CODE_DESC" VARCHAR2(50 BYTE), 
    "BASE_EQUIVALENT" NUMBER(23,3), 
    "PROD_GROUP_DESC" VARCHAR2(100 BYTE), 
    "PROD_GROUP_TYPE_DESC" VARCHAR2(100 BYTE), 
    "CUSTOMER_ID" VARCHAR2(10 BYTE), 
    "CUSTOMER_NAME" VARCHAR2(50 BYTE), 
    "CUSTOMER_TYPE" VARCHAR2(30 BYTE), 
    "RELATED_DEP_INST_YESNO" VARCHAR2(5 BYTE), 
    "PURPOSE_CODE" VARCHAR2(50 BYTE), 
    "FOREIGN_DOMESTIC" VARCHAR2(8 BYTE), 
    "CUST_PARENT_FOREIGN_DOMESTIC" VARCHAR2(15 BYTE), 
    "COUNTRY_CODE" VARCHAR2(5 BYTE), 
    "COUNTRY_DESC" VARCHAR2(30 BYTE), 
    "RISK_COUNTRY" VARCHAR2(50 BYTE), 
    "OPERATING_STATE" VARCHAR2(10 BYTE), 
    "LOAN_USED_IN_STATE" VARCHAR2(10 BYTE), 
    "BORROWER_COUNTY" VARCHAR2(50 BYTE), 
    "LOAN_USED_IN_COUNTY" VARCHAR2(50 BYTE), 
    "AFFL_CONSOL_NODE" VARCHAR2(30 BYTE), 
    "DAY_COUNT_BASIS" VARCHAR2(30 BYTE), 
    "SOURCE" VARCHAR2(4 BYTE), 
    "HIGHLVL_PROD_CAT" VARCHAR2(10 BYTE), 
    "GL_KEY_CODE" VARCHAR2(15 BYTE), 
    "GL_KEY_CODE_DESC" VARCHAR2(50 BYTE), 
    "PRINCIPAL_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "ACC_INT_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "DEF_FEES_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "UNEARN_FEES_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "SPCFC_RESRV_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "INT_INC_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "FEES_GL_US_GAAP_BASE_EQ" NUMBER(23,3), 
    "PRINCIPAL_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "ACC_INT_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "DEFERRED_FEES_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "UNEARNED_FEES_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "SPCFC_RESRV_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "INT_INC_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "FEES_GL_IFRS_BASE_EQ" NUMBER(23,3), 
    "UMD1" NUMBER(23,3), 
    "UMD2" NUMBER(23,3), 
    "UMD3" NUMBER(23,3), 
    "CONSOL_NODE" VARCHAR2(20 BYTE), 
    "SUB_LE1" VARCHAR2(20 BYTE), 
    "SUB_LE2" VARCHAR2(20 BYTE), 
    "BUSINESS_UNIT" VARCHAR2(5 BYTE), 
    "BUSINESS_LINE" VARCHAR2(20 BYTE), 
    "CURRENCY_CODE" VARCHAR2(3 BYTE), 
    "LEGAL_CUST_TOTAL_COMMIT" NUMBER(23,3), 
    "LEGAL_CUST_PRINC_FUNDED" NUMBER(23,3), 
    "LEGAL_CUST_UNFUNDED_COMMIT" NUMBER(23,3), 
    "LEGAL_CUST_INT_OWED" NUMBER(23,3), 
    "BANK_SHARE_PRINC_IFRS" NUMBER(23,3), 
    "BANK_SHARE_PRINC_US_GAAP" NUMBER(23,3), 
    "BANK_SHARE_TOTAL_COMMIT" NUMBER(23,3), 
    "BANK_SHARE_UNFUNDED_COMMIT" NUMBER(23,3), 
    "BANK_SPECIFIC_RESRV_US_GAAP" NUMBER(23,3), 
    "UNEARNED_FEES_US_GAAP" NUMBER(23,3), 
    "CHARGED_OFF_US_GAAP" NUMBER(23,3), 
    "CHARGED_OFF_IFRS" NUMBER(23,3), 
    "SPECIFIC_RESRV_IFRS" NUMBER(23,3), 
    "NON_ACC_INTEREST_DIFF_US_GAAP" NUMBER(23,3), 
    "INTEREST_APPLIED_PRINC_US_GAAP" NUMBER(23,3), 
    "NON_ACC_INTEREST_DIFF_IFRS" NUMBER(23,3), 
    "INTEREST_APPLLIED_PRINC_IFRS" NUMBER(23,3), 
    "UNEARNED_FEE_IFRS" NUMBER(23,3), 
    "LEDGER_ACCRUED_INTEREST_IFRS" NUMBER(23,3), 
    "LEDG_ACC_INTEREST_US_GAAP" NUMBER(23,3), 
    "INTEREST_PL_MTD_IFRS" NUMBER(23,3), 
    "INTEREST_PL_MTD_US_GAAP" NUMBER(23,3), 
    "INTEREST_PL_QTD_IFRS" NUMBER(23,3), 
    "INTEREST_PL_QTD_US_GAAP" NUMBER(23,3), 
    "INTEREST_PL_YTD_IFRS" NUMBER(23,3), 
    "INTEREST_PL_YTD_US_GAAP" NUMBER(23,3), 
    "ORIGINAL_PREMIUM_DISCOUNT" NUMBER(23,3), 
    "REMAINING_PREMIUM_DISCOUNT" NUMBER(23,3), 
    "ORIGINATION_DATE" DATE, 
    "MATURITY_DATE" DATE, 
    "ORIGINAL_INTEREST_RATE" NUMBER(23,3), 
    "REVOLVER_YN" VARCHAR2(5 BYTE), 
    "RATE_EFFECTIVE_DATE" DATE, 
    "RATE_EXPIRATION_DATE" DATE, 
    "INTEREST_RATE" NUMBER(23,3), 
    "OVER_UNDER_RATE_INDEX" VARCHAR2(10 BYTE), 
    "NOTE_CEILING_RATE" NUMBER(23,3), 
    "NOTE_FLOOR_RATE" NUMBER(23,3), 
    "NEXT_RATE_RESET_DATE" DATE, 
    "LAST_RATE_RESET_DATE" DATE, 
    "RATE_RESET_FREQUENCY" VARCHAR2(20 BYTE), 
    "LAST_REPRICING_DATE" DATE, 
    "RB_INDEX" VARCHAR2(20 BYTE), 
    "FIXED_OR_VARIABLE" VARCHAR2(20 BYTE), 
    "BOOK_INDICATOR_HTM_OR_AFS" VARCHAR2(10 BYTE), 
    "IF_AFS_THEN_FV_BALANCE" NUMBER(23,3), 
    "CUSTOMER_PARENT" VARCHAR2(20 BYTE), 
    "AMORTIZATION_METHOD" VARCHAR2(20 BYTE), 
    "COF_FTP_RATE" NUMBER(23,3), 
    "SPREAD" NUMBER(23,3), 
    "FED_CALL_CODE" VARCHAR2(20 BYTE), 
    "ZIP_CODE" VARCHAR2(10 BYTE), 
    "REAL_ESTATE_ZIP_CODE" VARCHAR2(10 BYTE), 
    "PCT_OWNED" NUMBER(23,3), 
    "MATURITY_REPORTING" VARCHAR2(50 BYTE), 
    "MATURITY_BUCKETS" VARCHAR2(50 BYTE), 
    "PAST_DUE_YN" VARCHAR2(10 BYTE),
    "PROVENIENZA" VARCHAR2(30 BYTE), 
    "USERUPD" VARCHAR2(30 BYTE), 
    "DATEUPD" DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_LOAN_01
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_LOAN_01
ON RB_HST_LOAN_01 (
	MONTH_END_DATE,
	REPORTING_ENTITY,
	RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_LOAN_01_RE
ON RB_HST_LOAN_01 (REPORTING_ENTITY)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_LOAN_01_GLKC
ON RB_HST_LOAN_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_LOAN_01_CC
ON RB_HST_LOAN_01 (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_HST_LOAN_01
--------------------------------------------------------

ALTER TABLE RB_HST_LOAN_01 ADD CONSTRAINT PK_RB_HST_LOAN_01
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_LOAN_01 ENABLE VALIDATE;