--------------------------------------------------------
--  DDL - DROP for Table RB_HST_SECURITY
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_SECURITY"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
  
--------------------------------------------------------
--  DDL for Table RB_HST_SECURITY
--------------------------------------------------------
SET DEFINE OFF;
CREATE TABLE "RB_HST_SECURITY" (
	RB_ROWID INT,
	MONTH_END_DATE DATE,
	REPORTING_ENTITY VARCHAR2(6),
	INSTRUMENT VARCHAR2(27),
	INTERCOMPANY VARCHAR2(15),
	CONSOL_NODE VARCHAR2(20),
	BUSINESS_UNIT VARCHAR2(5),
	GL_KEY_CODE VARCHAR2(15),
	GL_KEY_CODE_DESC VARCHAR2(150),
	CALL_CODE VARCHAR2(15),
	CALL_CODE_DESC VARCHAR2(150),
	PRODUCT_GROUP_DESC VARCHAR2(100),
	AMORTIZED_COST NUMBER(23,3),
	FAIR_VALUE NUMBER(23,3),
	PRICE VARCHAR2(20),
	PRINCIPAL_GL_US_GAAP_BASE_EQ NUMBER(23,3),
	DISCOUNT_GL_US_GAAP_BASE_EQ NUMBER(23,3),
	PREMIUM_GL_US_GAAP_BASE_EQ NUMBER(23,3),
	UNRLZED_PL_GL_US_GAAP_BASE_EQ NUMBER(23,3),
	LTD_IMPAIRMENT_US_GAAP_BASE_EQ NUMBER(23,3),
	SOURCE VARCHAR2(4),
	IBF_ONLY_RAL_COLUMN_B_YN VARCHAR2(5),
	CURRENCY_CODE VARCHAR2(3),
	REGULATORY_RISK_RATINGS NUMBER(2,1),
	LEVEL_FAIR_VALUE VARCHAR2(10),
	ORIGINAL_PRICE VARCHAR2(20),
	MATURITY_DATE DATE,
	REMAINING_MATURITY VARCHAR2(6),
	INT_RATE NUMBER(12,8),
	FIXED_OR_VARIABLE VARCHAR2(20),
	FLOATING_RATE NUMBER(15,8),
	FIXED_RATE NUMBER(15,8),
	INDEX_RATE_ADD NUMBER(8,4),
	FLOAT_FREQ VARCHAR2(12),
	MATURITY_BUCKETS VARCHAR2(50),
	LAST_RATE_RESET_DATE DATE,
	NEXT_RATE_RESET_DATE DATE,
	DAY_COUNT_BASIS VARCHAR2(30),
	PLEDGED_SECURITIES_YN VARCHAR2(5),
	CMMP_TO_PURCHASE_SEC_YN VARCHAR2(5),
	GUARANTOR VARCHAR2(20),
	CUSTOMER_NAME VARCHAR2(50),
	CUSTOMER_TYPE VARCHAR2(30),
	CITY VARCHAR2(30),
	OPERATING_STATE VARCHAR2(10),
	COUNTRY_CODE VARCHAR2(5),
	COUNTRY_DESC VARCHAR2(30),
	FOREIGN_DOMESTIC VARCHAR2(8),
	SECURITY_DESCRIPTION VARCHAR2(150),
	"S&P_RATING" VARCHAR2(4),
	MOODYS_RATING VARCHAR2(4),
	CUSIP VARCHAR2(10),
	ISIN VARCHAR2(12),
	TRADE_ID VARCHAR2(20),
	CUSTOMER_ID VARCHAR2(10),
	RELATED_DEP_INST VARCHAR2(20),
	BRANCH_SUBSIDIARY VARCHAR2(12),
	VAL_DATE DATE,
	TRADE_DATE DATE,
	SETTLE_DATE DATE,
	LAST_PRIN_PMT DATE,
	UMD1 VARCHAR2(250),
	UMD2 VARCHAR2(250),
	UMD3 VARCHAR2(250),
	UMD4 VARCHAR2(250),
	UMD5 VARCHAR2(250),
	UMD6 VARCHAR2(250),
	UMD7 VARCHAR2(250),
	UMD8 VARCHAR2(250),
	UMD9 VARCHAR2(250),
	UMD10 VARCHAR2(250),
	SYMB_POOL VARCHAR2(12),
	PORTFOLIO VARCHAR2(20),
	ACCOUNT_CAMRA VARCHAR2(10),
	PRODUCT_CAMRA VARCHAR2(10),
	ACCOUNT VARCHAR2(10),
	PRODUCT VARCHAR2(6),
	OPERATING_UNIT VARCHAR2(8),
	AFFILIATE VARCHAR2(5),
	CUST_CLASS VARCHAR2(10),
	DISCOUNT_CODEBLOCK VARCHAR2(250),
	PREMIUM_CODEBLOCK VARCHAR2(250),
	UNRLZED_CODEBLOCK VARCHAR2(250),
	LTD_IMPAIRMENT_CODEBLOCK VARCHAR2(250),
	FILLER_1 VARCHAR2(250),
	FILLER_2 VARCHAR2(250),
	FILLER_3 VARCHAR2(250),
	FILLER_4 VARCHAR2(250),
	FILLER_5 VARCHAR2(250),
	FILLER_6 VARCHAR2(250),
	FILLER_7 VARCHAR2(250),
	FILLER_8 VARCHAR2(250),
	FILLER_9 VARCHAR2(250),
	FILLER_10 VARCHAR2(250),
	FILLER_11 VARCHAR2(250),
	FILLER_12 VARCHAR2(250),
	FILLER_13 VARCHAR2(250),
	FILLER_14 VARCHAR2(250),
	FILLER_15 VARCHAR2(250),
	FILLER_16 VARCHAR2(250),
	FILLER_17 VARCHAR2(250),
	FILLER_18 VARCHAR2(250),
	FILLER_19 VARCHAR2(250),
	FILLER_20 VARCHAR2(250),
	FILLER_21 VARCHAR2(250),
	FILLER_22 VARCHAR2(250),
	FILLER_23 VARCHAR2(250),
	FILLER_24 VARCHAR2(250),
	FILLER_25 VARCHAR2(250),
	PROVENIENZA VARCHAR2(30),
	USERUPD VARCHAR2(30 BYTE),
	DATEUPD DATE
)
PARTITION BY HASH (MONTH_END_DATE)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_SECURITY
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_SECURITY
ON RB_HST_SECURITY (
	MONTH_END_DATE,
	REPORTING_ENTITY,
	RB_ROWID
)
GLOBAL PARTITION BY HASH (MONTH_END_DATE)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_SECURITY_RE
ON RB_HST_SECURITY (REPORTING_ENTITY)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_SECURITY_GLKC
ON RB_HST_SECURITY (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_SECURITY_CC
ON RB_HST_SECURITY (CALL_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_HST_SECURITY
--------------------------------------------------------

ALTER TABLE RB_HST_SECURITY ADD CONSTRAINT PK_RB_HST_SECURITY
PRIMARY KEY (MONTH_END_DATE, REPORTING_ENTITY, RB_ROWID) USING INDEX UI_RB_HST_SECURITY ENABLE VALIDATE;