--------------------------------------------------------
--  DDL - DROP for Table RB_HST_GL_01
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_HST_GL_01"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
  
/
--------------------------------------------------------
--  DDL for Table RB_HST_GL_01
--------------------------------------------------------

CREATE TABLE "RB_HST_GL_01" (
	RB_ROWID INT,
	REPORTING_ENTITY VARCHAR2(6),
	GL_KEY_CODE VARCHAR2(15),
	CONSOL_NODE VARCHAR2(20),
	BUSINESS_UNIT VARCHAR2(5),
	OPERATING_UNIT VARCHAR2(8),
	RB_BALANCE_TYPE VARCHAR2(6),
	SOURCE VARCHAR2(4),
	FISCAL_YEAR NUMBER(4),
	BASE_CURRENCY VARCHAR2(3),
	JAN_BASE NUMBER(26,3),
	FEB_BASE NUMBER(26,3),
	MAR_BASE NUMBER(26,3),
	APR_BASE NUMBER(26,3),
	MAY_BASE NUMBER(26,3),
	JUNE_BASE NUMBER(26,3),
	JULY_BASE NUMBER(26,3),
	AUG_BASE NUMBER(26,3),
	SEP_BASE NUMBER(26,3),
	OCT_BASE NUMBER(26,3),
	NOV_BASE NUMBER(26,3),
	DEC_BASE NUMBER(26,3),
	CURRENCY_CODE VARCHAR2(3),
	JAN_ORIG NUMBER(26,3),
	FEB_ORIG NUMBER(26,3),
	MAR_ORIG NUMBER(26,3),
	APR_ORIG NUMBER(26,3),
	MAY_ORIG NUMBER(26,3),
	JUNE_ORIG NUMBER(26,3),
	JULY_ORIG NUMBER(26,3),
	AUG_ORIG NUMBER(26,3),
	SEP_ORIG NUMBER(26,3),
	OCT_ORIG NUMBER(26,3),
	NOV_ORIG NUMBER(26,3),
	DEC_ORIG NUMBER(26,3),
	ACCOUNT VARCHAR2(10),
	DEPTID VARCHAR2(10),
	PRODUCT VARCHAR2(6),
	CUST_CLASS VARCHAR2(10),
	AFFILIATE VARCHAR2(5),
	OBU_AFFILIATE VARCHAR2(10),
	PROJECT_ID VARCHAR2(15),
  US_COA_ACCOUNT VARCHAR2(30),
	PROVENIENZA VARCHAR2(30),
	USERUPD VARCHAR2(30 BYTE),
	DATEUPD DATE
)
PARTITION BY HASH (FISCAL_YEAR)
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Indexes for Table RB_HST_GL_01
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_HST_GL_01
ON RB_HST_GL_01 (
	FISCAL_YEAR,
	REPORTING_ENTITY,
	BUSINESS_UNIT,
	OPERATING_UNIT,
	RB_BALANCE_TYPE,
	BASE_CURRENCY,
	CURRENCY_CODE,
	ACCOUNT,
	DEPTID,
	PRODUCT,
	CUST_CLASS,
	AFFILIATE,
	OBU_AFFILIATE,
	PROJECT_ID
)
GLOBAL PARTITION BY HASH (FISCAL_YEAR)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_HST_GL_01_GLKC
ON RB_HST_GL_01 (GL_KEY_CODE, BUSINESS_UNIT)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_HST_GL_01
--------------------------------------------------------

ALTER TABLE RB_HST_GL_01 ADD CONSTRAINT PK_RB_HST_GL_01
PRIMARY KEY (FISCAL_YEAR, REPORTING_ENTITY, RB_ROWID) ENABLE VALIDATE;