--------------------------------------------------------
--  DDL - DROP for Table RB_DRILL_INSTRUMENT
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "RB_DRILL_INSTRUMENT"';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
  
--------------------------------------------------------
--  DDL for Table RB_DRILL_INSTRUMENT
--------------------------------------------------------

CREATE TABLE "RB_DRILL_INSTRUMENT" (
  COD_SCENARIO VARCHAR(15),
  COD_PERIODO VARCHAR(2),
  COD_AZIENDA VARCHAR2(30),
  COD_AZI_CTP VARCHAR2(30),
  COD_CONTO VARCHAR2(30),
  COD_DEST1 VARCHAR2(30),
  COD_DEST2 VARCHAR2(30),
  COD_DEST3 VARCHAR2(30),
  COD_DEST4 VARCHAR2(30),
  COD_DEST5 VARCHAR2(30),
  COD_DEST2_CTP VARCHAR2(30),
  COD_CATEGORIA VARCHAR2(15),
  COD_VALUTA VARCHAR2(5),
  COD_VALUTA_ORIGINARIA VARCHAR2(5),
  OID_FORM_DATI VARCHAR2(36),
  PROVENIENZA VARCHAR2(30),
  USERUPD VARCHAR2(30 BYTE),
  DATEUPD DATE
)
PARTITION BY HASH (COD_SCENARIO)
  SUBPARTITION BY LIST (COD_PERIODO)
    SUBPARTITION TEMPLATE(
    SUBPARTITION JAN VALUES('01'),
    SUBPARTITION FEB VALUES('02'),
    SUBPARTITION MAR VALUES('03'),
    SUBPARTITION APR VALUES('04'),
    SUBPARTITION MAY VALUES('05'),
    SUBPARTITION JUN VALUES('06'),
    SUBPARTITION JUL VALUES('07'),
    SUBPARTITION AUG VALUES('08'),
    SUBPARTITION SEP VALUES('09'),
    SUBPARTITION OCT VALUES('10'),
    SUBPARTITION NOV VALUES('11'),
    SUBPARTITION DEC VALUES('12')
    )
  PARTITIONS 12
INITRANS 1 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING
;

--------------------------------------------------------
--  Indexes for Table RB_DRILL_INSTRUMENT
--------------------------------------------------------

CREATE UNIQUE INDEX UI_RB_DRILL_INSTRUMENT
ON RB_DRILL_INSTRUMENT (
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_CATEGORIA,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_AZI_CTP,
  COD_DEST2_CTP,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  OID_FORM_DATI
)
GLOBAL PARTITION BY HASH (COD_SCENARIO)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_DRILL_INSTRUMENT
ON RB_DRILL_INSTRUMENT (
  COD_SCENARIO,
  COD_PERIODO,
  PROVENIENZA,
  COD_CATEGORIA
)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

CREATE INDEX IX_RB_DRILL_INSTRUMENT_OID
ON RB_DRILL_INSTRUMENT (
  OID_FORM_DATI
)
INITRANS 2 MAXTRANS 255 NOCOMPRESS PARALLEL LOGGING;

--------------------------------------------------------
--  Constraints for Table RB_DRILL_INSTRUMENT
--------------------------------------------------------

ALTER TABLE RB_DRILL_INSTRUMENT ADD CONSTRAINT PK_RB_DRILL_INSTRUMENT
PRIMARY KEY (
  COD_SCENARIO,
  COD_PERIODO,
  COD_AZIENDA,
  COD_CONTO,
  COD_CATEGORIA,
  COD_DEST1,
  COD_DEST2,
  COD_DEST3,
  COD_DEST4,
  COD_DEST5,
  COD_AZI_CTP,
  COD_DEST2_CTP,
  COD_VALUTA,
  COD_VALUTA_ORIGINARIA,
  OID_FORM_DATI
) USING INDEX UI_RB_DRILL_INSTRUMENT ENABLE VALIDATE
;