SELECT
	COALESCE(A.INSTRUMENT_ID, P.INSTRUMENT_ID) AS INSTRUMENT_ID,
	COALESCE(A.REPORTING_ENTITY, P.REPORTING_ENTITY) AS REPORTING_ENTITY,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.INTERCOMPANY <> P.INTERCOMPANY
			  OR A.INTERCOMPANY IS NULL AND P.INTERCOMPANY IS NOT NULL
			  OR A.INTERCOMPANY IS NOT NULL AND P.INTERCOMPANY IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS INTERCOMPANY,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CONSOL_NODE <> P.CONSOL_NODE
			  OR A.CONSOL_NODE IS NULL AND P.CONSOL_NODE IS NOT NULL
			  OR A.CONSOL_NODE IS NOT NULL AND P.CONSOL_NODE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CONSOL_NODE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.BUSINESS_UNIT <> P.BUSINESS_UNIT
			  OR A.BUSINESS_UNIT IS NULL AND P.BUSINESS_UNIT IS NOT NULL
			  OR A.BUSINESS_UNIT IS NOT NULL AND P.BUSINESS_UNIT IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS BUSINESS_UNIT,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.GL_KEY_CODE <> P.GL_KEY_CODE
			  OR A.GL_KEY_CODE IS NULL AND P.GL_KEY_CODE IS NOT NULL
			  OR A.GL_KEY_CODE IS NOT NULL AND P.GL_KEY_CODE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS GL_KEY_CODE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.GL_KEY_CODE_DESC <> P.GL_KEY_CODE_DESC
			  OR A.GL_KEY_CODE_DESC IS NULL AND P.GL_KEY_CODE_DESC IS NOT NULL
			  OR A.GL_KEY_CODE_DESC IS NOT NULL AND P.GL_KEY_CODE_DESC IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS GL_KEY_CODE_DESC,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CALL_CODE <> P.CALL_CODE
			  OR A.CALL_CODE IS NULL AND P.CALL_CODE IS NOT NULL
			  OR A.CALL_CODE IS NOT NULL AND P.CALL_CODE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CALL_CODE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CALL_CODE_DESC <> P.CALL_CODE_DESC
			  OR A.CALL_CODE_DESC IS NULL AND P.CALL_CODE_DESC IS NOT NULL
			  OR A.CALL_CODE_DESC IS NOT NULL AND P.CALL_CODE_DESC IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CALL_CODE_DESC,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.LOAN_NUMBER <> P.LOAN_NUMBER
			  OR A.LOAN_NUMBER IS NULL AND P.LOAN_NUMBER IS NOT NULL
			  OR A.LOAN_NUMBER IS NOT NULL AND P.LOAN_NUMBER IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS LOAN_NUMBER,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.INSTRUMENT_ID <> P.INSTRUMENT_ID
			  OR A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
			  OR A.INSTRUMENT_ID IS NOT NULL AND P.INSTRUMENT_ID IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS INSTRUMENT_ID,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CONVERTED_INSTRUMENT_ID <> P.CONVERTED_INSTRUMENT_ID
			  OR A.CONVERTED_INSTRUMENT_ID IS NULL AND P.CONVERTED_INSTRUMENT_ID IS NOT NULL
			  OR A.CONVERTED_INSTRUMENT_ID IS NOT NULL AND P.CONVERTED_INSTRUMENT_ID IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CONVERTED_INSTRUMENT_ID,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CALL_CODE_LOOKUP <> P.CALL_CODE_LOOKUP
			  OR A.CALL_CODE_LOOKUP IS NULL AND P.CALL_CODE_LOOKUP IS NOT NULL
			  OR A.CALL_CODE_LOOKUP IS NOT NULL AND P.CALL_CODE_LOOKUP IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CALL_CODE_LOOKUP,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CURRENT_OREO_ASSET_NUMBER <> P.CURRENT_OREO_ASSET_NUMBER
			  OR A.CURRENT_OREO_ASSET_NUMBER IS NULL AND P.CURRENT_OREO_ASSET_NUMBER IS NOT NULL
			  OR A.CURRENT_OREO_ASSET_NUMBER IS NOT NULL AND P.CURRENT_OREO_ASSET_NUMBER IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CURRENT_OREO_ASSET_NUMBER,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.ENTITY_CHANGE <> P.ENTITY_CHANGE
			  OR A.ENTITY_CHANGE IS NULL AND P.ENTITY_CHANGE IS NOT NULL
			  OR A.ENTITY_CHANGE IS NOT NULL AND P.ENTITY_CHANGE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS ENTITY_CHANGE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.DUPLICATE_LOAN_ON_ONE_PROPERTY <> P.DUPLICATE_LOAN_ON_ONE_PROPERTY
			  OR A.DUPLICATE_LOAN_ON_ONE_PROPERTY IS NULL AND P.DUPLICATE_LOAN_ON_ONE_PROPERTY IS NOT NULL
			  OR A.DUPLICATE_LOAN_ON_ONE_PROPERTY IS NOT NULL AND P.DUPLICATE_LOAN_ON_ONE_PROPERTY IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS DUPLICATE_LOAN_ON_ONE_PROPERTY,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FORECLOSURE_INDICATOR_DESCRPTN <> P.FORECLOSURE_INDICATOR_DESCRPTN
			  OR A.FORECLOSURE_INDICATOR_DESCRPTN IS NULL AND P.FORECLOSURE_INDICATOR_DESCRPTN IS NOT NULL
			  OR A.FORECLOSURE_INDICATOR_DESCRPTN IS NOT NULL AND P.FORECLOSURE_INDICATOR_DESCRPTN IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FORECLOSURE_INDICATOR_DESCRPTN,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_NEW_OREO_EVENT <> P.OREO_NEW_OREO_EVENT
			  OR A.OREO_NEW_OREO_EVENT IS NULL AND P.OREO_NEW_OREO_EVENT IS NOT NULL
			  OR A.OREO_NEW_OREO_EVENT IS NOT NULL AND P.OREO_NEW_OREO_EVENT IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_NEW_OREO_EVENT,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_COST_CENTER <> P.OREO_COST_CENTER
			  OR A.OREO_COST_CENTER IS NULL AND P.OREO_COST_CENTER IS NOT NULL
			  OR A.OREO_COST_CENTER IS NOT NULL AND P.OREO_COST_CENTER IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_COST_CENTER,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_INDICATOR <> P.OREO_INDICATOR
			  OR A.OREO_INDICATOR IS NULL AND P.OREO_INDICATOR IS NOT NULL
			  OR A.OREO_INDICATOR IS NOT NULL AND P.OREO_INDICATOR IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_INDICATOR,
	COALESCE(A.OREO_NET_LIDQUIDATION_PROCEEDS,0) - COALESCE(P.OREO_NET_LIDQUIDATION_PROCEEDS, 0) AS OREO_NET_LIDQUIDATION_PROCEEDS,
	COALESCE(A.OREO_NET_LIDQUIDATION_AMT,0) - COALESCE(P.OREO_NET_LIDQUIDATION_AMT, 0) AS OREO_NET_LIDQUIDATION_AMT,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_SALE_DATE <> P.OREO_SALE_DATE
			  OR A.OREO_SALE_DATE IS NULL AND P.OREO_SALE_DATE IS NOT NULL
			  OR A.OREO_SALE_DATE IS NOT NULL AND P.OREO_SALE_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_SALE_DATE,
	COALESCE(A.OREO_OFFSET_TO_CHARGE_OFF,0) - COALESCE(P.OREO_OFFSET_TO_CHARGE_OFF, 0) AS OREO_OFFSET_TO_CHARGE_OFF,
	COALESCE(A.OREO_OPER_EXP_CLOSING_STMT,0) - COALESCE(P.OREO_OPER_EXP_CLOSING_STMT, 0) AS OREO_OPER_EXP_CLOSING_STMT,
	COALESCE(A.OREO_VALUATION_ADJUSTMENT,0) - COALESCE(P.OREO_VALUATION_ADJUSTMENT, 0) AS OREO_VALUATION_ADJUSTMENT,
	COALESCE(A.OREO_FINAL_SALE,0) - COALESCE(P.OREO_FINAL_SALE, 0) AS OREO_FINAL_SALE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_EVENT_DATE <> P.OREO_EVENT_DATE
			  OR A.OREO_EVENT_DATE IS NULL AND P.OREO_EVENT_DATE IS NOT NULL
			  OR A.OREO_EVENT_DATE IS NOT NULL AND P.OREO_EVENT_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_EVENT_DATE,
	COALESCE(A.OREO_APPRAISAL_VALUE,0) - COALESCE(P.OREO_APPRAISAL_VALUE, 0) AS OREO_APPRAISAL_VALUE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_APPRAISAL_DATE <> P.OREO_APPRAISAL_DATE
			  OR A.OREO_APPRAISAL_DATE IS NULL AND P.OREO_APPRAISAL_DATE IS NOT NULL
			  OR A.OREO_APPRAISAL_DATE IS NOT NULL AND P.OREO_APPRAISAL_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_APPRAISAL_DATE,
	COALESCE(A.OREO_CURRENT_BAL_ACCUMULATOR,0) - COALESCE(P.OREO_CURRENT_BAL_ACCUMULATOR, 0) AS OREO_CURRENT_BAL_ACCUMULATOR,
	COALESCE(A.OREO_LOSS_ON_SALE,0) - COALESCE(P.OREO_LOSS_ON_SALE, 0) AS OREO_LOSS_ON_SALE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_PROJCTED_LIQUIDATION_DATE <> P.OREO_PROJCTED_LIQUIDATION_DATE
			  OR A.OREO_PROJCTED_LIQUIDATION_DATE IS NULL AND P.OREO_PROJCTED_LIQUIDATION_DATE IS NOT NULL
			  OR A.OREO_PROJCTED_LIQUIDATION_DATE IS NOT NULL AND P.OREO_PROJCTED_LIQUIDATION_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_PROJCTED_LIQUIDATION_DATE,
	COALESCE(A.OREO_LOAN_PRIN_BAL_PRPTY_REV,0) - COALESCE(P.OREO_LOAN_PRIN_BAL_PRPTY_REV, 0) AS OREO_LOAN_PRIN_BAL_PRPTY_REV,
	COALESCE(A.OREO_BEG_BAL_AT_CURRENT_YEAR,0) - COALESCE(P.OREO_BEG_BAL_AT_CURRENT_YEAR, 0) AS OREO_BEG_BAL_AT_CURRENT_YEAR,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_NOTES <> P.OREO_NOTES
			  OR A.OREO_NOTES IS NULL AND P.OREO_NOTES IS NOT NULL
			  OR A.OREO_NOTES IS NOT NULL AND P.OREO_NOTES IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_NOTES,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OREO_COMPANY <> P.OREO_COMPANY
			  OR A.OREO_COMPANY IS NULL AND P.OREO_COMPANY IS NOT NULL
			  OR A.OREO_COMPANY IS NOT NULL AND P.OREO_COMPANY IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OREO_COMPANY,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FORECLOSURE_START_DATE <> P.FORECLOSURE_START_DATE
			  OR A.FORECLOSURE_START_DATE IS NULL AND P.FORECLOSURE_START_DATE IS NOT NULL
			  OR A.FORECLOSURE_START_DATE IS NOT NULL AND P.FORECLOSURE_START_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FORECLOSURE_START_DATE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FORECLOSURE_SALE_DATE <> P.FORECLOSURE_SALE_DATE
			  OR A.FORECLOSURE_SALE_DATE IS NULL AND P.FORECLOSURE_SALE_DATE IS NOT NULL
			  OR A.FORECLOSURE_SALE_DATE IS NOT NULL AND P.FORECLOSURE_SALE_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FORECLOSURE_SALE_DATE,
	COALESCE(A.LOSS_SHARE_VALUE,0) - COALESCE(P.LOSS_SHARE_VALUE, 0) AS LOSS_SHARE_VALUE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.MATURITY_DATE <> P.MATURITY_DATE
			  OR A.MATURITY_DATE IS NULL AND P.MATURITY_DATE IS NOT NULL
			  OR A.MATURITY_DATE IS NOT NULL AND P.MATURITY_DATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS MATURITY_DATE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.MATURITY_BUCKETS <> P.MATURITY_BUCKETS
			  OR A.MATURITY_BUCKETS IS NULL AND P.MATURITY_BUCKETS IS NOT NULL
			  OR A.MATURITY_BUCKETS IS NOT NULL AND P.MATURITY_BUCKETS IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS MATURITY_BUCKETS,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.LOSS_SHARING_AGREEMENT_YN <> P.LOSS_SHARING_AGREEMENT_YN
			  OR A.LOSS_SHARING_AGREEMENT_YN IS NULL AND P.LOSS_SHARING_AGREEMENT_YN IS NOT NULL
			  OR A.LOSS_SHARING_AGREEMENT_YN IS NOT NULL AND P.LOSS_SHARING_AGREEMENT_YN IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS LOSS_SHARING_AGREEMENT_YN,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.SPV_YN <> P.SPV_YN
			  OR A.SPV_YN IS NULL AND P.SPV_YN IS NOT NULL
			  OR A.SPV_YN IS NOT NULL AND P.SPV_YN IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS SPV_YN,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.ABCP_CONDUITS_YN <> P.ABCP_CONDUITS_YN
			  OR A.ABCP_CONDUITS_YN IS NULL AND P.ABCP_CONDUITS_YN IS NOT NULL
			  OR A.ABCP_CONDUITS_YN IS NOT NULL AND P.ABCP_CONDUITS_YN IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS ABCP_CONDUITS_YN,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.VIE_YN <> P.VIE_YN
			  OR A.VIE_YN IS NULL AND P.VIE_YN IS NOT NULL
			  OR A.VIE_YN IS NOT NULL AND P.VIE_YN IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS VIE_YN,
	COALESCE(A.REGULATORY_RISK_RATINGS,0) - COALESCE(P.REGULATORY_RISK_RATINGS, 0) AS REGULATORY_RISK_RATINGS,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.LEVEL_FAIR_VALUE <> P.LEVEL_FAIR_VALUE
			  OR A.LEVEL_FAIR_VALUE IS NULL AND P.LEVEL_FAIR_VALUE IS NOT NULL
			  OR A.LEVEL_FAIR_VALUE IS NOT NULL AND P.LEVEL_FAIR_VALUE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS LEVEL_FAIR_VALUE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.ACCOUNT <> P.ACCOUNT
			  OR A.ACCOUNT IS NULL AND P.ACCOUNT IS NOT NULL
			  OR A.ACCOUNT IS NOT NULL AND P.ACCOUNT IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS ACCOUNT,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.PRODUCT <> P.PRODUCT
			  OR A.PRODUCT IS NULL AND P.PRODUCT IS NOT NULL
			  OR A.PRODUCT IS NOT NULL AND P.PRODUCT IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS PRODUCT,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.OPERATING_UNIT <> P.OPERATING_UNIT
			  OR A.OPERATING_UNIT IS NULL AND P.OPERATING_UNIT IS NOT NULL
			  OR A.OPERATING_UNIT IS NOT NULL AND P.OPERATING_UNIT IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS OPERATING_UNIT,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.AFFILIATE <> P.AFFILIATE
			  OR A.AFFILIATE IS NULL AND P.AFFILIATE IS NOT NULL
			  OR A.AFFILIATE IS NOT NULL AND P.AFFILIATE IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS AFFILIATE,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.CUST_CLASS <> P.CUST_CLASS
			  OR A.CUST_CLASS IS NULL AND P.CUST_CLASS IS NOT NULL
			  OR A.CUST_CLASS IS NOT NULL AND P.CUST_CLASS IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS CUST_CLASS,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.UMD1 <> P.UMD1
			  OR A.UMD1 IS NULL AND P.UMD1 IS NOT NULL
			  OR A.UMD1 IS NOT NULL AND P.UMD1 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS UMD1,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.UMD2 <> P.UMD2
			  OR A.UMD2 IS NULL AND P.UMD2 IS NOT NULL
			  OR A.UMD2 IS NOT NULL AND P.UMD2 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS UMD2,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.UMD3 <> P.UMD3
			  OR A.UMD3 IS NULL AND P.UMD3 IS NOT NULL
			  OR A.UMD3 IS NOT NULL AND P.UMD3 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS UMD3,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.UMD4 <> P.UMD4
			  OR A.UMD4 IS NULL AND P.UMD4 IS NOT NULL
			  OR A.UMD4 IS NOT NULL AND P.UMD4 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS UMD4,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.UMD5 <> P.UMD5
			  OR A.UMD5 IS NULL AND P.UMD5 IS NOT NULL
			  OR A.UMD5 IS NOT NULL AND P.UMD5 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS UMD5,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_1 <> P.FILLER_1
			  OR A.FILLER_1 IS NULL AND P.FILLER_1 IS NOT NULL
			  OR A.FILLER_1 IS NOT NULL AND P.FILLER_1 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_1,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_2 <> P.FILLER_2
			  OR A.FILLER_2 IS NULL AND P.FILLER_2 IS NOT NULL
			  OR A.FILLER_2 IS NOT NULL AND P.FILLER_2 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_2,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_3 <> P.FILLER_3
			  OR A.FILLER_3 IS NULL AND P.FILLER_3 IS NOT NULL
			  OR A.FILLER_3 IS NOT NULL AND P.FILLER_3 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_3,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_4 <> P.FILLER_4
			  OR A.FILLER_4 IS NULL AND P.FILLER_4 IS NOT NULL
			  OR A.FILLER_4 IS NOT NULL AND P.FILLER_4 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_4,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_5 <> P.FILLER_5
			  OR A.FILLER_5 IS NULL AND P.FILLER_5 IS NOT NULL
			  OR A.FILLER_5 IS NOT NULL AND P.FILLER_5 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_5,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_6 <> P.FILLER_6
			  OR A.FILLER_6 IS NULL AND P.FILLER_6 IS NOT NULL
			  OR A.FILLER_6 IS NOT NULL AND P.FILLER_6 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_6,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_7 <> P.FILLER_7
			  OR A.FILLER_7 IS NULL AND P.FILLER_7 IS NOT NULL
			  OR A.FILLER_7 IS NOT NULL AND P.FILLER_7 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_7,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_8 <> P.FILLER_8
			  OR A.FILLER_8 IS NULL AND P.FILLER_8 IS NOT NULL
			  OR A.FILLER_8 IS NOT NULL AND P.FILLER_8 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_8,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_9 <> P.FILLER_9
			  OR A.FILLER_9 IS NULL AND P.FILLER_9 IS NOT NULL
			  OR A.FILLER_9 IS NOT NULL AND P.FILLER_9 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_9,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_10 <> P.FILLER_10
			  OR A.FILLER_10 IS NULL AND P.FILLER_10 IS NOT NULL
			  OR A.FILLER_10 IS NOT NULL AND P.FILLER_10 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_10,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_11 <> P.FILLER_11
			  OR A.FILLER_11 IS NULL AND P.FILLER_11 IS NOT NULL
			  OR A.FILLER_11 IS NOT NULL AND P.FILLER_11 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_11,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_12 <> P.FILLER_12
			  OR A.FILLER_12 IS NULL AND P.FILLER_12 IS NOT NULL
			  OR A.FILLER_12 IS NOT NULL AND P.FILLER_12 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_12,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_13 <> P.FILLER_13
			  OR A.FILLER_13 IS NULL AND P.FILLER_13 IS NOT NULL
			  OR A.FILLER_13 IS NOT NULL AND P.FILLER_13 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_13,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_14 <> P.FILLER_14
			  OR A.FILLER_14 IS NULL AND P.FILLER_14 IS NOT NULL
			  OR A.FILLER_14 IS NOT NULL AND P.FILLER_14 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_14,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_15 <> P.FILLER_15
			  OR A.FILLER_15 IS NULL AND P.FILLER_15 IS NOT NULL
			  OR A.FILLER_15 IS NOT NULL AND P.FILLER_15 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_15,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_16 <> P.FILLER_16
			  OR A.FILLER_16 IS NULL AND P.FILLER_16 IS NOT NULL
			  OR A.FILLER_16 IS NOT NULL AND P.FILLER_16 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_16,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_17 <> P.FILLER_17
			  OR A.FILLER_17 IS NULL AND P.FILLER_17 IS NOT NULL
			  OR A.FILLER_17 IS NOT NULL AND P.FILLER_17 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_17,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_18 <> P.FILLER_18
			  OR A.FILLER_18 IS NULL AND P.FILLER_18 IS NOT NULL
			  OR A.FILLER_18 IS NOT NULL AND P.FILLER_18 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_18,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_19 <> P.FILLER_19
			  OR A.FILLER_19 IS NULL AND P.FILLER_19 IS NOT NULL
			  OR A.FILLER_19 IS NOT NULL AND P.FILLER_19 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_19,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_20 <> P.FILLER_20
			  OR A.FILLER_20 IS NULL AND P.FILLER_20 IS NOT NULL
			  OR A.FILLER_20 IS NOT NULL AND P.FILLER_20 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_20,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_21 <> P.FILLER_21
			  OR A.FILLER_21 IS NULL AND P.FILLER_21 IS NOT NULL
			  OR A.FILLER_21 IS NOT NULL AND P.FILLER_21 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_21,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_22 <> P.FILLER_22
			  OR A.FILLER_22 IS NULL AND P.FILLER_22 IS NOT NULL
			  OR A.FILLER_22 IS NOT NULL AND P.FILLER_22 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_22,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_23 <> P.FILLER_23
			  OR A.FILLER_23 IS NULL AND P.FILLER_23 IS NOT NULL
			  OR A.FILLER_23 IS NOT NULL AND P.FILLER_23 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_23,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_24 <> P.FILLER_24
			  OR A.FILLER_24 IS NULL AND P.FILLER_24 IS NOT NULL
			  OR A.FILLER_24 IS NOT NULL AND P.FILLER_24 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_24,
	CASE
		WHEN A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('OLD' AS VARCHAR(8))
	   WHEN P.INSTRUMENT_ID IS NULL AND A.INSTRUMENT_ID IS NOT NULL
		  THEN CAST('NEW' AS VARCHAR(8))
		WHEN  A.FILLER_25 <> P.FILLER_25
			  OR A.FILLER_25 IS NULL AND P.FILLER_25 IS NOT NULL
			  OR A.FILLER_25 IS NOT NULL AND P.FILLER_25 IS NULL
		  THEN CAST('VARIANCE' AS VARCHAR(8))
		ELSE CAST('OK' AS VARCHAR(8))
	  END AS FILLER_25
FROM
(
  SELECT
    ROW_NUMBER() OVER (PARTITION BY
      H.REPORTING_ENTITY,
      H.INSTRUMENT_ID
      ORDER BY
		H."INTERCOMPANY",
		H."CONSOL_NODE",
		H."BUSINESS_UNIT",
		H."GL_KEY_CODE",
		H."GL_KEY_CODE_DESC",
		H."CALL_CODE",
		H."CALL_CODE_DESC",
		H."LOAN_NUMBER",
		H."CONVERTED_INSTRUMENT_ID",
		H."CALL_CODE_LOOKUP",
		H."CURRENT_OREO_ASSET_NUMBER",
		H."ENTITY_CHANGE",
		H."DUPLICATE_LOAN_ON_ONE_PROPERTY",
		H."FORECLOSURE_INDICATOR_DESCRPTN",
		H."OREO_NEW_OREO_EVENT",
		H."OREO_COST_CENTER",
		H."OREO_INDICATOR",
		H."OREO_NET_LIDQUIDATION_PROCEEDS",
		H."OREO_NET_LIDQUIDATION_AMT",
		H."OREO_SALE_DATE",
		H."OREO_OFFSET_TO_CHARGE_OFF",
		H."OREO_OPER_EXP_CLOSING_STMT",
		H."OREO_VALUATION_ADJUSTMENT",
		H."OREO_FINAL_SALE",
		H."OREO_EVENT_DATE",
		H."OREO_APPRAISAL_VALUE",
		H."OREO_APPRAISAL_DATE",
		H."OREO_CURRENT_BAL_ACCUMULATOR",
		H."OREO_LOSS_ON_SALE",
		H."OREO_PROJCTED_LIQUIDATION_DATE",
		H."OREO_LOAN_PRIN_BAL_PRPTY_REV",
		H."OREO_BEG_BAL_AT_CURRENT_YEAR",
		H."OREO_NOTES",
		H."OREO_COMPANY",
		H."FORECLOSURE_START_DATE",
		H."FORECLOSURE_SALE_DATE",
		H."LOSS_SHARE_VALUE",
		H."MATURITY_DATE",
		H."MATURITY_BUCKETS",
		H."LOSS_SHARING_AGREEMENT_YN",
		H."SPV_YN",
		H."ABCP_CONDUITS_YN",
		H."VIE_YN",
		H."REGULATORY_RISK_RATINGS",
		H."LEVEL_FAIR_VALUE",
		H."ACCOUNT",
		H."PRODUCT",
		H."OPERATING_UNIT",
		H."AFFILIATE",
		H."CUST_CLASS",
		H."UMD1",
		H."UMD2",
		H."UMD3",
		H."UMD4",
		H."UMD5",
		H."FILLER_1",
		H."FILLER_2",
		H."FILLER_3",
		H."FILLER_4",
		H."FILLER_5",
		H."FILLER_6",
		H."FILLER_7",
		H."FILLER_8",
		H."FILLER_9",
		H."FILLER_10",
		H."FILLER_11",
		H."FILLER_12",
		H."FILLER_13",
		H."FILLER_14",
		H."FILLER_15",
		H."FILLER_16",
		H."FILLER_17",
		H."FILLER_18",
		H."FILLER_19",
		H."FILLER_20",
		H."FILLER_21",
		H."FILLER_22",
		H."FILLER_23",
		H."FILLER_24",
		H."FILLER_25"
    ) AS ROW_ID,
	REPORTING_ENTITY,
	INSTRUMENT_ID,
	"INTERCOMPANY",
	"CONSOL_NODE",
	H."BUSINESS_UNIT",
	"GL_KEY_CODE",
	"GL_KEY_CODE_DESC",
	"CALL_CODE",
	"CALL_CODE_DESC",
	"LOAN_NUMBER",
	"CONVERTED_INSTRUMENT_ID",
	"CALL_CODE_LOOKUP",
	"CURRENT_OREO_ASSET_NUMBER",
	"ENTITY_CHANGE",
	"DUPLICATE_LOAN_ON_ONE_PROPERTY",
	"FORECLOSURE_INDICATOR_DESCRPTN",
	"OREO_NEW_OREO_EVENT",
	"OREO_COST_CENTER",
	"OREO_INDICATOR",
	"OREO_NET_LIDQUIDATION_PROCEEDS",
	"OREO_NET_LIDQUIDATION_AMT",
	"OREO_SALE_DATE",
	"OREO_OFFSET_TO_CHARGE_OFF",
	"OREO_OPER_EXP_CLOSING_STMT",
	"OREO_VALUATION_ADJUSTMENT",
	"OREO_FINAL_SALE",
	"OREO_EVENT_DATE",
	"OREO_APPRAISAL_VALUE",
	"OREO_APPRAISAL_DATE",
	"OREO_CURRENT_BAL_ACCUMULATOR",
	"OREO_LOSS_ON_SALE",
	"OREO_PROJCTED_LIQUIDATION_DATE",
	"OREO_LOAN_PRIN_BAL_PRPTY_REV",
	"OREO_BEG_BAL_AT_CURRENT_YEAR",
	"OREO_NOTES",
	"OREO_COMPANY",
	"FORECLOSURE_START_DATE",
	"FORECLOSURE_SALE_DATE",
	"LOSS_SHARE_VALUE",
	"MATURITY_DATE",
	"MATURITY_BUCKETS",
	"LOSS_SHARING_AGREEMENT_YN",
	"SPV_YN",
	"ABCP_CONDUITS_YN",
	"VIE_YN",
	"REGULATORY_RISK_RATINGS",
	"LEVEL_FAIR_VALUE",
	"ACCOUNT",
	"PRODUCT",
	"OPERATING_UNIT",
	"AFFILIATE",
	"CUST_CLASS",
	"UMD1",
	"UMD2",
	"UMD3",
	"UMD4",
	"UMD5",
	"FILLER_1",
	"FILLER_2",
	"FILLER_3",
	"FILLER_4",
	"FILLER_5",
	"FILLER_6",
	"FILLER_7",
	"FILLER_8",
	"FILLER_9",
	"FILLER_10",
	"FILLER_11",
	"FILLER_12",
	"FILLER_13",
	"FILLER_14",
	"FILLER_15",
	"FILLER_16",
	"FILLER_17",
	"FILLER_18",
	"FILLER_19",
	"FILLER_20",
	"FILLER_21",
	"FILLER_22",
	"FILLER_23",
	"FILLER_24",
	"FILLER_25"
	FROM
    RB_V_OREO H
    INNER JOIN
    (
      SELECT DISTINCT
        DATA_1 AS MONTH_END_DATE,
        COD_AZIENDA AS BUSINESS_UNIT
      FROM
        FORM_DATI
      WHERE
        COD_SCENARIO = ${A1}
        AND COD_PERIODO = ${B1}
        AND COD_PROSPETTO = 'OREO'
        AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )
    ) F
   ON
     H.MONTH_END_DATE = F.MONTH_END_DATE
     AND RB_F_TGK_SANITIZE_CODE(H.BUSINESS_UNIT) = F.BUSINESS_UNIT
  ) A
FULL OUTER JOIN
(
  SELECT
    ROW_NUMBER() OVER (PARTITION BY
      H.REPORTING_ENTITY,
      H.INSTRUMENT_ID
      ORDER BY
		H."INTERCOMPANY",
		H."CONSOL_NODE",
		H."BUSINESS_UNIT",
		H."GL_KEY_CODE",
		H."GL_KEY_CODE_DESC",
		H."CALL_CODE",
		H."CALL_CODE_DESC",
		H."LOAN_NUMBER",
		H."CONVERTED_INSTRUMENT_ID",
		H."CALL_CODE_LOOKUP",
		H."CURRENT_OREO_ASSET_NUMBER",
		H."ENTITY_CHANGE",
		H."DUPLICATE_LOAN_ON_ONE_PROPERTY",
		H."FORECLOSURE_INDICATOR_DESCRPTN",
		H."OREO_NEW_OREO_EVENT",
		H."OREO_COST_CENTER",
		H."OREO_INDICATOR",
		H."OREO_NET_LIDQUIDATION_PROCEEDS",
		H."OREO_NET_LIDQUIDATION_AMT",
		H."OREO_SALE_DATE",
		H."OREO_OFFSET_TO_CHARGE_OFF",
		H."OREO_OPER_EXP_CLOSING_STMT",
		H."OREO_VALUATION_ADJUSTMENT",
		H."OREO_FINAL_SALE",
		H."OREO_EVENT_DATE",
		H."OREO_APPRAISAL_VALUE",
		H."OREO_APPRAISAL_DATE",
		H."OREO_CURRENT_BAL_ACCUMULATOR",
		H."OREO_LOSS_ON_SALE",
		H."OREO_PROJCTED_LIQUIDATION_DATE",
		H."OREO_LOAN_PRIN_BAL_PRPTY_REV",
		H."OREO_BEG_BAL_AT_CURRENT_YEAR",
		H."OREO_NOTES",
		H."OREO_COMPANY",
		H."FORECLOSURE_START_DATE",
		H."FORECLOSURE_SALE_DATE",
		H."LOSS_SHARE_VALUE",
		H."MATURITY_DATE",
		H."MATURITY_BUCKETS",
		H."LOSS_SHARING_AGREEMENT_YN",
		H."SPV_YN",
		H."ABCP_CONDUITS_YN",
		H."VIE_YN",
		H."REGULATORY_RISK_RATINGS",
		H."LEVEL_FAIR_VALUE",
		H."ACCOUNT",
		H."PRODUCT",
		H."OPERATING_UNIT",
		H."AFFILIATE",
		H."CUST_CLASS",
		H."UMD1",
		H."UMD2",
		H."UMD3",
		H."UMD4",
		H."UMD5",
		H."FILLER_1",
		H."FILLER_2",
		H."FILLER_3",
		H."FILLER_4",
		H."FILLER_5",
		H."FILLER_6",
		H."FILLER_7",
		H."FILLER_8",
		H."FILLER_9",
		H."FILLER_10",
		H."FILLER_11",
		H."FILLER_12",
		H."FILLER_13",
		H."FILLER_14",
		H."FILLER_15",
		H."FILLER_16",
		H."FILLER_17",
		H."FILLER_18",
		H."FILLER_19",
		H."FILLER_20",
		H."FILLER_21",
		H."FILLER_22",
		H."FILLER_23",
		H."FILLER_24",
		H."FILLER_25"
    ) AS ROW_ID,
	REPORTING_ENTITY,
	INSTRUMENT_ID,
	"INTERCOMPANY",
	"CONSOL_NODE",
	H."BUSINESS_UNIT",
	"GL_KEY_CODE",
	"GL_KEY_CODE_DESC",
	"CALL_CODE",
	"CALL_CODE_DESC",
	"LOAN_NUMBER",
	"CONVERTED_INSTRUMENT_ID",
	"CALL_CODE_LOOKUP",
	"CURRENT_OREO_ASSET_NUMBER",
	"ENTITY_CHANGE",
	"DUPLICATE_LOAN_ON_ONE_PROPERTY",
	"FORECLOSURE_INDICATOR_DESCRPTN",
	"OREO_NEW_OREO_EVENT",
	"OREO_COST_CENTER",
	"OREO_INDICATOR",
	"OREO_NET_LIDQUIDATION_PROCEEDS",
	"OREO_NET_LIDQUIDATION_AMT",
	"OREO_SALE_DATE",
	"OREO_OFFSET_TO_CHARGE_OFF",
	"OREO_OPER_EXP_CLOSING_STMT",
	"OREO_VALUATION_ADJUSTMENT",
	"OREO_FINAL_SALE",
	"OREO_EVENT_DATE",
	"OREO_APPRAISAL_VALUE",
	"OREO_APPRAISAL_DATE",
	"OREO_CURRENT_BAL_ACCUMULATOR",
	"OREO_LOSS_ON_SALE",
	"OREO_PROJCTED_LIQUIDATION_DATE",
	"OREO_LOAN_PRIN_BAL_PRPTY_REV",
	"OREO_BEG_BAL_AT_CURRENT_YEAR",
	"OREO_NOTES",
	"OREO_COMPANY",
	"FORECLOSURE_START_DATE",
	"FORECLOSURE_SALE_DATE",
	"LOSS_SHARE_VALUE",
	"MATURITY_DATE",
	"MATURITY_BUCKETS",
	"LOSS_SHARING_AGREEMENT_YN",
	"SPV_YN",
	"ABCP_CONDUITS_YN",
	"VIE_YN",
	"REGULATORY_RISK_RATINGS",
	"LEVEL_FAIR_VALUE",
	"ACCOUNT",
	"PRODUCT",
	"OPERATING_UNIT",
	"AFFILIATE",
	"CUST_CLASS",
	"UMD1",
	"UMD2",
	"UMD3",
	"UMD4",
	"UMD5",
	"FILLER_1",
	"FILLER_2",
	"FILLER_3",
	"FILLER_4",
	"FILLER_5",
	"FILLER_6",
	"FILLER_7",
	"FILLER_8",
	"FILLER_9",
	"FILLER_10",
	"FILLER_11",
	"FILLER_12",
	"FILLER_13",
	"FILLER_14",
	"FILLER_15",
	"FILLER_16",
	"FILLER_17",
	"FILLER_18",
	"FILLER_19",
	"FILLER_20",
	"FILLER_21",
	"FILLER_22",
	"FILLER_23",
	"FILLER_24",
	"FILLER_25"
  FROM
    RB_V_OREO H
    INNER JOIN
    (
      SELECT DISTINCT
        DATA_1 AS MONTH_END_DATE,
        COD_AZIENDA AS BUSINESS_UNIT
      FROM
        FORM_DATI
      WHERE
        COD_SCENARIO = ${A2}
        AND COD_PERIODO = ${B2}
        AND COD_PROSPETTO = 'OREO'
        AND COD_AZIENDA IN (
              SELECT
                COD_AZIENDA
              FROM
                UTENTE_AZIENDA
              WHERE
                FLAG_INSERIMENTO_DATI = 1
                AND COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND COD_UTENTE = ${USER.CODE}
              UNION
              SELECT
                A.COD_AZIENDA
              FROM
                UTENTE U,
                AZIENDA_GERARCHIA_ABBI A
              WHERE
                U.TIPO_LIM_AZIENDA = 'X'
                AND A.COD_AZIENDA_GERARCHIA = (SELECT COD_AZIENDA_GERARCHIA FROM RACCOLTA WHERE COD_RACCOLTA = 'ACT')
                AND U.COD_UTENTE = ${USER.CODE}
          )
    ) F
   ON
     H.MONTH_END_DATE = F.MONTH_END_DATE
     AND RB_F_TGK_SANITIZE_CODE(H.BUSINESS_UNIT) = F.BUSINESS_UNIT
  ) P
ON
  A.ROW_ID = P.ROW_ID
  AND A.REPORTING_ENTITY = P.REPORTING_ENTITY
  AND (A.INSTRUMENT_ID = P.INSTRUMENT_ID OR (A.INSTRUMENT_ID IS NULL AND P.INSTRUMENT_ID IS NULL))