CREATE OR REPLACE FUNCTION RB_F_TGK_LINEITEM_TO_ACCOUNT (
  LINEITEM IN VARCHAR2,
  HIERARCHY_CODE IN VARCHAR2,
  HIERARCHY_NODE_CODE IN VARCHAR2
)
RETURN VARCHAR2 IS
  COD_CONTO VARCHAR2(30);

BEGIN

  SELECT
    COD_CONTO INTO RB_F_TGK_LINEITEM_TO_ACCOUNT.COD_CONTO
  FROM
    CONTO C
    INNER JOIN
    TABLE(RB_F_TGK_GET_LEAVES_ACCOUNT (HIERARCHY_CODE, HIERARCHY_NODE_CODE)) T
    ON
      C.COD_CONTO = T.COLUMN_VALUE
  WHERE
    C.ATTRIBUTO3 = LINEITEM
  ;
  
  RETURN(RB_F_TGK_LINEITEM_TO_ACCOUNT.COD_CONTO);
  
END;