CREATE OR REPLACE FUNCTION RB_F_TGK_DUMMYENTITY_TO_NODE (
  DUMMY_ENTITY IN VARCHAR2
)
RETURN VARCHAR2 IS
  HIERARCHY_NODE VARCHAR2(30);

BEGIN

  SELECT
    ATTRIBUTO4 INTO RB_F_TGK_DUMMYENTITY_TO_NODE.HIERARCHY_NODE
  FROM
    AZIENDA
  WHERE
    COD_AZIENDA = RB_F_TGK_DUMMYENTITY_TO_NODE.DUMMY_ENTITY
  ;
  
  RETURN(RB_F_TGK_DUMMYENTITY_TO_NODE.HIERARCHY_NODE);
  
END;