--------------------------------------------------------
--  DDL for FUNCTION RB_F_TGK_GET_ACCOUNT_NODE
--------------------------------------------------------

CREATE OR REPLACE FUNCTION RB_F_TGK_GET_ACCOUNT_NODE (
  COD_CONTO IN VARCHAR2,
  HIERARCHY_CODE IN VARCHAR2,
  HIERARCHY_LEVEL IN INT
)
RETURN VARCHAR2 IS
--  This function returns the node at level HIERARCHY_LEVEL
--  in hierarchy HIERARCHY_CODE for Business Unit COD_AZIENDA
  HIERARCHY_NODE VARCHAR2(30);
BEGIN

  SELECT
    H.COD_CONTO_ELEGER INTO RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_NODE
  FROM
    (
      SELECT
        COD_CONTO_GERARCHIA,
        COD_CONTO_ELEGER,
        LEVEL AS "LEVEL"
      FROM
        (
          SELECT 
            COD_CONTO_GERARCHIA,
            COD_CONTO_ELEGER,
            COD_CONTO_ELEGER_PADRE
          FROM
            CONTO_GERARCHIA
          WHERE
            COD_CONTO_GERARCHIA = RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_CODE
        )
      START WITH COD_CONTO_ELEGER = (
        SELECT
          COD_CONTO_ELEGER
        FROM
          CONTO_GERARCHIA_ABBI
        WHERE
              COD_CONTO_GERARCHIA = RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_CODE
          AND COD_CONTO = RB_F_TGK_GET_ACCOUNT_NODE.COD_CONTO
      )
      CONNECT BY PRIOR COD_CONTO_ELEGER_PADRE = COD_CONTO_ELEGER
    ) H,
    (
      SELECT
        MAX(LEVEL) AS "LEVEL"
      FROM
        (
          SELECT 
            COD_CONTO_GERARCHIA,
            COD_CONTO_ELEGER,
            COD_CONTO_ELEGER_PADRE
          FROM
            CONTO_GERARCHIA
          WHERE
            COD_CONTO_GERARCHIA = RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_CODE
        )
      START WITH COD_CONTO_ELEGER = (
        SELECT
          COD_CONTO_ELEGER
        FROM
          CONTO_GERARCHIA_ABBI
        WHERE
              COD_CONTO_GERARCHIA = RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_CODE
          AND COD_CONTO = RB_F_TGK_GET_ACCOUNT_NODE.COD_CONTO
      )
      CONNECT BY PRIOR COD_CONTO_ELEGER_PADRE = COD_CONTO_ELEGER
    ) M
  WHERE
    M."LEVEL" - H."LEVEL" + 1 = RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_LEVEL
	OR - H."LEVEL" = RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_LEVEL
  ;
  
  RETURN(RB_F_TGK_GET_ACCOUNT_NODE.HIERARCHY_NODE);
END;