--------------------------------------------------------
--  DDL for FUNCTION RB_F_TGK_GET_BU_NODE
--------------------------------------------------------

CREATE OR REPLACE FUNCTION RB_F_TGK_GET_BU_NODE (
  COD_AZIENDA IN VARCHAR2,
  HIERARCHY_CODE IN VARCHAR2,
  HIERARCHY_LEVEL IN INT
)
RETURN VARCHAR2 IS
--  This function returns the node at level HIERARCHY_LEVEL
--  in hierarchy HIERARCHY_CODE for Business Unit COD_AZIENDA
  HIERARCHY_NODE VARCHAR2(30);
BEGIN

  SELECT
    H.COD_AZIENDA_ELEGER INTO RB_F_TGK_GET_BU_NODE.HIERARCHY_NODE
  FROM
    (
      SELECT
        COD_AZIENDA_GERARCHIA,
        COD_AZIENDA_ELEGER,
        LEVEL AS "LEVEL"
      FROM
        (
          SELECT 
            COD_AZIENDA_GERARCHIA,
            COD_AZIENDA_ELEGER,
            COD_AZIENDA_ELEGER_PADRE
          FROM
            AZIENDA_GERARCHIA
          WHERE
            COD_AZIENDA_GERARCHIA = RB_F_TGK_GET_BU_NODE.HIERARCHY_CODE
        )
      START WITH COD_AZIENDA_ELEGER = (
        SELECT
          COD_AZIENDA_ELEGER
        FROM
          AZIENDA_GERARCHIA_ABBI
        WHERE
              COD_AZIENDA_GERARCHIA = RB_F_TGK_GET_BU_NODE.HIERARCHY_CODE
          AND COD_AZIENDA = RB_F_TGK_GET_BU_NODE.COD_AZIENDA
      )
      CONNECT BY PRIOR COD_AZIENDA_ELEGER_PADRE = COD_AZIENDA_ELEGER
    ) H,
    (
      SELECT
        MAX(LEVEL) AS "LEVEL"
      FROM
        (
          SELECT 
            COD_AZIENDA_GERARCHIA,
            COD_AZIENDA_ELEGER,
            COD_AZIENDA_ELEGER_PADRE
          FROM
            AZIENDA_GERARCHIA
          WHERE
            COD_AZIENDA_GERARCHIA = RB_F_TGK_GET_BU_NODE.HIERARCHY_CODE
        )
      START WITH COD_AZIENDA_ELEGER = (
        SELECT
          COD_AZIENDA_ELEGER
        FROM
          AZIENDA_GERARCHIA_ABBI
        WHERE
              COD_AZIENDA_GERARCHIA = RB_F_TGK_GET_BU_NODE.HIERARCHY_CODE
          AND COD_AZIENDA = RB_F_TGK_GET_BU_NODE.COD_AZIENDA
      )
      CONNECT BY PRIOR COD_AZIENDA_ELEGER_PADRE = COD_AZIENDA_ELEGER
    ) M
  WHERE
    M."LEVEL" - H."LEVEL" + 1 = RB_F_TGK_GET_BU_NODE.HIERARCHY_LEVEL
  ;
  
  RETURN(RB_F_TGK_GET_BU_NODE.HIERARCHY_NODE);
END;