--------------------------------------------------------
--  DDL for FUNCTION RB_F_TGK_GET_BU_HIERARCHY
--------------------------------------------------------

CREATE OR REPLACE FUNCTION RB_F_TGK_GET_BU_HIERARCHY (
  COD_AZIENDA IN VARCHAR2,
  HIERARCHY_CODE IN VARCHAR2
)
RETURN VARCHAR2 IS
--  This function returns the Tree Structure in hierarchy HIERARCHY_CODE
--  for Business Unit COD_AZIENDA
  HIERARCHY_STRUCTURE VARCHAR2(4000);
BEGIN

  SELECT
        '||' || LISTAGG(COD_AZIENDA_ELEGER, '||') WITHIN GROUP (ORDER BY LEVEL DESC) || '||' INTO RB_F_TGK_GET_BU_HIERARCHY.HIERARCHY_STRUCTURE
      FROM
        (
          SELECT 
            COD_AZIENDA_GERARCHIA,
            COD_AZIENDA_ELEGER,
            COD_AZIENDA_ELEGER_PADRE
          FROM
            AZIENDA_GERARCHIA
          WHERE
            COD_AZIENDA_GERARCHIA = RB_F_TGK_GET_BU_HIERARCHY.HIERARCHY_CODE
        )
      START WITH COD_AZIENDA_ELEGER = (
        SELECT
          COD_AZIENDA_ELEGER
        FROM
          AZIENDA_GERARCHIA_ABBI
        WHERE
              COD_AZIENDA_GERARCHIA = RB_F_TGK_GET_BU_HIERARCHY.HIERARCHY_CODE
          AND COD_AZIENDA = RB_F_TGK_GET_BU_HIERARCHY.COD_AZIENDA
      )
      CONNECT BY PRIOR COD_AZIENDA_ELEGER_PADRE = COD_AZIENDA_ELEGER
  ;
  
  RETURN(RB_F_TGK_GET_BU_HIERARCHY.HIERARCHY_STRUCTURE);
END