create or replace FUNCTION RB_F_TGK_GET_ACCOUNT_HIERARCHY (
  COD_CONTO IN VARCHAR2,
  HIERARCHY_CODE IN VARCHAR2
)
RETURN VARCHAR2 IS
--  This function returns the Tree Structure in hierarchy HIERARCHY_CODE
--  for ACCOUNT COD_CONTO
  HIERARCHY_STRUCTURE VARCHAR2(4000);
BEGIN

  SELECT
        '||' || LISTAGG(COD_CONTO_ELEGER, '||') WITHIN GROUP (ORDER BY LEVEL DESC) || '||' INTO RB_F_TGK_GET_ACCOUNT_HIERARCHY.HIERARCHY_STRUCTURE
      FROM
        (
          SELECT 
            COD_CONTO_GERARCHIA,
            COD_CONTO_ELEGER,
            COD_CONTO_ELEGER_PADRE
          FROM
            CONTO_GERARCHIA
          WHERE
            COD_CONTO_GERARCHIA = RB_F_TGK_GET_ACCOUNT_HIERARCHY.HIERARCHY_CODE
        )
      START WITH COD_CONTO_ELEGER = (
        SELECT
          COD_CONTO_ELEGER
        FROM
          CONTO_GERARCHIA_ABBI
        WHERE
              COD_CONTO_GERARCHIA = RB_F_TGK_GET_ACCOUNT_HIERARCHY.HIERARCHY_CODE
          AND COD_CONTO = RB_F_TGK_GET_ACCOUNT_HIERARCHY.COD_CONTO
      )
      CONNECT BY PRIOR COD_CONTO_ELEGER_PADRE = COD_CONTO_ELEGER
  ;
  
  RETURN(RB_F_TGK_GET_ACCOUNT_HIERARCHY.HIERARCHY_STRUCTURE);
END;